### ISSUE TITLE
import fails, package points to external directory

### ISSUE THREAD

**Issue by bsheese** [raphaelvallat/pingouin#1]
importing pingouin returns the following: 

---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
<ipython-input-1-f0ef7192de11> in <module>()
      1 import pandas as pd
      2 import numpy as np
----> 3 import pingouin

~/.local/lib/python3.6/site-packages/pingouin/__init__.py in <module>()
      1 # Import pingouin objects
----> 2 from .utils import *
      3 from .bayesian import *
      4 from .effsize import *
      5 from .multicomp import *

~/.local/lib/python3.6/site-packages/pingouin/utils.py in <module>()
      3 import numpy as np
      4 from six import string_types
----> 5 from pingouin.external.tabulate import tabulate
      6 import pandas as pd
      7 

ModuleNotFoundError: No module named 'pingouin.external'

**Comment by raphaelvallat** [comment]
Hi @bsheese ! I am so sorry for only seeing your message today; I unfortunately did not get notified that a new issue had been opened.
I have fixed the pingouin.external import error in the latest Pingouin release (v0.1.4). Updating your version should solve the problem: 

`pip install pingouin --upgrade`

Thanks,
Raphael

**Comment by Grecia616** [comment]
> 

Sorry, in this case, how can I call the module? 

I already installed as pip install pingouin, but when I want to use it for example:

pingouin.wilcoxon(supermarket['GenderDummy'], supermarket['Quantity']) 

it said: 

NameError: name 'pingouin' is not defined


Thank you!

**Comment by raphaelvallat** [comment]
Hi @Grecia616,

Make sure to import pingouin in your code:

```import pingouin
pingouin.wilcoxon
```

If it doesn't work, there is a problem with your installation of pingouin. I would then re-install: `pip uninstall pingouin` followed by `pip install pingouin` in a terminal.

Thanks,
Raphael
