### ISSUE TITLE
Two way within-subject ANOVA

### ISSUE THREAD

**Issue by PanBartosz** [raphaelvallat/pingouin#10]
Hello,
one small problem: rm_anova collapses multiple observation for each subject and condition to mean (which is correct behavior) but if you have 2 within subject factors this function runs rm_anova2 which does not. Due to this fact when you run rm_anova with two within-subject variables it returns wrong value. If you do agree I can submit a pull request - as far as i can see the fix is to collapse values to a mean and THEN run rm_anova2.

**Comment by raphaelvallat** [comment]
Hi @PanBartosz!

Indeed, I agree with you that we should also do an automatic collapsing to the mean for `rm_anova2()`.  The collapsing should be done in this latter function and not in the `rm_anova()`. Please do feel free to submit a PR, that would be greatly appreciated. Since I've made quite a lot of changes on several functions for the next release, I'd recommend that you submit it on the develop branch and not the master.

Thanks,
Raphael

**Comment by PanBartosz** [comment]
Cool! Tomorrow I will add it and make a PR.

By the way: what do you think about implementing following statistical techniques in Pingouin:
1. Power analysis for chi suqare test of independence
2. Effect size for RxC tables (Phi and Cramer's V)
2. Some reliability measures (inter-rater reliability and Cronbach alpha)

To be honest I absolutely love Pingouin as a outputting-beatiful-and-informative-tables-for-experimental-reports Python package but my field of work i frequently use aforementioned techniques and it would be great to have it implemented in Python in one simple to use package. I will write some tests against R (`pwr` library nad `irr` library). What do you think?

**Comment by raphaelvallat** [comment]
That would be great! These are not tests that I use in my field but if you think that this can be useful to you and others then please do feel free to submit PRs. And it's fantastic if you can also write some tests against R. I really want Pingouin to be a community-driven package so thank you for all this, I really appreciate!
Raphael

**Comment by raphaelvallat** [comment]
Hi @PanBartosz !
Is there any chance that you can submit the PR for the rm_anova2 collapsing to the mean by the end of the week? I'd love to include it in the soon-to-come new release of Pingouin. If you don't have the time, just let me know and I'll make the changes!
Thanks - Raphael

**Comment by raphaelvallat** [comment]
Hi @PanBartosz ! Ok I've addded it in commit 33e36761d1d26b156fe9a93bddb20cb35f5b8476, this will be included in the soon to come next release of Pingouin. Please feel free to submit PRs for the functions that you have mentionned above (power analysis, reliability, etc).

Thank you again for your input!
