### ISSUE TITLE
Get all factor combinations in mixed designs

### ISSUE THREAD

**Issue by sappelhoff** [raphaelvallat/pingouin#102]
I have mixed design data with some subjects, one within, and one between factor similar to this:

![image](https://user-images.githubusercontent.com/9084751/85136035-4cd60680-b23f-11ea-8fca-521f6ad37223.png)

With pingouin, I can calculate a mixed anova and afterwards some pairwise ttests, which is very nice (thanks!). :-)

I have an issue with the pairwise ttests: the tested effects are always in this order (as also described in the docstring):

1. within
1. between
1. within * between

... however, I'd also like to see the `between * within` comparison.

Is there a way to do this that I don't see? Or can this be included in future versions of pingouin?

# Minimal working example

INPUT 

```Python
# Create mixed design data for 20 subjects
n = 40
within = np.tile(['a','b'], int(n/2))
between = np.tile(['c', 'c', 'd', 'd'], int(n/4))
vals = np.random.randn(n)
subjs = np.repeat(np.arange(int(n/2)), 2)

_ = pd.DataFrame({'subject': subjs, 'within': within, 'between': between, 'values': vals})

# ttests
pingouin.pairwise_ttests(
    data=_,
    padjust="bonf",
    dv="values",
    within="within",
    between="between",
    subject="subject",
)
```

OUTPUT

![image](https://user-images.githubusercontent.com/9084751/85136420-e6051d00-b23f-11ea-92f5-c35c5eba880e.png)

WHAT I WANT/NEED
| contrast | between | A | B | paired |
| -----------|----------|---|---|-----------|
|between * within | c | a | b | true|
|between * within | d | a | b | true|

**Comment by raphaelvallat** [comment]
Hi @sappelhoff !

Thanks for the very detailed issue. This is something I've been pondering for a long time. When I first coded this function, I was only interested in the within * between interaction, hence the choice of only reporting this order (and I also think it's also the default in some other stats software). But I agree it would be good to have the option of having the between * within interaction.

I'm thinking perhaps adding a parameter like `pg.pairwise_ttests(..., within_first=True)`. When `within_first=False`, the order of the interaction is between * within. Would that make sense? Let me know what you think!

Thanks
Raphael

**Comment by sappelhoff** [comment]
Hi @raphaelvallat thanks for the quick answer!

> and I also think it's also the default in some other stats software

interesting, do these other software packages offer the option to also get the "reverse" (between * within)?

> I'm thinking perhaps adding a parameter like pg.pairwise_ttests(..., within_first=True)

that sounds reasonable to me, and it's exactly what I would have expected (and what I looked for). 

One obvious (easy) issue is that one of the columns in the stats output DF is called "within", and that wouldn't make sense if a between factor level is entered there. ... so either that column could then be called "between" (if within_first=False), or there could always be two columns (within, and between) with the non-applicable cells filled with `-` or similar.

**Comment by raphaelvallat** [comment]
> interesting, do these other software packages offer the option to also get the "reverse" (between * within)?

Not in JASP, at least, as you can see in the screenshot below. The only order is within * between:

![image](https://user-images.githubusercontent.com/25703792/85185992-667d4b00-b24b-11ea-9b5d-6269945208aa.png)

I will work on implementing this over the weekend and should hopefully have a working version on the develop branch soon. Thanks again!

**Comment by raphaelvallat** [comment]
Ok this is now implemented in commit 4d1f10b2de1a088d52d10a4ef6928ab7227672e6. If you have the develop version of Pingouin (e.g. GitHub clone), it would be great if you could go to the develop branch and try this new feature on your own data. This will be part of the next stable version, which will be released sometime this summer. Thanks again!

**Comment by sappelhoff** [comment]
Thanks for the quick implementation! :-) 

I just ran a test with my data:

# What's good

The `within_first=False` between*within interactions align with the pairwise t-tests that I calculated prior to having this new feature. So that's as expected.

![image](https://user-images.githubusercontent.com/9084751/85197948-d390ef00-b2e4-11ea-934e-f2dd7d79490e.png)

# What's strange

The "within" factor and the "between" factor per se should not be affected by this new feature if I understand correctly. Yet they are somehow affected ... look at the between factor (especially degrees of freedom)

![image](https://user-images.githubusercontent.com/9084751/85197971-0dfa8c00-b2e5-11ea-9aea-efb40a8de54a.png)

**Comment by raphaelvallat** [comment]
Ah sorry, I forgot to update the `marginal` parameter when `within_first=True`. The between-subject T-test should be calculated after averaging over all the repeated measurements (when `marginal=True`), which probably explains the difference in dof. I've just pushed a new commit, can you let me know if that solved the issue? And if not, could you please send me your data and script on Gitter? Thanks!

**Comment by sappelhoff** [comment]
yes, that fixed it! :-)

re your PS --> I think that's totally fine ... it's cool that this feature required only so few changed lines. Thanks a lot, I am looking forward to the next release.
