### ISSUE TITLE
Deprecating or replacing pingouin.plot_skipped_corr

### ISSUE THREAD

**Issue by raphaelvallat** [raphaelvallat/pingouin#105]
For the sake of simplicity, I would be in favor of deprecating the [pingouin.plot_skipped_corr](https://pingouin-stats.org/generated/pingouin.plot_skipped_corr.html#pingouin.plot_skipped_corr) function which I think is too specific and most likely only used by very few users (but I may be wrong?). That said, I do like the left panel of the output plot (= standard scatterplot with robust regression line and outliers highlighted), and I could also imagine replacing this function by a more general ``pingouin.plot_robust_corr`` function where users can specificy the robust correlation method (i.e. not limited to only a skipped correlation).

Please feel free to let me know which options you prefer:

1. Keeping the function as is.
2. Deprecating the function.
3. Replacing the function by a more general ``pingouin.plot_robust_corr`` function which would only integrate the left panel of the current function, i.e. without the bootstrapped distribution.

Thanks!

**Comment by LegrandNico** [comment]
Yes, I agree this function may be too specific, so could be depreciated or replaced. It still makes sense for me to have some visualization tools like a `pingouin.plot_robust_corr`, but it depends on the kind of plotting module you want in Pingouin.

**Comment by mmolet** [comment]
Hi all,

I like #3.

Thanks!

**Comment by raphaelvallat** [comment]
The plot_skipped-corr function has been deprecated in the new release (v0.3.7). Closing this issue for now but please feel free to reopen.
