### ISSUE TITLE
Adding Multicollinearity plots

### ISSUE THREAD

**Issue by tirthajyoti** [raphaelvallat/pingouin#106]
Any chance of adding more multi-colinearity tests like,

- Pairplot
- Variance infletion factors (VIF)
- Covariance matrix
- Correlation matrix
- Correlation matrix heatmap

**Comment by raphaelvallat** [comment]
Hi @tirthajyoti,

Can you please be more specific and provide a few examples?

- Pairplot is already implemented in Seaborn.
- Covariance / corr matrix can be calculated with pandas and then easily plotted with seaborn heatmap.

So I don't think there's a need to implement these functions in Pingouin.

Thanks
Raphael

**Comment by tirthajyoti** [comment]
I think I understand your goal in this package - to provide a tabular output of statistical tests and analyses - with a simple API. Closing this issue now. Thanks.
