### ISSUE TITLE
Goodness of fit function

### ISSUE THREAD

**Issue by jcvall-olympus** [raphaelvallat/pingouin#108]
Love the package.  I was wondering if we can add goodness of fit function here.  I have been working on a function for this but I still need to work a few things out with it.  Would you be interested to collaborate on it for this package?

**Comment by raphaelvallat** [comment]
Hi @jcvall-olympus ! Goodness of fit is a broad term that encompass several tests (see [Wikipedia](https://en.wikipedia.org/wiki/Goodness_of_fit)). Can you be more specific as to which test(s) you have in mind in particular?

Thanks,
Raphael

**Comment by raphaelvallat** [comment]
Closing this issue but please feel free to reopen.
