### ISSUE TITLE
SyntaxError when importing on python < 3.6

### ISSUE THREAD

**Issue by stephantul** [raphaelvallat/pingouin#11]
Hey,

Thanks for the great package.

The documentation of Pingouin states that it is strongly recommended that python >= 3.6 is used, which seems to imply that the package is usable with other versions. This is not the case. 
Importing Pingouin on python < 3.6 fails, because [this line](https://github.com/raphaelvallat/pingouin/blob/e1855aa28da8bbe4de28781a280724dea92f91b0/pingouin/plotting.py#L137) uses f-strings, which were only introduced in python 3.6. 

AFAIK, the file linked above is the only place where f-strings are used. 
I'm not sure whether you want to create a work-around for this, but it threw me for a loop when I saw the error. I'll leave it up to you to decide whether removing these f-strings is a good choice, they are the way forward after all.

On a related note, installing pingouin using python 2.7 does not work, because the matching matplotlib version is not available. So it seems to me that python 2.7 support can be dropped from the readme as well.
```
error: Setup script exited with
Matplotlib 3.0+ does not support Python 2.x, 3.0, 3.1, 3.2, 3.3, or 3.4.
Beginning with Matplotlib 3.0, Python 3.5 and above is required.
```

**Comment by raphaelvallat** [comment]
Hi @stephantul! 
Thank you for this! I have fixed the f-string issue in the develop version of Pingouin, which I hope to release in the next week or so. 

You are right for Python 2.7, I have just changed the README & doc to say that Pingouin only works with Python 3. This will be visible in the next release.

Thank you again,
Have a great day,
Raphael
