### ISSUE TITLE
Bootstrapping 'Basic Percentile method'

### ISSUE THREAD

**Issue by jnecus** [raphaelvallat/pingouin#110]
Hello,

I was wondering whether you could clarify what the bootstrapping percentile method labelled as `Basic percentile method`  in the bootstrap function below is:

```
def compute_bootci(x, y=None, func='pearson', method='cper', paired=False,
                   confidence=.95, n_boot=2000, decimals=2, seed=None,
                   return_dist=False):
....
    method : str
        Method to compute the confidence intervals:
        * ``'norm'``: Normal approximation with bootstrapped bias and
          standard error
        * ``'per'``: Basic percentile method
        * ``'cper'``: Bias corrected percentile method (default)
```

As far as I understand, there are at least three types of percentile method for computing bootstraps according to the following link : https://www.datacamp.com/community/tutorials/bootstrap-r

- Percentile CI
- Basic CI (also called _pivotal_ or _empirical_ CI) 
- Bias Corrected Percentile CI

I would like to try and understand which method is implemented as part of the Basic percentile method in Pingouin above.

I assume that it is the 'Percentile CI'. If so, then perhaps it should be re-named from 'Basic Percentile method' to Percentile method, and then the Basic CI (also called _pivotal_ or _empirical_ CI)  can also be implemented.

I am happy to go ahead and re-name and implement this if you are able to clarify this for me and also agree that it is a good idea.

**Comment by raphaelvallat** [comment]
Hi @jnecus,

The names of the different methods are taken from the Matlab [bootci ](https://www.mathworks.com/help/stats/bootci.html)function:

- 'norm' : Normal approximated interval with bootstrapped bias and standard error (= Normal CI in the link that you sent)
- 'per': Basic percentile method (= Percentile CI)
- 'cper': Bias corrected percentile method (= I think this is the basic CI, but I'll have to check with the R code to be sure)
- The bias-corrected and accelerated method ('bca') is not yet implemented in Pingouin.

To avoid API-breaking changes, and since the method names are consistent with Matlab, I would be in favor of keeping the current names.

Let me know if that makes sense,

Thanks
Raphael

**Comment by jnecus** [comment]
Hi Raphael,

Yes that does make sense and I agree that you should keep it consistent with Matlab. I think the confusion here comes with my lack of understanding of bootstrap methods. When looking at the different options provided across Matlab, R, and Pingouin, it seems that the naming of the percentile methods when it comes to basic & percentile is a little ambiguous. The the bottom two rows of the table comparing the three packages here:

|           R    (boot)           |         Matlab  (bootci)         |             Pingouin             |
|:-------------------------------:|:--------------------------------:|:--------------------------------:|
| normal                          | normal                           | normal                           |
| student                         | student                          | n/a                              |
| bca                             | bca                              | n/a                              |
| percent (Bootstrap percentile)  | percentile (Basic Percentile)    | per (Basic Percentile)           |
| basic (Basic Bootstrap method)  | cper (Bias corrected percentile) | cper (Bias corrected percentile) |

**Comment by raphaelvallat** [comment]
Thanks for this table, this will be certainly useful for others! I'd love implement the student and bca bootstrap methods at some point in the future.

Closing this issue for now, but feel free to reopen or submit a PR.

Thanks
Raphael
