### ISSUE TITLE
Updating CLES in MWU test to Vargha and Delaney

### ISSUE THREAD

**Issue by odgaard** [raphaelvallat/pingouin#114]
Hi, thank you for the response in #94.

Just wanted to note that the MWU test currently uses the original CLES definition, and it could also be updated to the Vargha Delaney A measure.

Kind regards,
Jacob

**Comment by raphaelvallat** [comment]
Hi @odgaard,

You're absolutely right. To be honest, I cannot remember why I did not update it in parallel with the `wilcoxon` and `compute_effsize` functions. I just probably missed it. Anyway, I've now updated the formula in the develop branch of Pingouin (see 78c9a3b91d05c788f666671e1b117bd7b3f427c7), and this will be included in the next stable release, expected around September.

Thanks
Raphael

**Comment by raphaelvallat** [comment]
This is fixed in the just-released stable version of Pingouin (v0.3.8). Please make sure to update your version. Closing the issue. Thanks again!
