### ISSUE TITLE
Normality function (Shapiro-Wilk test) and NaNs

### ISSUE THREAD

**Issue by eotp** [raphaelvallat/pingouin#12]
At the moment the `normality` function does not account properly for `NaN`s in the data. 

```
normality([np.nan, 1, 2])
(False, nan)

normality([np.nan, 1, 2, 10])
(True, 1.0)
```
Though a _p_ value of 1 is suspicious anyway, it would make sense to provide a warning message or an argument to remove the `NaN`s.

```
normality([np.nan, 1, 2, 10], remove_na=True)
(True, 0.194)
```

**Comment by raphaelvallat** [comment]
Indeed, thank you @eotp for the suggestion! We are going to make some major changes to the `normality()` function for the next release (see also https://github.com/raphaelvallat/pingouin/issues/6), including an option to automatically remove missing values, as you suggested. 
Have a great day!
Raphael

**Comment by raphaelvallat** [comment]
I completely rewrote the normality function, which now applies an automatic casewise deletion. The changes will be visible in the next (June) release of Pingouin.

See develop commit at 9a7fc50ac79b5c287a433e151cc55136029415d6

Thanks again!
