### ISSUE TITLE
pingouin.multivariate_normality() bugs in mu and sigma^2 equations

### ISSUE THREAD

**Issue by jckrumm** [raphaelvallat/pingouin#125]
I was going over your implementation of 

def multivariate_normality(X, alpha=.05):

in multivariate.py. I might’ve found a couple bugs in the equations for mu and si2 in lines 99-104. I assume you’re using the equations from the paper “MVN: An R Package for Assessing Multivariate Normality” at https://www.mclibre.org/descargar/docs/revistas/the-r-journal/the-r-journal-12-en-201412.pdf#page=151. I’ve included a screenshot of the equations in the paper for mu and sigma^2.

For mu, I’ve circled a term beta^(2/a). You have this implemented in Python as b\*\*2/a. According to operator precedence, the exponentiation will happen before the division. I think the code should be b\*\*(2/a). 

For si2, there seems to be a problem with the parentheses. In my screenshot, I’ve circled two matching parentheses that should not be matching according to the equation for sigma^2 in the paper.

![mean_and_variance_paper](https://user-images.githubusercontent.com/53381882/91893696-5faa8580-ec49-11ea-88e2-d05b4bc440b5.JPG)
![mean_and_variance](https://user-images.githubusercontent.com/53381882/91893916-b748f100-ec49-11ea-8af0-a9aa5352de78.JPG)

**Comment by raphaelvallat** [comment]
Hi @jckrumm! 

Thanks for looking into that! For this function, I've essentially translated the code of the MVN package from R to Python, and then made sure that I obtained similar results. For comparison, please find below Pingouin's code (top) and the [original R code](https://github.com/selcukorkmaz/MVN/blob/master/R/mvn.R) (bottom) for both mu and si2:

Mu:

> ```python
> mu = 1 - a**(-p / 2) * (1 + p * b**2 / a + (p * (p + 2) * (b**4)) / (2 * a**2))
> ```
> ```R
> mu = 1 - a^(-p / 2)  * (1 + p * b^2  / a + (p * (p + 2) * (b^4) ) / (2 * a^2))
> ```

Si2:

> ```python
> si2 = 2 * (1 + 4 * b**2)**(-p / 2) + 2 * a**(-p) * (1 + (2 * p * b**4) / a**2 + (3 * p * (p + 2) * b**8) / (4 * a**4)) - 4 * wb**(-p / 2) * (1 + (3 * p * b**4) / (2 * wb) + (p * (p + 2) * b**8) / (2 * wb**2))
> ```
> ```R
> si2 = 2 * (1 + 4 * b^2)^ (-p / 2) + 2 * a^(-p)  * (1 + (2 * p * b^4)  / a^2  + (3 * p * (p + 2) * b^8) /  (4 * a^4))  - 4 * wb^(-p / 2)  * (1 + (3 * p * b^4) /  (2 * wb) + (p * (p + 2) * b^8)  / (2 * wb^2))
> ```

As you can see, it seems that the points you highlight are also present in the original R code. So I guess it would make more sense to reach out directly to the authors of the paper / R toolbox?

Let me know what you think,

Thanks
Raphael

**Comment by jckrumm** [comment]
Now I think the pingouin equations are correct. They don't match the paper in “MVN: An R Package for Assessing Multivariate Normality”, which makes me think the paper has the wrong equation. I tested four different implementations of the mu and sigma^2 equations (pasted below), including the equations presented in the original paper describing this multivariate normality test. On my test, the only implementation that stood out as different was the one from the "R Package" paper. Your equations gave the same result as the R code equations you have above, and those two both matched the equations from the original paper. Next time I'll wait until I do a more thorough test before I accuse anyone of a bug in their code. Thanks for taking a close look at it.

    # From https://github.com/raphaelvallat/pingouin/blob/master/pingouin/multivariate.py
    def mu_sigma2_pingouin(self,beta):
        p = self.d
        b = beta
        wb = (1 + b**2) * (1 + 3 * b**2)
        a = 1 + 2 * b**2
        # Mean and variance
        mu = 1 - a**(-p / 2) * (1 + p * b**2 / a + (p * (p + 2)
                                                * (b**4)) / (2 * a**2))
        si2 = 2 * (1 + 4 * b**2)**(-p / 2) + 2 * a**(-p) * \
        (1 + (2 * p * b**4) / a**2 + (3 * p * (p + 2) * b**8) / (4 * a**4)) \
        - 4 * wb**(-p / 2) * (1 + (3 * p * b**4) / (2 * wb)
                              + (p * (p + 2) * b**8) / (2 * wb**2))

        return mu, si2

    # From https://rdrr.io/cran/MVN/src/R/mvn.R
    def mu_sigma2_MVNR(self,beta):
        p = self.d
        b = beta
        wb = (1 + b**2)*(1 + 3*b**2)
        a = 1 + 2*b**2
        mu = 1 - a**(- p/2)*(1 + p*b**2/a + (p*(p + 2)*(b**4))/(2*a**2)) #HZ mean
        si2 = 2*(1 + 4*b**2)**(- p/2) + 2*a**( - p)*(1 + (2*p*b**4)/a**2 + (3*p*
                                                                    (p + 2)*b**8)/(4*a**4)) - 4*wb**( - p/2)*(1 + (3*p*b**4)/(2*wb) + (p*
                                                                                                                                     (p + 2)*b**8)/(2*wb**2)) 
        return mu, si2

    # From "MVN: An R Package for Assessing Multivariate Normality" shortly after Equation (2)
    # This one is likely wrong, because the other three methods give the same result on a test, but this one is different.
    def mu_sigma2_MVN(self,beta):
        a = 1+2*beta*beta
        wBeta = (1+beta*beta)*(1+3*beta*beta)
        mu = math.pow(a,-self.d/2.0)*(1 + self.d*math.pow(beta,2/a) + self.d*(self.d+2)*math.pow(beta,4))
        mu = 1-mu/(2*a*a)
        
        s2 = 2*math.pow(1+4*beta*beta,-self.d/2.0)
        s2 = s2 + 2*math.pow(a,-self.d)*(1+2*self.d*math.pow(beta,4))/(a*a)
        s2 = s2 + 3*self.d*(self.d+2)*math.pow(beta,8)/(4*math.pow(a,4))
        s2 = s2 - 4*math.pow(wBeta,-self.d/2.0)*(1 + 3*self.d*math.pow(beta,4)/(2*wBeta) + self.d*(self.d+2)*math.pow(beta,8)/(2*wBeta*wBeta))

        return mu, s2

    # From "A class of invariant consistent tests for multivariate normality", original paper, p. 3605
    def mu_sigma2_Henze_Zirkler(self,beta):
        d = self.d
        wBeta = (1+beta*beta)*(1+3*beta*beta)
        mu = 1-math.pow(1+2*beta*beta,-self.d/2)*(1 + d*beta*beta/(1+2*beta*beta) + d*(d+2)*math.pow(beta,4)/(2*math.pow(1+2*beta*beta,2)))

        s2 = 2*math.pow(1+4*beta*beta,-self.d/2)
        s2 = s2 + 2*math.pow(1+2*beta*beta,-self.d)*(1 + 2*self.d*math.pow(beta,4)/math.pow(1+2*beta*beta,2) + 3*self.d*(self.d+2)*math.pow(beta,8)/(4*math.pow(1+2*beta*beta,4)))
        s2 = s2 - 4*math.pow(wBeta,-self.d/2)*(1 + 3*self.d*math.pow(beta,4)/(2*wBeta) + self.d*(self.d+2)*math.pow(beta,8)/(2*wBeta*wBeta))

        return mu, s2

**Comment by raphaelvallat** [comment]
No worries at all and thanks for taking a deep dive into this! Always good to revisit some code that I do not use that often. 

Closing the issue now.
