### ISSUE TITLE
Pairwise comparisons in one-way repeated measures anova - p value results not matching with R p values

### ISSUE THREAD

**Issue by merjekrepo** [raphaelvallat/pingouin#128]
[liquor-sales_long.xlsx](https://github.com/raphaelvallat/pingouin/files/5213386/liquor-sales_long.xlsx)

For the attached excel file, when I run pairwise comparisons in one-way repeated measures using pingouin, I get the following p value results:

```
file_name = "mydirectory\\liquor-sales_long.xlsx"
df = pd.read_excel(file_name)
print(df)
print()

print("Applying pairwise t-test for one way repeated measures anova")
res = pg.pairwise_ttests(data=df, dv='amount', within='day', subject='id', return_desc=True, padjust='bonferroni')
print(res)
```

![one_way_within_subjects_anova_screenshot_pengouin](https://user-images.githubusercontent.com/12020185/93007029-4945d900-f529-11ea-81c0-2b353fa2efd5.JPG)

On the other hand, when I perform pairwise comparison using R, I get the following p values:

```
library(readxl)
anovadata = read_excel(file.choose())
result <- aov(amount ~ day + Error(id/day), data=anovadata)
tresult <- tapply(amount, day, mean)
require(stats)
pairwise.t.test(amount, day, p.adjust.method = "bonferroni")
```

![one_way_within_subjects_anova_screenshot_R](https://user-images.githubusercontent.com/12020185/93007049-8e6a0b00-f529-11ea-97ed-3d520808a733.JPG)

Is it normal that adjusted p values from R don't match with pingouin's adjusted p values? Or am I doing something wrong?

**Comment by raphaelvallat** [comment]
Hi @merjekrepo,

It's because you need to specify `paired = TRUE` in R otherwise you're calculating _independent_ T-tests. The following R snippet gives the same results as Pingouin:

```R
library(readxl)
require(stats)
data = read_excel("liquor-sales_long.xlsx")
pairwise.t.test(data$amount, data$day, p.adjust.method = "bonferroni", paired = TRUE)
```

Thanks,
Raphael
