### ISSUE TITLE
plot_paired for n>2 subjects

### ISSUE THREAD

**Issue by JoElfner** [raphaelvallat/pingouin#132]
Hi @raphaelvallat 

are you interested in an implementation of a paired plot for an arbitrary number of unique subjects?

This could look like:
![evolution of income over subjects](https://user-images.githubusercontent.com/38665102/94118748-3c40b800-fe4e-11ea-81ec-2f8b1811dbd6.png)

**Comment by raphaelvallat** [comment]
Hi @JoElfner!

Absolutely! Many people have asked me if paired plots with n>2 were going to be implemented in Pingouin, and I've always been too lazy to do it, but if you want to submit a PR please do :-)

**Comment by JoElfner** [comment]
Done! Initial commit pushed. As soon as you approve the PR or at least parts of it, I'll add examples, tests and doc.
