### ISSUE TITLE
Quade's RANCOVA/Nonparametric Analysis of Covariance

### ISSUE THREAD

**Issue by apavlo89** [raphaelvallat/pingouin#134]
Hello Raphael,

This is a feature request. It would be great if Quade's RANCOVA was included in Pingouin. Here is the procedure on SPSS https://www.youtube.com/watch?v=jozx59H5IHw&feature=youtu.be

I haven't been able to find Quade's in Python so if this was done it would be the first python implementation of this method.

Regards,

Achilleas

**Comment by raphaelvallat** [comment]
Hi @apavlo89,

Thanks for opening this feature request. I had never heard of Quade's ANCOVA before, and it doesn't seem to be implemented in JASP either. Could be a nice addition to Pingouin but I really don't think I'll have the time to work on it within the next months.

I'll leave the issue open in case anyone wants to give it a try and submit a PR!

Thanks
Raphael

**Comment by apavlo89** [comment]
Hello Raphael,

It is quite a decent method for non-parametric analysis of variance. I wish I had the programming skills to add it to Pengouin myself! I came upon Pengouin recently trying to find a better and faster and easier way to apply statistical tests and to display graphs better, using Python, on the data I extracted using YASA that I inspected on Visbrain. Both project you are involved in. Lo and behold I see you are also the author of this Python package as well! Thank you for your immense contribution to open-source science

**Comment by raphaelvallat** [comment]
Closing this issue but please feel free to reopen

**Comment by seralouk** [comment]
Quade’s ANCOVA would be indeed a great addition!

**Comment by sabin5105** [comment]
Hi @raphaelvallat @apavlo89 @seralouk ,

I have opened a PR to implement Quade’s test for repeated measures data in Pingouin, addressing this feature request. You can check out the PR here: [#439](https://github.com/raphaelvallat/pingouin/pull/439).

Looking forward to any feedback or suggestions!

Thank you!
