### ISSUE TITLE
Reimplementing Pingouin in Julia

### ISSUE THREAD

**Issue by clementpoiret** [raphaelvallat/pingouin#135]
Hey Raphael, I hope you're fine.

I want to practice my skills in Julia, and I really like using Pingouin for my Python projects.
I think it can be practical to have a Julia version of Pingouin, do you allow me to try to "port" your work on this language? Of course, I'll credit your original package, and stay open source :) 

Have a nice day,
Clément

**Comment by raphaelvallat** [comment]
Hi @clementpoiret,

Absolutely, that's a great idea! I've always thought that at some point in the future it would be nice to port Pingouin to Julia. Good luck with that and keep us posted on your progress :-)

Have a great day,
Raphael

**Comment by clementpoiret** [comment]
Thanks!
I think this is the kind of libraries that lacks in the Julia ecosystem (I didn't even found an implementation for a Shapiro-Wilk test, beside calling a 20-years-old Fortran code used in scipy...)
I'll try to do my best :) ! 

Have a great day too,
Clément

**Comment by clementpoiret** [comment]
If anyone want to check the project, here is the current state of implementation: https://github.com/clementpoiret/Pingouin.jl/projects/1 :)
