### ISSUE TITLE
Mixed 2-way ANOVA 

### ISSUE THREAD

**Issue by dokato** [raphaelvallat/pingouin#136]
My RM ANOVA works fine:

```
pg.rm_anova(data = df, dv='time', subject='pid', within=['axis', 'congr'])
```

I thought it would be easy to extrapolate to mixed ANOVA by introducing another between subject variable. But this:

```
pg.mixed_anova(data=df, dv='time', within=['axis', 'congr'], between='shift', subject='pid')
```

errors: `'DataFrame' object has no attribute 'dtype'`

Is there a plans to introduce 2-way mixed ANOVA, eg. for a design 2x2x2?

**Comment by raphaelvallat** [comment]
Hi @dokato,

For now, only one-within / one-between factors are supported in mixed_anova. It would actually require a lot of changes to the code to add support for multiple between or within factor, so I doubt this will be implemented in the near future.

For more complex ANOVA designs, I strongly recommend using JASP.

Thanks!
Raphael

**Comment by dokato** [comment]
@raphaelvallat ah pity, thanks for adding it to the roadmap though ;)

**Comment by sappelhoff** [comment]
based on how often this question comes up (also on gitter), it may be worthwhile to add a short check for `mixed_anova`: if more than one within or between factor are specified, a ValueError is raised, saying that this is not yet implemented, and pointing to this issue, asking for somebody to implement it :-)
