### ISSUE TITLE
Allow specification of "skipped" correlation

### ISSUE THREAD

**Issue by achennings** [raphaelvallat/pingouin#138]
Hello Raphael,

I've been playing around with robust correlations, and I realized that currently pingouin has the option to run both skipped spearman's, and pearson's correlations. However, the user cannot actually request a skipped pearson's correlation, the unchangeable default is spearman's.

In correlation.py:
```python
elif method == 'skipped':
    r, pval, outliers = skipped(x, y)
```

Where the definition of `skipped` is:
```python
def skipped(x, y, method='spearman'):
    """Skipped correlation (Rousselet and Pernet 2012).

    Parameters
    ----------
    x, y : array_like
        First and second set of observations. x and y must be independent.
    method : str
        Method used to compute the correlation after outlier removal. Can be
        either 'spearman' (default) or 'pearson'."""
```

So it seems all that is required is to rework the possible methods in `pg.corr`. 

I think a simple suggestion could be `skipped-pearson` and `skipped-spearman`, where we just need to add these lines:

```python
    elif method == 'skipped-spearman':
        r, pval, outliers = skipped(x, y, method='spearman')
    elif method == 'skipped-pearson':
        r, pval, outliers = skipped(x, y, method='pearson')
```

I'd be happy to submit a pull request if this works for you.

**Comment by raphaelvallat** [comment]
@achennings,

I think that's a great idea, and I like your suggestion. Another option is to add a **kwargs argument to the pingouin.corr() function that would then be passed to the lower-level correlation functions, e.g.:

```python
pg.corr(x, y, method='shepherd', n_boot=1000)  # n_boot is a kwarg argument passed to pg.shepherd
pg.corr(x, y, method='skipped', method='spearman')  # Here we'd need to rename the `method` argument in pingouin.skipped
pg.corr(x, y, method='percbend', beta=.2)
```
Let me know what you think!

Thanks,
Raphael

**Comment by achennings** [comment]
I think actually you have the right idea with passing **kwargs down so that other options can be controlled. Something else that I noticed, that maybe should be its own issue, is that currently the p-value from robust correlations comes from the single estimate, and the 95% CI is derived parametrically. Something that I think would be useful would be to allow for specification if the 95%CI and corresponding p-value should be calculated non-parametrically, as discussed here (https://www.frontiersin.org/articles/10.3389/fpsyg.2012.00606/full).

The code to make this happen all exists in "pingouin" form already, I think in the now deprecated plot_skipped_corr function. 

To bring it back to the issue at hand, I think a good solution is to allow keywords to specify both the parameters of robust correlation (percbend beta weight, skipped method), as well as the preferred method of hypothesis testing (parametric vs. non-parametric). 

-Augustin

**Comment by raphaelvallat** [comment]
Hi @achennings,

Please feel free to submit a PR implementing the kwargs in pg.corr()!

As for the non-parametric estimation of confidence intervals and p-values, I have to say I'm not especially in favor of implementing that for the following reasons:

1. It's hard to validate the results derived from (random) bootstrapped distribution.
2. There is already the compute_bootci function if users want to calculate the non-parametric confidence intervals of a correlation coefficient.
3. The p-values and 95%CI cannot be estimated from the same bootstrapped distribution, so we would need to have two different bootstrapping which may be very slow.

Let me know what you think, and if others think that such non-parametric p-values / 95% CIs would be useful then please feel free to let us know.

Thanks
Raphael

**Comment by raphaelvallat** [comment]
I have just added support for kwargs in pg.corr (see cba94ff48157a27eaf73afbc32ee94c9e880c912). This will be available on the next stable release of Pingouin, which I'm planning on pushing within the next few days. Closing the issue for now but feel free to reopen. Thanks
