### ISSUE TITLE
can i use it for an 2x2x2 repeated anova

### ISSUE THREAD

**Issue by caofeizhen** [raphaelvallat/pingouin#140]

**Comment by caofeizhen** [comment]
beg you

**Comment by raphaelvallat** [comment]
Hi @caofeizhen,

For similar questions, please use the Pingouin Gitter channel: https://gitter.im/pingouin-stats/Lobby

To answer your question, no, you cannot. Pingouin does not support 2x2x2 design. I'd suggest using the free software JASP.

Thanks
Raphael
