### ISSUE TITLE
Feature request: Non-parametric repeated measures

### ISSUE THREAD

**Issue by apavlo89** [raphaelvallat/pingouin#142]
Would be awesome if non-parametric repeated measures was added at some point. It has been implemented in R nparcomp package. Here is a researchgate post about it. https://www.researchgate.net/post/Is_there_a_non-parametric_equivalent_of_Repeated_Measures_ANOVA

**Comment by raphaelvallat** [comment]
Hi @apavlo89,

Can you please be a little more specific? I just want to note that there is already the [pingouin.friedman](https://pingouin-stats.org/generated/pingouin.friedman.html) function which is basically a non-parametric one-way repeated measures ANOVA.

Thanks!
Raphael

**Comment by raphaelvallat** [comment]
Closing this issue but please feel free to reopen
