### ISSUE TITLE
Feature request: F-test for Friedman

### ISSUE THREAD

**Issue by PuncocharM** [raphaelvallat/pingouin#143]
I found through wikipedia (https://en.wikipedia.org/wiki/Kendall%27s_W#Significance_Tests) that apart from the usual Chi-squared test, there is a possibility to perform F-test and the wiki page links to a paper (Marozzi 2014) showing the F-test is superior to Chi2 in size and power for smaller samples. It would be nice to have it in pingouin too, at least as an option if not as a default.

I use it as follows:
```
W = Q / (k-1) / n  # Kendall's W
F = W * (n-1) / (1-W)  # F statistic
v1 = k-1 - 2/n
v2 = (n-1) * v1
p = sps.f.sf(F, v1, v2)
```

**Comment by raphaelvallat** [comment]
HI @PuncocharM,

Thanks for the PR! This sounds like a nice addition to the pingouin.friedman function indeed. Currently, the function only returns the Q-statistic, degrees of freedom, and p-value. Two options:

1. We add the W (Kendall), F-statistic, new p-value + the two degrees of freedom of the F-test to the output dataframe. This would be super exhaustive but probably very confusing for users (e.g. having two p-values)

2. We specify a `method=` argument that allows users to choose between a chi-square or F test. I'm not sure what the names of these methods should be though (?).

3. I think whatever option we decide, we should probably still return the Kendall's W statistic in both cases.

What do you think? Would you be okay to implement it in a PR?

Thanks again,
Raphael

**Comment by PuncocharM** [comment]
Hi @raphaelvallat,

sure, I can try to put together a PR. I agree with you that the second option is better. We would return Kendall's W, which serves as an effect size and according to a method argument we compute either Q or F statistic, perform the corresponding test and return the used statistic and p-value. The argument could be method='chisq' or method='f' for example?

**Comment by raphaelvallat** [comment]
That sounds great! Please feel free to submit a PR (on the develop branch of Pingouin -- and see the [contributing guidelines](https://pingouin-stats.org/contributing.html)). Let me know if you have any questions. Thanks again!

**Comment by raphaelvallat** [comment]
Closing this issue. This will be released in the next soon-to-come version of Pingouin.
