### ISSUE TITLE
F-test for linear model?

### ISSUE THREAD

**Issue by gacek91** [raphaelvallat/pingouin#145]
Hello,

Is there any way to calculate the F-stat and significance level of the linear model using pingouin?

Kind regards.

**Comment by raphaelvallat** [comment]
Hi @gacek91,

I'm assuming you are referring to the F-test of a multiple linear regression, correct? This is not calculated by Pingouin, but it should be pretty straightforward to manually compute it using the residuals and degrees of freedom of the model. For more details, please see: http://facweb.cs.depaul.edu/sjost/csc423/documents/f-test-reg.htm

If you succeed, please feel free to share your code here to help future users who may have the same request. Also, this could be a nice idea for a PR so please feel free to submit one if you feel like it.

Thanks
Raphael

**Comment by gacek91** [comment]
Sure, will give it a try!

Cheers,

Maciej

**Comment by raphaelvallat** [comment]
Re: The F-test of a linear regression can also be calculated with statsmodels, see: https://www.statsmodels.org/devel/examples/notebooks/generated/regression_diagnostics.html

I'm closing this issue for now, but please feel free to reopen.

Thanks
Raphael
