### ISSUE TITLE
T-test results different from R and scipy

### ISSUE THREAD

**Issue by texturejc** [raphaelvallat/pingouin#146]
Hi. First of all, thanks for pingouin; it's a great package––perfect for teaching and the kind of analyses done in experimental psychology. 

However, I'm after picking up an inconsistent behaviour in the independent samples t-test function. Basically, when I compare means between the two groups in the data attached, pingouin outputs the following test statistics:

```
T              -1.98937
dof             37.9368
tail          two-sided
p-val         0.0539058
CI95%      [-0.09, 0.0]
cohen-d        0.535728
BF10              1.353
power          0.524033
```

This would be fine, except that performing the same test in R gives the following, different results:

```
data:  variable by Group
t = -2.0548, df = 57, p-value = 0.04449
alternative hypothesis: true difference in means is not equal to 0
95 percent confidence interval:
 -0.091280396 -0.001178309
sample estimates:
mean in group 0 mean in group 1 
     0.03372529      0.07995464 
```

Scipy agrees with R in this:

`Ttest_indResult(statistic=-2.054839885933219, pvalue=0.04448820543302607)`

I expect that the difference here derives from how pingouin treats `nan` data, as the dof in the pingouin output is incorrect: it should be 57 and not 37. 

Any idea what's happening here? The difference in output is subtle; it's only by chance that I noticed it. 
[pingouin_ttest_bug.xlsx](https://github.com/raphaelvallat/pingouin/files/5647068/pingouin_ttest_bug.xlsx)

**Comment by raphaelvallat** [comment]
Hi @texturejc,

This is because Pingouin automatically applies the Welch correction for groups of different sizes. Setting `correction=False` give a similar output to R and SciPy:

![image](https://user-images.githubusercontent.com/25703792/101268590-75808880-3719-11eb-9dbf-910d69dd16c1.png)

**Comment by texturejc** [comment]
Great, thanks for clarifying this! Now that you say it, I see that it's stated in the docs, but nice to have the puzzle resolved.
