### ISSUE TITLE
pg.ttest() documentation: the behavior for the one sample test

### ISSUE THREAD

**Issue by FlorinAndrei** [raphaelvallat/pingouin#149]
When y is a scalar, `pg.ttest()` performs a one sample test. But the documentation is not clear on what y means in this context.

Related, what value should y have to replicate the t.test() function from R?

https://pingouin-stats.org/generated/pingouin.ttest.html

Please add this line to the documentation, to make it more clear (for beginners) what the real behavior is:

```
y is the testvalue for the one sample t-test; y=0 replicates the t.test() R function
```

Thanks!

**Comment by manfred2020** [comment]
here you find info about the t-test in R:

https://www.rdocumentation.org/packages/stats/versions/3.6.2/topics/t.test

"mu = 0"
"mu          a number indicating the true value of the mean (or difference in means if you are performing a two sample test)."

or maybe this helps:
http://www.sthda.com/english/wiki/one-sample-t-test-in-r

**Comment by FlorinAndrei** [comment]
I'm trying to make you look at it not from the perspective of someone who is very familiar with it (and then of course it's all clear) but from the p.o.v. of someone just getting started.

The documentation seems to say the function is very firmly geared towards the two-sample test, and there are no clear clues as to how to transition it to a one-sample test.

This phrase seems to provide a clue...

```
If y is a single value, a one-sample T-test is computed.
```

but what's missing is the effect of the different values y could then take on the test.

Please understand - just repeating "but it's very clear" never helps fixing documentation issues.

**Comment by manfred2020** [comment]
i'm not familiar with R, i do not use is, googled t.test() R for the first time.

first thing is, that you need to know what a one sample t-test does. i think you know that because otherwise you won't calculate it with R or python.
but then you also know that you need a single value against which your sample is tested.

so, in sum, i'm not sure where the problem is. when you know what a t-test does, you will find the pingouin documentation and the R t-test doc very easy.

**Comment by FlorinAndrei** [comment]
> i'm not sure where the problem is

Modify the phrase like this:

```
If y is a single value, a one-sample T-test is computed against that value.
```

And then folks transitioning from R would go "oh, that's like the default for mu in R".

`t.test(sample)` (no parameters but the sample) is very idiomatic in R, whereas `pg.ttest()` seems written (if you've been indoctrinated by R) for a two-sample test, which may create confusion about the value of mu.

I'm not trying to be annoying here, and I've been on the other side of the table, too. Sometimes when you're extremely familiar with something you forget the stepping stones that beginners have to use to get there.

Thank you for your patience.

**Comment by sappelhoff** [comment]
@FlorinAndrei I find your second suggestion reasonable

> If y is a single value, a one-sample T-test is computed against that value.

would be an improvement over the current

>  If y is a single value, a one-sample T-test is computed.

in my humble opinion.

**Comment by raphaelvallat** [comment]
Thank you all for your input! I've now modified the doc as follow:

>     y : array_like or float
>         Second set of observations. If ``y`` is a single value, a one-sample
>         T-test is computed against that value, which is assumed to be the
>         true value of the mean (= "mu" in the t.test R function).

These changes are on the develop branch, but I'm hoping to release a new minor version soon.

Thanks
Raphael

**Comment by manfred2020** [comment]
it's getting complicated... 

> > y : array_like or float
> >     Second set of observations. If ``y`` is a single value, a one-sample
> >     T-test is computed against that value, which is assumed to be the
> >     true value of the mean (= "mu" in the t.test R function).
> > ```
> 
> These changes are on the develop branch, but I'm hoping to release a new minor version soon.

this " which is assumed to be the true value of the mean" is not true. it can be the true value of the mean, it can be any value. in most uses cases it will be any value, e.g. your height compared to a sample of top 100 basketball players height.

so please do not 'improve' the original doc with a misleading doc.

i would suggest: "Second set of observations. If ``y`` is a single value, a one-sample
> >     T-test is computed against that value.

that's it, that's what a one sample t-test does.

**Comment by raphaelvallat** [comment]
What about:

> y : array_like or float
>     Second set of observations. If ``y`` is a single value, a one-sample
>     T-test is computed against that value (= "mu" in the t.test R function).

**Comment by manfred2020** [comment]
ok, if you want to keep that R reference :-)
