### ISSUE TITLE
Feature request: add custom confidence level to ttest()

### ISSUE THREAD

**Issue by FlorinAndrei** [raphaelvallat/pingouin#152]
`ttest()` works great, but the confidence level is set in stone at 0.95

It would be nice to add a parameter to `ttest()` so users can set different CLs.

Thanks!

**Comment by raphaelvallat** [comment]
Hi @FlorinAndrei,

I just added (and validated against R) a `confidence=0.95` parameter in pg.ttest. The changes are visible [in the develop branch](85cd4ab96cff07e7dd9be4d9c0801e2a47b0468a), and I'm hoping to release a new stable version of Pingouin very soon. 

Thanks!
