### ISSUE TITLE
Planned comparisons pairwise_ttest

### ISSUE THREAD

**Issue by vb690** [raphaelvallat/pingouin#154]
Hello :)

do you think it could be valuable to be able to spcify planned comparisons in `pairwise_ttest` (I suspect this might also apply to other post-hoc tests).

I know it calls for data dredging but it is a pity having to run all the possible comparisons when only a few are of interests.

**Comment by raphaelvallat** [comment]
HI @vb690,

Could you provide an example (using real or fake data) of the modifications you'd like to see on the input/output of the current function? That'd be great. That said, the pairwise_ttests function is already quite complex and I'm a bit reluctant to complicate it even further.

Thanks,
Raphael

**Comment by vb690** [comment]
Hi @raphaelvallat, 
first of all, amazing job with this library.

As for the example, given a DataFrame `df`:

| Subject | Factor | DV | 
|---------|--------|----|
| 1       | A      | 3  |  
| 2       | A      | 4  |  
| 3       | A      | 6  |  
| 1       | B      | 7  |  
| 2       | B      | 2  |  
| 3       | B      | 9  |  
| 1       | C      | 8  |  
| 2       | C      | 1  |  
| 3       | C      | 3  |   

Let's assume (given theoretical basis) that after a repeated measure ANOVA , I would like to know through pairwise t-tests if `A<B`, `B<C` but I do not care about the difference between `A `and `C`. Maybe having an additional parameter `contrasts` in `pairwise_ttest` could be handy

```python
table = pg.pairwise_ttests(
    dv='DV', 
    within='Time',
    subject='Subject', 
    contrasts=[('A','B'), ('B', 'C')]
    data=df
 )
 ```
 as an output I would expect the same table returned by the current function but reporting only the specified contrasts.
 
 Skimming the code in the repository, I naively thought that a condition could be added [here](https://github.com/raphaelvallat/pingouin/blob/58df89197905c7382ee721e57c8abf9fa748e7df/pingouin/pairwise.py#L344) checking for `contrasts is not None` but I've likely overlooked some important detail. 
 
 I am aware that this is more a convenience feature (e.g. avoid clogging when `Factor` has many levels) and it would lead to slightly different output only in fringe cases (e.g. bonferroni correction).

**Comment by raphaelvallat** [comment]
Hi @vb690,

Thanks for this exhaustive answer, this is super helpful! I like your idea, and I think it could be quite straightforward to implement for one-way designs (repeated measures or independent). However, it's gonna be a mess when dealing with interaction terms. Are you aware of any software or R package that offers such planned comparison for two-way interaction? If not, how would you implement it?

Cheers,
Raphael

**Comment by vb690** [comment]
Hi :)

aplogies for the late response but I tried to understand how pinguoin deals with interactions in `pairwise_ttest`. 
As you said the function looks quite complex and all the initial ideas I had seem rather unfit.

I thought that maybe a solution based on [DataFrame.query()](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.query.html) in conjunction with a patsy-like specification of the contrasts might have worked but half-way through I realized it was more complicated than I thought.

So I did a bit more of googling and it seems that the r package [emmeans ](https://cran.r-project.org/web/packages/emmeans/vignettes/comparisons.html) allows you to specify planned pairwise comparisons through a contrast matrix.

However it seems to me that also this approach would not be easy to integrate with the current implementation of `pairwise_ttest`.

Best
Valerio

**Comment by raphaelvallat** [comment]
Hi @vb690,

I agree that specifying a contrast matrix would not work with the current implementation. In truth, I think that the simplest way to focus on specific contrasts is to run the pairwise_ttests function on all possible contrasts, then keep only the relevant rows, and then calculate the corrected p-values using the pingouin.multicomp function. If that sounds like a good compromise, I'll close this issue.

Thanks,
Raphael

**Comment by vb690** [comment]
Hi @raphaelvallat 

that seems very sensible.

Best
Valerio
