### ISSUE TITLE
Comparing correlation

### ISSUE THREAD

**Issue by orduek** [raphaelvallat/pingouin#157]
I think it would be a great addition to this library if we can implement a way to compare dependent or independent correlations. 
There is already an example function for that from here:
https://github.com/psinger/CorrelationStats/blob/master/corrstats.py

**Comment by raphaelvallat** [comment]
Hi @orduek,

Thank you for opening the issue. This seems indeed pretty straightforward to implement. That said, Pingouin already returns the confidence intervals of correlation coefficients, which I think can be used to compare the coefficients (see for example [this article](https://www.researchgate.net/publication/5671680_Toward_Using_Confidence_Intervals_to_Compare_Correlations)). Plus, both methods works by converting the r values to z values, so I'm guessing that they should return pretty similar results. What do you think?

Thanks,
Raphael

**Comment by orduek** [comment]
Seems reasonable. I'll take a look at the paper and try to write something up. 
I shouldn't be too complicated indeed.

**Comment by raphaelvallat** [comment]
Closing this issue but please feel free to reopen
