### ISSUE TITLE
info about Partial Rank Correlation Coefficents (PRCC) 

### ISSUE THREAD

**Issue by giupardeb** [raphaelvallat/pingouin#159]
Hi guys, I'm looking for a function to compute the partial rank correlation coefficients (PRCC). in your library, I found this [function](https://pingouin-stats.org/generated/pingouin.partial_corr.html), is there the function that allow me to compute the PRCC? Thanks!

**Comment by raphaelvallat** [comment]
Hi @giupardeb,

Yes you can use the [pingouin.partial_corr](https://pingouin-stats.org/generated/pingouin.partial_corr.html) function with `method='spearman'` to calculate a partial rank correlation. If you have multiple correlations to calculate, you can also use the [pingouin.pairwise_corr](https://pingouin-stats.org/generated/pingouin.pairwise_corr.html#pingouin.pairwise_corr) function.

Thanks
Raphael

**Comment by raphaelvallat** [comment]
Closing this issue, but feel free to reopen.

**Comment by giupardeb** [comment]
@raphaelvallat Thank you so much for your help. I have another question, Is it possible to calculate PRCC over time? I Try to explain myself better.. I perform 1000 sample on 1 parameter using the LHS algorithm, after that I run my model 1000 times by varying the parameter. So, I have the LHS matrix with 1000 rows, and output model matrix with 1000 columns and N rows. Can I perform PRCC over time with these matrix? I hope I was clear.

**Comment by raphaelvallat** [comment]
Hi @giupardeb,

If I understood correctly, you will have to implement some sort a _for loop_ (or numpy.apply_along_axis) to iteratively calculate the PRCC across one dimension of your matrix (which I assume is time). This might be a bit slow, but I cannot think of a better alternative, at least not in Pingouin.

Hope this helps!
Raphael

**Comment by giupardeb** [comment]
> Hi @giupardeb,
> 
> If I understood correctly, you will have to implement some sort a _for loop_ (or numpy.apply_along_axis) to iteratively calculate the PRCC across one dimension of your matrix (which I assume is time). This might be a bit slow, but I cannot think of a better alternative, at least not in Pingouin.
> 
> Hope this helps!
> Raphael

Thank you very much! you was very useful! If I can, I would like to do you another question about the pairwise_corr. I have a dataframe with 3 columns [["a"], ["b", "c"]] and I want to do the product between [“a”] and [“b”, “c”]. If the values of all rows of the column "b" are zero, then the column b was delete from the output of the matrix. Does this happens because the values of are all NaN ?

I hope I was cleare

Thanks again

**Comment by raphaelvallat** [comment]
Hi @giupardeb,

Indeed, columns with constant values are removed from the dataframe before calculating the pairwise correlation, see:

https://github.com/raphaelvallat/pingouin/blob/91b184780d27f291ff9f894d1c80f74c0c20e146/pingouin/pairwise.py#L1101-L1102

Thanks,
Raphael
