### ISSUE TITLE
pairwise_corr with covariates // multiple comparison correction

### ISSUE THREAD

**Issue by dominikkraft** [raphaelvallat/pingouin#162]
Hi @raphaelvallat,

I am using your pairwise_corr function with covariates to calculate (partial) correlations between columns in a pandas dataframe. This  relates to [PR 124](https://github.com/raphaelvallat/pingouin/pull/124).

I was however wondering why the current implementation includes correlations between the columns and covariates, too? I see that there are situation in which this might be certainly of interest, but when correcting for multiple testing it adds additional comparisons one has to deal with. See Screenshot below:

<img width="500" alt="Bildschirmfoto 2021-03-15 um 10 57 42" src="https://user-images.githubusercontent.com/37620024/111137710-68c4c980-857f-11eb-9173-5fecde23d945.png">

I am currently not aware of a (statistical) reason to include these tests - if there is one, it would be great if you could share it!

If there is no strong reason, it would be great to include an `argument` for `pairwise_corr` that would allow to enable this step or adjust `padjust` accordingly. Let me know what you think, would be happy to help! 

Best,
Dominik

**Comment by raphaelvallat** [comment]
Hi @dominikkraft,

Thanks for opening the issue!

> I was however wondering why the current implementation includes correlations between the columns and covariates, too?

It shouldn't...! How are you using the pairwise_corr functions? Is there any chance that you could share an example with full code and using Pingouin example datasets (e.g. `pg.read_dataset("pairwise_corr")`)?

Best,
Raphael

**Comment by dominikkraft** [comment]
I followed example "3" from `pairwise_corr?` and the screenshot above resulted from: 

`pg.pairwise_corr(data = funcnet_df, columns=[quest], padjust="fdr_bh", 
                               covar=["age", "gender", "fd"]).round(3)`

where `columns=[quest]` refers to a single string.

I get the same for your example dataset : 

<img width="641" alt="Bildschirmfoto 2021-03-15 um 16 55 14" src="https://user-images.githubusercontent.com/37620024/111182536-48146800-85af-11eb-85b5-d82e95236003.png">

**Comment by raphaelvallat** [comment]
Hi @dominikkraft,

You're right, something is wrong here. I think there was a misunderstanding in [PR 124](https://github.com/raphaelvallat/pingouin/pull/124), i.e. I didn't understand that this would become the default behavior. I'll have to revert the changes in the next release.

Thanks for opening the issue,
Raphael

**Comment by raphaelvallat** [comment]
Pinging @JoElfner: So I thought that the _"full partial correlation"_ behavior would only be applied in the specific case of `columns=None` and `covar=data.columns` (i.e. all columns). It seems however that this behavior is always applied when `columns=None`, which I think is not right. Let me know what you think.

Thanks for your help,
Raphael

**Comment by dominikkraft** [comment]
thanks @raphaelvallat, 
if this is settled, I suggest to include an example also here [in the examples](uhttps://github.com/raphaelvallat/pingouin/blob/master/notebooks/04_Correlations.ipynbrl) as the cases there only cover the described behavior as far as I see.
Let me know if I can be of any help.

Best,
Dominik

**Comment by raphaelvallat** [comment]
Changes have now been reverted in bb83d84ae7f8d54b85ddceda4c5b82af5c2bdcf3

I am hoping to release a new version of Pingouin within the next week.

Thanks again,
Raphael

**Comment by raphaelvallat** [comment]
Closing this issue but please feel free to reopen.

**Comment by dominikkraft** [comment]
works like a charm now in 0.3.11! 
thanks again @raphaelvallat
