### ISSUE TITLE
Multivariate ICC?

### ISSUE THREAD

**Issue by dPys** [raphaelvallat/pingouin#163]
What would be needed to support this? See so-called [I2C2](https://github.com/muschellij2/I2C2/blob/master/R/I2C2.R)

If you point me in the right direction, I'd be happy to start a PR.

**Comment by raphaelvallat** [comment]
Hi @dPys,

- [Link to the paper describing the I2C2](https://link.springer.com/article/10.3758/s13415-013-0196-0)

Thanks for opening the issue and suggesting this new feature. I wasn't familiar with it, and after a quick read of the paper, it seems that it is a highly-specific function that would be more adequate in image-processing packages such as [scikit-image](https://scikit-image.org/), or even fMRI analysis packages such as [nilearn](https://nilearn.github.io/).

Best,
Raphael

**Comment by dPys** [comment]
Thanks for the quick reply! 

Indeed, I2C2 was invented in the context of imaging studies where it was most immediately applicable. Perhaps I will bug the scikit-image people instead.

More generally speaking though, would it not be possible to enhance pingouin.intraclass_corr such that Scores can optionally be vectors and not just scalar values? i.e. using manova instead of just anova [here](https://github.com/raphaelvallat/pingouin/blob/master/pingouin/reliability.py#L300)?

**Comment by raphaelvallat** [comment]
Hi @dPys,

Is that something you've seen in other statistical softwares (R, JASP)? Currently, there is no MANOVA module in Pingouin, which would be required to implement what you suggest. I'd like to implement it in the future though.

Thanks
Raphael

**Comment by raphaelvallat** [comment]
Closing this issue but please feel free to reopen
