### ISSUE TITLE
problem with convergence in mixed_anova

### ISSUE THREAD

**Issue by zeydabadi** [raphaelvallat/pingouin#166]
My dataframe has three groups, 6 subjects (channels), and 60 time-points per subject. 
The first group has 15 time-points, the second has 30 time-points, and the third has 15 time-points, so the data is unbalanced.
[https://drive.google.com/file/d/14rW2cqfHsAaNplQzoPnHvmBFsZO5pYu-/view?usp=sharing](url)

I am running the following code:
`aov = pg.mixed_anova(dv='DFreq', within='Time', between='Group', subject='Channel', data=DFreq_df)`

and this gives me the blow error:
`/home/lucy/.local/lib/python3.8/site-packages/numpy/lib/function_base.py:380: RuntimeWarning: Mean of empty slice.
  avg = a.mean(axis)
/home/lucy/.local/lib/python3.8/site-packages/numpy/core/_methods.py:162: RuntimeWarning: invalid value encountered in true_divide
  ret = um.true_divide(
/home/lucy/.local/lib/python3.8/site-packages/pandas/core/frame.py:8525: RuntimeWarning: Degrees of freedom <= 0 for slice
  base_cov = np.cov(mat.T, ddof=ddof)
/home/lucy/.local/lib/python3.8/site-packages/numpy/lib/function_base.py:2480: RuntimeWarning: divide by zero encountered in true_divide
  c *= np.true_divide(1, fact)
/home/lucy/.local/lib/python3.8/site-packages/numpy/lib/function_base.py:2480: RuntimeWarning: invalid value encountered in multiply
  c *= np.true_divide(1, fact)
---------------------------------------------------------------------------
LinAlgError                               Traceback (most recent call last)
project_functions.py in <module>
      1 # Compute the two-way mixed-design ANOVA
----> 2 aov = pg.mixed_anova(dv='DFreq', within='Time', between='Group', subject='Channel', data=DFreq_df)
      3 # Pretty printing of ANOVA summary
      4 pg.print_table(aov)

~/.local/lib/python3.8/site-packages/pingouin/parametric.py in mixed_anova(data, dv, within, subject, between, correction, effsize)
   1470     ss_total = ((data[dv] - grandmean)**2).sum()
   1471     # Extract main effects of within and between factors
-> 1472     aov_with = rm_anova(dv=dv, within=within, subject=subject, data=data,
   1473                         correction=correction, detailed=True)
   1474     aov_betw = anova(dv=dv, between=between, data=data, detailed=True)

~/.local/lib/python3.8/site-packages/pingouin/parametric.py in rm_anova(data, dv, within, subject, correction, detailed, effsize)
    586     if correction == 'auto' or (correction is True and n_rm >= 3):
    587         spher, W_spher, chi_sq_spher, ddof_spher, \
--> 588             p_spher = sphericity(data_pivot, alpha=.05)
    589         if correction == 'auto':
    590             correction = True if not spher else False

~/.local/lib/python3.8/site-packages/pingouin/distribution.py in sphericity(data, dv, within, subject, method, alpha)
    946         S = data.cov().to_numpy()  # NumPy, otherwise S.mean() != grandmean
    947         S_pop = S - S.mean(0)[:, None] - S.mean(1)[None, :] + S.mean()
--> 948         eig = np.linalg.eigvalsh(S_pop)[1:]
    949         eig = eig[eig > 0.001]  # Additional check to remove very low eig
    950         W = np.product(eig) / (eig.sum() / d)**d

<__array_function__ internals> in eigvalsh(*args, **kwargs)

~/.local/lib/python3.8/site-packages/numpy/linalg/linalg.py in eigvalsh(a, UPLO)
   1174     t, result_t = _commonType(a)
   1175     signature = 'D->d' if isComplexType(t) else 'd->d'
-> 1176     w = gufunc(a, signature=signature, extobj=extobj)
   1177     return w.astype(_realType(result_t), copy=False)
   1178 

~/.local/lib/python3.8/site-packages/numpy/linalg/linalg.py in _raise_linalgerror_eigenvalues_nonconvergence(err, flag)
     92 
     93 def _raise_linalgerror_eigenvalues_nonconvergence(err, flag):
---> 94     raise LinAlgError("Eigenvalues did not converge")
     95 
     96 def _raise_linalgerror_svd_nonconvergence(err, flag):

LinAlgError: Eigenvalues did not converge
`
Can you please tell me what is going wrong?

**Comment by raphaelvallat** [comment]
Hi @zeydabadi,

Without seeing the data it's hard for me to know what is wrong, as I've never seen this error before. A few points though: 

1. Can you try passing `pg.mixed_anova(..., correction=False`)? 
2. Can you compute a simple between-group ANOVA (`pg.anova`), and then a repeated-measures ANOVA (`pg.rm_anova`) to check if they work?
3. Can you run the mixed ANOVA in  [JASP](https://jasp-stats.org/)?

PS: For future similar questions, please use the Gitter channel instead: https://gitter.im/pingouin-stats/Lobby

Thanks,
Raphael

**Comment by zeydabadi** [comment]
I have saved data in csv format and shared the link to it. Are you able to
download it?

**Comment by zeydabadi** [comment]
trying `pg.mixed_anova(dv='DFreq', within='Time', between='Group', subject='Channel', data=DFreq_df, correction=False)` throws this error `KeyError                                  Traceback (most recent call last)
~/.local/lib/python3.8/site-packages/pandas/core/indexes/base.py in get_loc(self, key, method, tolerance)
   3079             try:
-> 3080                 return self._engine.get_loc(casted_key)
   3081             except KeyError as err:

pandas/_libs/index.pyx in pandas._libs.index.IndexEngine.get_loc()

pandas/_libs/index.pyx in pandas._libs.index.IndexEngine.get_loc()

pandas/_libs/hashtable_class_helper.pxi in pandas._libs.hashtable.PyObjectHashTable.get_item()

pandas/_libs/hashtable_class_helper.pxi in pandas._libs.hashtable.PyObjectHashTable.get_item()

KeyError: 'eps'`

**Comment by zeydabadi** [comment]
trying `pg.anova(dv='DFreq', between='Group', data=DFreq_df)` was successful and here is the output:
`=============
ANOVA SUMMARY
=============

Source      ddof1    ddof2      F    p-unc    np2
--------  -------  -------  -----  -------  -----
Group           2      357  2.682    0.070  0.015
`

**Comment by raphaelvallat** [comment]
Hi @zeydabadi,

Got it. I think the issue is driven by the fact that you have 60 levels in your within-subject factor (which is way more than usual in typical ANOVAs) and this might be leading to errors when trying to calculate the [sphericity](https://pingouin-stats.org/generated/pingouin.sphericity.html) assumption. Instead of using a mixed ANOVA here, I think a much more adequate solution is to use a linear mixed effect model, as implemented in the [LME4 package in R](https://www.rdocumentation.org/packages/lme4/versions/1.1-26/topics/lmer). Linear mixed-effect models are also capable of handling missing values / imbalance in your repeated measurements, and are therefore always more helpful than mixed ANOVA.

Thanks,
Raphael

**Comment by zeydabadi** [comment]
Thanks Raphael, do you know any Python method for doing linear mixed model?

**Comment by raphaelvallat** [comment]
The two best options are probably:
- https://github.com/ejolly/pymer4
- https://www.statsmodels.org/stable/generated/statsmodels.regression.mixed_linear_model.MixedLM.html
