### ISSUE TITLE
pairwise ttests error

### ISSUE THREAD

**Issue by mohammad2682** [raphaelvallat/pingouin#168]
Dear Dr Vallat

I'm using your pleasant pingouin package for my thesis. I've made two dataframes in my work, one for VBM analysis and another for FDG-PET. in second one I got an error when I'm using pairwise-ttests module. I don't know what's the problem, while it works correctly when I'm using anova or pairwise-tukey modules on this dataframe. I'll appreciate it if you could help me to solve this problem. this is the error I've got: 

`UnboundLocalError                         Traceback (most recent call last)
<ipython-input-45-db46efc6bd42> in <module>
      3 test = test.replace(r'^\s*$', np.nan, regex=True)
      4 test[feature]=test[feature].astype(float)
----> 5 pairwise_ttests(dv=feature, between=['Group', 'SDB'], data=test, padjust='bonf', tail='one-sided')

~/DataScience/DataScience/lib/python3.8/site-packages/pingouin/pairwise.py in pairwise_ttests(data, dv, between, within, subject, parametric, marginal, alpha, tail, padjust, effsize, correction, nan_policy, return_desc, interaction, within_first)
    377             if parametric:
    378                 stat_name = 'T'
--> 379                 df_ttest = ttest(x, y, paired=paired, tail=tail,
    380                                  correction=correction)
    381                 stats.at[i, 'BF10'] = df_ttest.at['T-test', 'BF10']

~/DataScience/DataScience/lib/python3.8/site-packages/pingouin/parametric.py in ttest(x, y, paired, tail, correction, r, confidence)
    247     if tail == 'one-sided':
    248         # Automatically decide which tail to use based on the T-value
--> 249         tail = 'greater' if tval > 0 else 'less'
    250 
    251     if tail == 'greater':

UnboundLocalError: local variable 'tval' referenced before assignment`

**Comment by mohammad2682** [comment]
after applying some corrections on data, I got below error:

AssertionError                            Traceback (most recent call last)
<ipython-input-18-9fef08e03b6f> in <module>
      3 test = test.replace(r'^\s*$', np.nan, regex=True)
      4 test[feature]=test[feature].astype(float)
----> 5 pairwise_ttests(dv=feature, between=['Group', 'SDB'], data=test, padjust='bonf', tail='one-sided')

~/DataScience/DataScience/lib/python3.8/site-packages/pingouin/pairwise.py in pairwise_ttests(data, dv, between, within, subject, parametric, marginal, alpha, tail, padjust, effsize, correction, nan_policy, return_desc, interaction, within_first)
    525                 if parametric:
    526                     stat_name = 'T'
--> 527                     df_ttest = ttest(x, y, paired=paired, tail=tail,
    528                                      correction=correction)
    529                     stats.at[ic, 'BF10'] = df_ttest.at['T-test', 'BF10']

~/DataScience/DataScience/lib/python3.8/site-packages/pingouin/parametric.py in ttest(x, y, paired, tail, correction, r, confidence)
    298 
    299     # Bayes factor
--> 300     bf = bayesfactor_ttest(tval, nx, ny, paired=paired, tail=tail, r=r)
    301 
    302     # Create output dictionnary

~/DataScience/DataScience/lib/python3.8/site-packages/pingouin/bayesian.py in bayesfactor_ttest(t, nx, ny, paired, tail, r)
    130 
    131     # Check T-value
--> 132     assert isinstance(t, (int, float)), 'The T-value must be a int or a float.'
    133     if not np.isfinite(t):
    134         return np.nan

AssertionError: The T-value must be a int or a float.

**Comment by raphaelvallat** [comment]
Hi @mohammad2682,

Does it work if you remove the `padjust='bonf'` and/or `tail='one-sided'`?

**Comment by mohammad2682** [comment]
no it doesn't.
actually after some investigating in detail, I figuered out this error happens because in one of groups, there is just one valid data sample and others are NaN. so dof and T-value become <=0 and NaN respectively.
I thought it would be useful to share this with other users.
thanks for your time
