### ISSUE TITLE
New feature: Pearson's chi-squared test.

### ISSUE THREAD

**Issue by arthurpaulino** [raphaelvallat/pingouin#17]
[This is a test](https://en.wikipedia.org/wiki/Pearson%27s_chi-squared_test) that I use a lot to understand the relationship between categorical data.

[SciPy](https://docs.scipy.org/doc/scipy/reference/generated/scipy.stats.chi2_contingency.html) has it's own implementation, but we have to feed it with a contingency table. The contingency table is easy to build (using `pandas.crosstab`, for instance), but I think it would be an improvement for the user experience to simply call `pg.pearson_chi2(x, y)` or something like that.

SciPy's implementation returns the χ², the p-value, the degrees of freedom and a contingency table with the expected values (for which there would be no correlation between the columns). But I think it would be possible to infer more information from the test, just like you did with `pg.ttest`?

Best regards,
Arthur Paulino

**Comment by raphaelvallat** [comment]
Hi @arthurpaulino!

Thank you for your message! I don't use this test very often, but I'd be happy to implement it in the next release (or more realistically the one after the next). It would be very helpful if you could share a Jupyter Notebook showing how you would typically do this test using Pandas + SciPy, as well as the kind of metrics / information that you would be interested in having as an output of the `pg.pearson_chi2` function.

Best,
Raphael

**Comment by arthurpaulino** [comment]
Hello @raphaelvallat,

Sure, I'm working on it. While researching, I think I found how the extra metrics could be explicit on the results.

The test can be performed with a few different values for `lambda_`, as seen [here](https://docs.scipy.org/doc/scipy/reference/generated/scipy.stats.power_divergence.html#scipy.stats.power_divergence). And for each value of `lambda_`, there should be a different pair of χ² and p-value.

Wrapping it up, `pg.chi2` could return tests for each `lambda_` (not just for the Pearson's) as well as the degree of freedom and the contingency table with expected frequencies.

I'll be back soon with the Jupyter Notebook.

**Comment by arthurpaulino** [comment]
Alright, that took a while. It was a good learning experience for me.

I tried to keep the example as minimal and organized as possible. The result is somewhat close to a final version of what `gp.chi2` would look like. The notebook link is [here](https://www.kaggle.com/arthurpaulino/chi-squared-tests-example).

It was inspired by [SciPy's implementation](https://github.com/scipy/scipy/blob/6e782cae26e9b27ecc5994e99c7692cad54825b6/scipy/stats/contingency.py#L112), which is more robust and incorporates a few more checks that would be healthy in the final version of `gp.chi2`, I think.

**Comment by raphaelvallat** [comment]
Thank you @arthurpaulino, this looks great! I'm gonna look at that more in details this weekend, and hopefully should be able to include it in the next release or so then. (Btw if you prefer to work on a PR of your own, please feel free to fork the develop branch and submit it when you're done ;-))
Thanks!

**Comment by arthurpaulino** [comment]
> Btw if you prefer to work on a PR of your own, please feel free to fork the develop branch and submit it when you're done ;-)

That'd be great. I'm just a bit busy lately, but I'm eager to participate and help :D

**Comment by arthurpaulino** [comment]
Working on it and learning a lot! (https://github.com/arthurpaulino/pingouin/commit/41f176f176c27c4e1d17e2832a6b603d25061ef2)

I'll implement the tests tomorrow. Any feedback is already welcome :smiley:

**Comment by arthurpaulino** [comment]
Working on it and learning a lot! (https://github.com/arthurpaulino/pingouin/commit/41f176f176c27c4e1d17e2832a6b603d25061ef2)

I'll implement the tests tomorrow. Any feedback is welcome :smiley:

**Comment by raphaelvallat** [comment]
This looks absolutely great @arthurpaulino ! Amazing job, can't wait to try it out!

**Comment by raphaelvallat** [comment]
PS: you also need to add the datasets to the [MANIFEST.in](https://github.com/raphaelvallat/pingouin/blob/master/MANIFEST.in) file, otherwise the example dataset will not be installed with pip!

Thanks!
