### ISSUE TITLE
Add Box's M test

### ISSUE THREAD

**Issue by GanshengT** [raphaelvallat/pingouin#170]
Box’s M test can be used to verify an assumption of mixed ANOVA - **homogeneity of variance-covariance matrices**. It would be nice if we could add this to Pingouin. In my opinion, this function takes pandas.Dataframe as input and returns the statistics and p-value.

**Comment by raphaelvallat** [comment]
Thanks for opening the issue. I agree that it would make a nice addition to Pingouin. For reference, a R implementation of this function can be found here: https://rdrr.io/cran/MVTests/man/BoxM.html, and mathematical formula can be found https://www.real-statistics.com/multivariate-statistics/boxs-test/boxs-test-basic-concepts/

**Comment by GanshengT** [comment]
After going through the R implementation of Box's M, I found that it is used in MANOVA (multivariate ANOVA) where there are multiple dependent variables.  The Box's M should be applicable for testing the homogeneity of covariances of the between-subject factor in mixed ANOVA design and testing the equality of covariance matrices for the dependent variables across groups in MANOVA.

**Comment by raphaelvallat** [comment]
Thanks @GanshengT, unfortunately, MANOVA is not yet implemented in Pingouin. Would it be possible to do a generic implementation in which users directly pass the covariance matrices that they can test? (instead of a dataframe and grouping variable like the R implementation)

**Comment by GanshengT** [comment]
This should be less exhausting. We just need to make sure the calculation is correct.

**Comment by GanshengT** [comment]
I have made a pull request.
