### ISSUE TITLE
Different std. and statistics for pairwise t-tests when specifying "within"-factor

### ISSUE THREAD

**Issue by mno-93** [raphaelvallat/pingouin#172]
I just wondered when I rechecked the "Condition" output of the 
`pingouin.pairwise_ttests(dv = "Score" , between = "GROUP", within = "TIME", subject = "ID",  data = data, correction = True, return_desc = True)`
I compared it to `pinguin.pairwise_ttests(dv="Score", between="GROUP", data = data, correction = True, return_desc = True)`

This gave different results for the standard deviations and t-test statistics. Is this due to some pooling of the standard deviation.
When reporting this, which one is more reliable?
It was actually meant to be a posthoc analysis of a 2-way mixed ANOVA analysis using pinguin.mixed_anova()

Thanks for helping out.

**Comment by raphaelvallat** [comment]
Hi @mno-93,

When using a mixed design, Pingouin will automatically average across all levels of the within-subject factor before calculating the between-subject statistics. This is recommended to avoid violating the assumption of independence and conflating the degrees of freedom by the number of repeated measurements. You can disable this behavior by setting `pingouin.pairwise_ttests(..., marginal=False)` which should give you similar results whether you specify a within-factor or not. 

Please note that Pingouin uses a slightly different strategy than [JASP](https://jasp-stats.org/) or [JAMOVI](https://www.jamovi.org/) (see https://github.com/raphaelvallat/pingouin/issues/80), so I strongly recommend checking your results with either of these two softwares.

Thanks,
Raphael
