### ISSUE TITLE
Generalized Estimating Equations

### ISSUE THREAD

**Issue by malekpour-mreza** [raphaelvallat/pingouin#178]
Hello,
Pingouin is just what statisticians needed in the Python environment, thanks for your great job. I believe the addition of generalized linear models, specifically Generalized Estimating Equations (GEE), can provide considerable added value. GEE can be used for panel, cluster, or repeated measures data when the observations are possibly correlated within a cluster but uncorrelated across clusters. In addition, it needs non of the rm_anova or mixed ANOVA assumptions.

**Comment by raphaelvallat** [comment]
Hi @malekpour-mreza,

This is partially related to https://github.com/raphaelvallat/pingouin/issues/103. I agree that it would make a nice addition to Pingouin, however:

1) Such models are already implemented in statsmodels, so we don't want to "reinvent the wheel" (see https://www.statsmodels.org/stable/glm.html).

2) This will require a considerable amount of time, which I currently do not have. But please do feel free to work on a PR!

Cheers,
Raphael

**Comment by raphaelvallat** [comment]
Closing for now but please feel free to reopen
