### ISSUE TITLE
Errors for using N-way ANOVA

### ISSUE THREAD

**Issue by JacobBaxley** [raphaelvallat/pingouin#181]
I'm trying to use an N-way ANOVA on this data frame to collect the f values.
<img width="400" alt="df" src="https://user-images.githubusercontent.com/70708344/122997907-13fcd000-d372-11eb-99bd-a62b8c845cb3.png">

However when trying to use the function ANOVA I get the following error.
<img width="305" alt="error" src="https://user-images.githubusercontent.com/70708344/122998937-40fdb280-d373-11eb-9b8d-ec34ba0254fe.png">

**Comment by raphaelvallat** [comment]
Hi @JacobBaxley,

I think your ANOVA is ill-specified: you are doing a 4-way ANOVA with only one unique value for each unique subgroup (e.g. subgroup[donor = 10, total_concentration = 20, spin = 3000, additive = 2]: only one value in the dependent variable PCE). To calculate an ANOVA, you need at least >3 samples in each subgroup. Accordingly, only including one of the between factors in the ANOVA model should work just fine.

Thanks,
Raphael
