### ISSUE TITLE
RuntimeWarning: divide by zero encountered in arctanh for spearman correlation

### ISSUE THREAD

**Issue by krassowski** [raphaelvallat/pingouin#183]
Running perfect correlation results in two warnings which seem spurious in this context:

```python
import pingouin as pg

x = list(range(1000))
y = list(reversed(x))

pg.corr(x, y, method='spearman')
```

. | n | r | CI95% | p-val | power
-- | -- | -- | -- | -- | -- 
spearman | 1000 | -1.0 | [-1.0, -1.0] | 0.0 | 1.0

Warnings:

```
python3.9/site-packages/pingouin/effsize.py:135: RuntimeWarning: divide by zero encountered in arctanh
  z = np.arctanh(stat)  # R-to-z transform
python3.9/site-packages/pingouin/power.py:899: RuntimeWarning: divide by zero encountered in arctanh
  zr = np.arctanh(r) + r / (2 * (n - 1))
```

Disabling these warnings would be especially useful for demonstrating various concepts using pingouin (and not scaring students with a wall of red text).

**Comment by raphaelvallat** [comment]
Hi @krassowski,

That's a good point. In fact, we could just skip [these two lines](https://github.com/raphaelvallat/pingouin/blob/ab5662b92ab730d50c430cf44703c4c2b62402fc/pingouin/correlation.py#L585) in the case of a perfect correlation, i.e.:

```python
if abs(r) == 1:
    ci = [r, r]
    pr = 1
else:
    # Compute the parametric 95% confidence interval and power
    ci = compute_esci(stat=r, nx=n_clean, ny=n_clean, eftype='r', decimals=6)
    pr = power_corr(r=r, n=n_clean, power=None, alpha=0.05, tail=tail),
```

**Comment by raphaelvallat** [comment]
This has been included in the new stable version of Pingouin ([v0.4.0](https://github.com/raphaelvallat/pingouin/releases/tag/v0.4.0)). Please make sure to upgrade with `pip install --upgrade pingouin`.

Thanks,
Closing the issue.

**Comment by krassowski** [comment]
I just realised that I have not thanked you for the quick fix earlier, so: thank you!

I also opened a new issue for a similar problem in 0.4.0 in partial correlations.
