### ISSUE TITLE
Diffrence Normality result between pingouin and SPSS

### ISSUE THREAD

**Issue by balandongiv** [raphaelvallat/pingouin#187]
I run a comparison for the `Normality` both in pingouin and SPSS. 

However, I notice, the result produced between these two platform are different

with `pingouin`

Table for `int`
```
     W  pval  normal
1  1.0   1.0    True  (issue)
2  1.0   1.0    True
3  1.0   1.0    True
```
with index 1,2,3 denote int_1, int_2, int_3, respectively
Table for `cond`
```
     W  pval  normal
1  1.0   1.0    True
2  1.0   1.0    True
3  1.0   1.0    True
```
with index 1,2,3 denote cond_1, cond_2, cond_3, respectively
Whereas, `SPSS` produce the following

![Snap 2021-08-01 at 00 11 36](https://user-images.githubusercontent.com/22090092/127746069-0b330d73-2f9c-46a2-9a05-4ba593b7e6c4.png)

Notice that, spss reported `int_1`(red line)  violated the normality assumption, whereas `pingouin` report the opposite (* indicate as issue in the `int` table).

May I know whether this is bug or some overlook from my side.

The Python code to reproduce the above result

import pingouin as pg
import pandas as pd

```
ls=['int','cond']
df=pd.read_excel('book.xlsx',header=0)
for my_ls in ls:
    df_f=df[df['condition']==my_ls]
    df_f['condition'] = df_f.condition.astype('category').cat.codes
    opt_=pg.normality(data=df_f,dv='condition',group='task_int')
    print(opt_)
```

The excel file  (book.xlsx) and spss file is accessible via the [link](https://drive.google.com/drive/folders/1HLkQEBEYp4KE9maH20gF8nUqM8ZfT5Jf?usp=sharing) https://drive.google.com/drive/folders/1HLkQEBEYp4KE9maH20gF8nUqM8ZfT5Jf?usp=sharing

**Comment by raphaelvallat** [comment]
Hi @balandongiv,

A few questions:

1. For safety, can you please share your data in CSV format and not XLSX? Thanks
2. I do not have a license for SPSS, have you tried with JASP or R?
3. Do you have missing values in your data? Pingouin will automatically remove those.
3. Pingouin uses [scipy.stats.shapiro](https://docs.scipy.org/doc/scipy/reference/generated/scipy.stats.shapiro.html) to calculate the p-values and W value. Could you calculate the p-values using scipy separately for each group and check that you get similar results?

Thanks,
Raphael

**Comment by balandongiv** [comment]
Thanks for prompt reply @raphaelvallat 

1. I have update the folder to include csv. ext
2. I have not tried neither JASP or R as Im not familiar with these two plaform
3. There were no missing value.

**Comment by raphaelvallat** [comment]
Hi @balandongiv,

Why do you use "condition" (which is a categorical) as the dependent variable? When I use `pow_freq_bands_ch0_band0` as the dependent variable:

```python
for my_ls in ls:
    df_f = df[df['condition'] == my_ls]
    opt_ = pg.normality(data=df_f, dv='pow_freq_bands_ch0_band0', group='task_int')
    display(opt_.round(3))
```

 I get the following output:

![image](https://user-images.githubusercontent.com/25703792/127957042-cf181674-ed16-45d8-8a06-f21e6de2ee18.png)

You can see that the W and p-values are all consistent with SPSS, despite some minor differences which I believe are caused by implementation differences between SPSS and [scipy.stats.shapiro](https://docs.scipy.org/doc/scipy/reference/generated/scipy.stats.shapiro.html).

Thanks,
Raphael

**Comment by balandongiv** [comment]
Thanks for validating the SPSS/pingouin output @raphaelvallat . Clearly I had made major mistake when posting this issue.
