### ISSUE TITLE
TestCorrelation::test_corr fails on some platforms

### ISSUE THREAD

**Issue by musicinmybrain** [raphaelvallat/pingouin#195]
I’m helping to update the `python-pingouin` package in Fedora Linux. One test, `TestCorrelation::test_corr`, is failing on some platforms because what should theoretically be a perfect unity correlation is coming out two or three ulps short:

```
        # Compare BF10 with JASP
        df = read_dataset('pairwise_corr')
        stats = corr(df['Neuroticism'], df['Extraversion'])
        assert np.isclose(1 / float(stats['BF10'].to_numpy()), 1.478e-13)
        # Perfect correlation, CI and power should be 1, BF should be Inf
        stats = corr(x, x)
>       assert stats.at['pearson', 'r'] == 1
E       AssertionError: assert 0.9999999999999997 == 1
```

This happens when the tests are executed on an `aarch64`, `ppc64le`, or `s390x` platform. (On `ppc64le` and `s390x`, the correlation is 0.9999999999999998.)

What do you think? Does this look like this a bug to be fixed somewhere, or should the assertion be loosened to permit a value slightly less than one due to platform-dependent rounding?

**Comment by raphaelvallat** [comment]
Hi @musicinmybrain,

Interesting — thanks for opening the issue and helping with this! I think it is definitely a platform-dependent rounding error so we should use `np.isclose(stats.at['pearson', 'r'], 1)` instead of the strict `==`.

Raphael

**Comment by musicinmybrain** [comment]
Makes sense to me. You could, if you like, add an additional test for `stats.at['pearson', 'r'] <= 1'`, since a high-quality implementation shouldn’t be producing correlations outside `[-1, 1]` no matter how the rounding happens to work out.

**Comment by raphaelvallat** [comment]
Done in 7f5f0cc083befebefabb853730596eb394b7f55d

See PR v0.5.1: https://github.com/raphaelvallat/pingouin/pull/236
