### ISSUE TITLE
TestRegression::test_linear_regression fails on 32-bit ARM

### ISSUE THREAD

**Issue by musicinmybrain** [raphaelvallat/pingouin#196]
I’m helping to update the `python-pingouin` package in Fedora Linux. One test, `TestRegression::test_linear_regression`, is failing on `armv7hl` (32-bit ARM) because an expected warning is not produced:

```

        # with rank deficient design matrix `X`
        # see: https://github.com/raphaelvallat/pingouin/issues/130
        n = 100
        rng = np.random.RandomState(42)
        X = np.vstack([rng.permutation([0, 1, 0, 0, 0]) for i in range(n)])
        y = rng.randn(n)
    
>       with pytest.warns(UserWarning, match='(rank 5 with 6 columns)'):
E       Failed: DID NOT WARN. No warnings of type (<class 'UserWarning'>,) was emitted. The list of emitted warnings is: [].
X          = array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 0, 1, 0]...      [0, 0, 0, 1, 0],
       [1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [1, 0, 0, 0, 0]])
[…]
y          = array([-0.92604662, -0.51296532,  0.71010924,  0.09247887,  0.63007494,
        1.76293747,  0.23095372, -0.80893689, ...097242,  0.43932714, -0.10849789, -0.48643277,
        0.20759826,  0.88499047, -0.46452975, -0.62223716, -0.35548864])
```

The line after the with-statement is:

```python
with pytest.warns(UserWarning, match='(rank 5 with 6 columns)'):
    res_pingouin = linear_regression(X, y, add_intercept=True)
```

At this time, I have not tried to look deeper into why this happens only on 32-bit ARM and not on the other platforms supported by Fedora.

**Comment by raphaelvallat** [comment]
Thanks! I cannot replicate this error on my Mac, but my guess is that it is related to the `cond` parameter of the [scipy.linalg.lstsq](https://docs.scipy.org/doc/scipy/reference/generated/scipy.linalg.lstsq.html) function (which is used to calculate the matrix rank). Can you check the following lines:

```python
import numpy as np
from scipy.linalg import lstsq
n = 100
rng = np.random.RandomState(42)
X = np.vstack([rng.permutation([0, 1, 0, 0, 0]) for i in range(n)])
y = rng.randn(n)
X = np.hstack((np.ones(shape=(n, 1)), X))
_, _, rank, _ = lstsq(X, y, cond=None)
assert rank == 5
```

Also, which version of NumPy and SciPy are you using? The default behavior of ``cond`` was changed to None [in Numpy 1.14.0](https://numpy.org/doc/stable/reference/generated/numpy.linalg.lstsq.html).

Raphael

**Comment by musicinmybrain** [comment]
I was testing this in the development version of Fedora (Rawhide), so NumPy was at 1.21.1 and SciPy was at 1.7.0.

I’ll try to replicate with the snippet you posted, first in a Python REPL in a 32-bit chroot on an 64-bit ARM machine. If that doesn’t get anywhere, I’ll add it as a scriptlet in the RPM spec file and do a scratch build to execute it on one of Fedora’s 32-bit ARM builders.

**Comment by musicinmybrain** [comment]
I forgot `aarch64` isn’t a superset of `armv7hl`/`armhfp`, so instead I used qemu emulation on `x86_64`. Anyway, with 32-bit ARM:

```
>>> _, _, rank, _ = lstsq(X, y, cond=None)
>>> assert rank == 5
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AssertionError
>>> from pprint import pprint
>>> pprint(dict(zip(['solution', 'residues', 'rank', 'singular_values'], lstsq(X, y, cond=None))))
{'rank': 6,
 'residues': 95.10457914827802,
 'singular_values': array([1.10268204e+01, 5.09901951e+00, 4.59234384e+00, 4.17805755e+00,
       3.72336464e+00, 3.73556391e-15]),
 'solution': array([ 3.68122071e+13, -3.68122071e+13, -3.68122071e+13, -3.68122071e+13,
       -3.68122071e+13, -3.68122071e+13])}
```

Compare to `aarch64`, 64-bit ARM:

```
>>> _, _, rank, _ = lstsq(X, y, cond=None)
>>> assert rank == 5
>>> from pprint import pprint
>>> pprint(dict(zip(['solution', 'residues', 'rank', 'singular_values'], lstsq(X, y, cond=None))))
{'rank': 5,
 'residues': array([], dtype=float64),
 'singular_values': array([1.10268204e+01, 5.09901951e+00, 4.59234384e+00, 4.17805755e+00,
       3.72336464e+00, 2.17341447e-15]),
 'solution': array([ 0.15142703, -0.23813759, -0.12416907,  0.2800976 ,  0.34713187,
       -0.11349579])}
```

**Comment by musicinmybrain** [comment]
For now I’m planning to skip the linear regression test on 32-bit ARM. Let me know if there is anything I can do to help deal with this more precisely.

**Comment by raphaelvallat** [comment]
Closing this issue, feel free to reopen!
