### ISSUE TITLE
Implementation of McNemar-Bowker test

### ISSUE THREAD

**Issue by adam2392** [raphaelvallat/pingouin#203]
The current implementation for McNemar's test assumes a 2x2 contingency table. Is it possible and feasible to add an implementation of McNemar-Bowker test for multiple categories?

**Comment by raphaelvallat** [comment]
Closing this, but feel free to reopen

**Comment by jeanbaptisteb** [comment]
This is implemented in base R, with the the [stats:::mcnemar.test()](https://github.com/SurajGupta/r-source/blob/master/src/library/stats/R/mcnemar.test.R) function, e.g. if you pass a square table of dimensions larger than 2x2 to the `x` argument. 

Another implementation in Python is available here: https://peterstatistics.com/Packages/python-docs/tests/test_mcnemar_bowker.html

**Comment by jeanbaptisteb** [comment]
I was thinking about making a pull request for this, but I have no idea when I'll have the time to look at this for the moment. At least not before one month, if someone else feels they can have a look at it in the meantime.
