### ISSUE TITLE
Add Jarque-Bera method to normality test

### ISSUE THREAD

**Issue by iki77** [raphaelvallat/pingouin#216]
Currently, there is only 'shapiro' and 'normaltest' method for normality test. Adding Jarque Bera method should be helpful as an alternative for testing large samples.

**Comment by raphaelvallat** [comment]
Hi @iki77,

Thank you, I agree. This should be pretty straightforward using [scipy.stats.jarque_bera](https://docs.scipy.org/doc/scipy/reference/generated/scipy.stats.jarque_bera.html), e.g.

```python
pg.normality(..., method="jb")
```

**Comment by raphaelvallat** [comment]
Done in cd7168befd0870c61323a48a527c812afb948b45

See https://github.com/raphaelvallat/pingouin/pull/236
