### ISSUE TITLE
pairwise_ttests doesn't work as expected

### ISSUE THREAD

**Issue by rnesti** [raphaelvallat/pingouin#217]
Hi @raphaelvallat, 

I think that the implemented function `pairwise_ttests()` does not work as expected. <br/> 
While using the `Goggles.sav` dataset from Andy Field, I noticed that I get other `p-values` than `JAMOVI` or `SPSS` when comparing the factor levels of the between factor `alcohol`. 

Here are the results of `pingouin`:

![pingouin_output](https://user-images.githubusercontent.com/75303808/145880787-de5a0a6c-b0e8-4161-8cf3-696eab68bf5e.png)

compared to the results of `JAMOVI`:

![jamovi_output](https://user-images.githubusercontent.com/75303808/145880891-384e9e51-8d09-4cc2-aea8-bf7423c231ab.png)

I noticed that the degrees of freedom differ. `pingouin` gives `30`, which corresponds to the **sum of the group samples - 2**, while `JAMOVI` gives `42`, which corresponds to the **degrees of freedom of the residuals**. 

Perhaps it could be because `JAMOVI` and the other programs use the *estimated marginal means* for calculation. 

Furthermore, I noticed that when passing several `between` factors, the combination of the individual groups are not tested, but rather simple contrasts are calculated, in which one factor level of the first factor is fixed *(e.g. `Attractive`)* and the factor levels of the other factor are compared with each other *(e.g. `Placebo` vs. `Low dose`)*. 

<img width="895" alt="post_hoc_two_factor" src="https://user-images.githubusercontent.com/75303808/145884949-c9fdb886-ec21-4082-a55c-2b96c296c892.png">

 I created a combination of the factors in a new column and passed it as a `between` factor to achieve a similar result as the statistical software 'JASP'.

<img width="943" alt="post_hoc_factor_combined" src="https://user-images.githubusercontent.com/75303808/145884671-ac5272b9-58a6-4f2d-b67e-bb7a0f804bfc.png">

I hope that my explanations can be of some help. 

Thank you very much! 

Best regards!

**Comment by raphaelvallat** [comment]
Hi @rnesti,

Thank you for this detailed post.

Regarding the differences in degrees of freedom, could you please include here the following: 1) the Goggles dataset, in CSV format, 2) the Python code to reproduce the Pingouin output, and 3) JASP notebook.

Regarding the combination of individual groups, this is actually a deliberate choice that I made when I first implemented the `pg.pairwise_ttests` function. In my own analyses, I find Pingouin's approach often more useful than the combinatorial approach implemented in JASP. That said, would you be able to share the code that you used to create this new column? I think this will be useful to others.

Thank you,
Raphael

**Comment by raphaelvallat** [comment]
Closing this, but feel free to reopen!
