### ISSUE TITLE
welch_anova docs

### ISSUE THREAD

**Issue by arthurpaulino** [raphaelvallat/pingouin#22]
Both [Wikipedia][wiki] and [Real Statistics][real] mention that the Welch's test is useful when we have samples of different sizes, but [pingouin][pg]'s documentation does not. Wouldn't it be interesting to contemplate that piece of information?

[wiki]: https://en.wikipedia.org/wiki/Welch%27s_t-test
[real]: https://www.real-statistics.com/one-way-analysis-of-variance-anova/welchs-procedure/
[pg]: https://pingouin-stats.org/generated/pingouin.welch_anova.html

**Comment by raphaelvallat** [comment]
Indeed, good idea @arthurpaulino! I think we can just probably copy-paste the following sentence from Wikipedia: _"... and is more reliable when the two samples have unequal variances and/or unequal sample sizes."_.
Would you mind adding that in the chi2 pull request?

Thanks! Raphael

**Comment by arthurpaulino** [comment]
> Would you mind adding that in the chi2 pull request?

Will do :)

**Comment by arthurpaulino** [comment]
done https://github.com/raphaelvallat/pingouin/pull/21/commits/d83a5a29d13477ae8ba106c4bae57c59826e1205

also, some minor fixes.
