### ISSUE TITLE
Omega Reliability

### ISSUE THREAD

**Issue by rafaelvalero** [raphaelvallat/pingouin#221]
Thanks for the library.
I think this is one of the first to have something related to reliability in python. In contraposition with R which has many and in particular psych.
I was wondering if there are plans to incorporate [McDonald's Omega](https://personality-project.org/r/psych/HowTo/omega.tutorial/omega.html) function for reliability.

References: 

-  https://github.com/cran/psych/blob/master/R/omega.R 
- I have a simple version here: https://github.com/rafaelvalero/different_notebooks/blob/master/adding_omega.ipynb

**Comment by raphaelvallat** [comment]
Hi @rafaelvalero,

I do think it could be a nice addition to Pingouin. I won't have the time to implement it, but if you have a first working version please do feel free to submit a PR (following the guidelines [here](https://pingouin-stats.org/contributing.html)). We'll also need to add unit testing against the R function.

Thanks,
Raphael
