### ISSUE TITLE
pg.ttest() error explicitation for second set of observations (unclear UnboundLocalError)

### ISSUE THREAD

**Issue by AlineROC** [raphaelvallat/pingouin#222]
Hello,

When using pg.ttest with two set of observations, the error is not explicit when the second set of observations is not valid.

`pingouin.ttest(x = [] , y = [1, 2, 3] )` returns _AssertionError: x must have more than one element._
`pingouin.ttest(x = [1, 2, 3] , y = [] )` returns _UnboundLocalError: local variable 'dof' referenced before assignment_

The **UnboundLocalError** can be unclear for the user, maybe it would be suitable to use an **AssertionError** as well.

Thanks,

**Comment by raphaelvallat** [comment]
Thanks @AlineROC! Agreed — I'll fix this in the next release of Pingouin.

**Comment by raphaelvallat** [comment]
Done in 6a7401589d8882da1b3e557e7a8bf36764404b37
