### ISSUE TITLE
Bayes Factor for spearman correlation?

### ISSUE THREAD

**Issue by SebastianSpeer** [raphaelvallat/pingouin#223]
Dear Pingouin team,

Are you also working on an implementation for computing the Bayes Factor for Spearman correlation? 

If not, do you have any suggestions where to find some guidance to implement this in Python?

Best,

Sebastian

**Comment by raphaelvallat** [comment]
Hi @SebastianSpeer,

Thanks for opening the issue! I am not working on an implementation of the Spearman Bayes Factor. In fact, I am not aware of any method for calculating the BF of a Spearman correlation. To be honest, I would just use the [pg.bayesfactor_pearson](https://pingouin-stats.org/generated/pingouin.bayesfactor_pearson.html) function regardless of whether you used a Pearson or Spearman correlation.

Two R functions that may be of interest:
- https://www.rdocumentation.org/packages/BayesianFirstAid/versions/0.1/topics/bayes.cor.test
- https://easystats.github.io/correlation/reference/correlation.html

Best,
Raphael
