### ISSUE TITLE
Contingency: exact tests

### ISSUE THREAD

**Issue by arthurpaulino** [raphaelvallat/pingouin#23]
Tests currently planned to be supported:
* Fisher's exact test
* Barnard's test

**Comment by arthurpaulino** [comment]
Good source: http://www.nbi.dk/~petersen/Teaching/Stat2009/Barnard_ExactTest_TwoBinomials.pdf

**Comment by raphaelvallat** [comment]
@arthurpaulino Should we create a `chi2_exact(method='fisher')` function with `method in ['barnard', 'fisher']`? The default for 2x2 being `barnard` and `fisher` for other shapes of contingency tables.

**Comment by arthurpaulino** [comment]
@raphaelvallat Don't you mean the opposite though? If I recall correctly, Barnard's test is the one that allows other shapes rather than 2x2.

**Comment by raphaelvallat** [comment]
http://www.nbi.dk/~petersen/Teaching/Stat2009/Barnard_ExactTest_TwoBinomials.pdf

> The smaller, statistically significant, exact p-value produced by Barnard’s method is no accident. For 2 × 2 tables, Barnard’s test is more powerful than Fisher’s, as Barnard noted in his 1945 paper, much to Fisher’s chagrin. 

https://en.wikipedia.org/wiki/Barnard%27s_test

> In statistics, Barnard's test is an exact test used in the analysis of contingency tables. It examines the association of two categorical variables and is a more powerful alternative than Fisher's exact test for 2×2 contingency tables.

**Comment by arthurpaulino** [comment]
I see. But I thought that Fisher's test was incompatible with tables that weren't 2x2. I guess I was wrong:

> For hand calculations, the test is only feasible in the case of a 2 × 2 contingency table. However the principle of the test can be extended to the general case of an m × n table,[8][9] and some statistical packages provide a calculation (sometimes using a Monte Carlo method to obtain an approximation) for the more general case.[10] ([Wikipedia](https://en.wikipedia.org/wiki/Fisher%27s_exact_test))

**Comment by raphaelvallat** [comment]
Closing for now. Please feel free to re-open.
