### ISSUE TITLE
Program works well but can not exit automatically

### ISSUE THREAD

**Issue by JiayuMaoReal** [raphaelvallat/pingouin#230]
python verision=3.8.12
pingouin=0.5.0
pycharm ide
when I import pingouin and click run, the program cannot end automatically after finishing all the calculation (It occurs even only import pingouin and do noting). And when i click stop button, the exception information are like bellow:
____________________________________________________________________________________
^CException ignored in: <module 'threading' from 'ADDRESS-OF-MY-CONDA-ENVlib/python3.8/threading.py'>
Traceback (most recent call last):
  File "ADDRESS-OF-MY-CONDA-ENV/lib/python3.8/threading.py", line 1388, in _shutdown
    lock.acquire()
_____________________________________________________________________________________
It not affect the normal use of pingouin, but seems an abnormal issue.

**Comment by raphaelvallat** [comment]
Hi @JiayuMaoReal,

Do you only see this issue when importing Pingouin? I do not use PyCharm, and I have never see such an issue with VSCode, Jupyter Lab or the terminal. I am not sure it is related to Pingouin: a Google search of this error yields a [large number of results](https://www.google.com/search?q=Traceback+%28most+recent+call+last%29%3A+File+%2C+line+1388%2C+in+_shutdown+lock.acquire%28%29&rlz=1C5CHFA_enUS907US907&sxsrf=APq-WBvgvaYWuxwvUCTazJV1FKs7PNL0qQ%3A1643933411070&ei=4278Yf_RA5_NkPIPvemImAM&ved=0ahUKEwi_z4CY4eT1AhWfJkQIHb00AjMQ4dUDCA4&uact=5&oq=Traceback+%28most+recent+call+last%29%3A+File+%2C+line+1388%2C+in+_shutdown+lock.acquire%28%29&gs_lcp=Cgdnd3Mtd2l6EAM6BwgAEEcQsANKBAhBGABKBAhGGABQtgFYtgFggwNoAXACeACAAYgBiAGIAZIBAzAuMZgBAKABAcgBCMABAQ&sclient=gws-wiz). Could it be related to the data that you are using instead? Have you tried running the same code on a different computer?

Thanks,
Raphael

**Comment by JiayuMaoReal** [comment]
The problem magically disappear…after I do some other work, so I think that pingouin did not cause it.
