### ISSUE TITLE
error in single rater ICC calculation

### ISSUE THREAD

**Issue by xyan326** [raphaelvallat/pingouin#231]
Hi, I got some error by just implementing the ICC calculation in cases where each subject is only rated by 1 one rater. The unbalanced sample will not be calculated. Could you please help?

**Comment by raphaelvallat** [comment]
Please ask any analysis-related questions on the Gitter channel of Pingouin: https://gitter.im/pingouin-stats/Lobby. I am closing this issue. Thanks
