### ISSUE TITLE
Deprecate pingouin.circular module?

### ISSUE THREAD

**Issue by raphaelvallat** [raphaelvallat/pingouin#241]
The [pingouin.circular](https://pingouin-stats.org/api.html#circular) module is essentially a Python wrapper for the Matlab [circstats](https://github.com/circstat/circstat-matlab) toolbox. However, the latter now has an official Python version ([pycircstats](https://github.com/circstat/pycircstat)). I would therefore suggest that over the next year or so we progressively deprecate the circular module of Pingouin.

**Comment by hoechenberger** [comment]
pycircstats development seems to have stopped years ago unfortunate
