### ISSUE TITLE
Contingency: Cochran–Mantel–Haenszel test

### ISSUE THREAD

**Issue by arthurpaulino** [raphaelvallat/pingouin#25]
`pg.chi2_cmh` also requires a `stratify` parameter.

Sources to study:
* https://en.wikipedia.org/wiki/Cochran%E2%80%93Mantel%E2%80%93Haenszel_statistics
* http://www.biostathandbook.com/cmh.html
* http://rcompanion.org/rcompanion/b_10.html
* https://www.statisticshowto.datasciencecentral.com/cochran-mantel-haenszel-statistic-test/

**Comment by raphaelvallat** [comment]
Closing for now. Please feel free to re-open.
