### ISSUE TITLE
Problems with the combination Windows 11 - IPython - Jupyter

### ISSUE THREAD

**Issue by thomas-haslwanter** [raphaelvallat/pingouin#255]
When I put the line
`import pingouin as pg`
into a startup script in 
   ~\.ipython\profile_default\startup
and then call
`jupyter qtconsole` or `jupyter lab` in a terminal, IPython crashes (i.e. it hangs up during startup).
Surprisingly, if I do NOT put that line into the startup script, I can execute it manually after startup without any problems.
The problem did not show up in Windows 10.

Has anybody experienced similar problems?

Setup:

- Win 11 Education N, Build 22000
- Winpython 3.9.10
- pingouin 0.5.1

**Comment by raphaelvallat** [comment]
I work exclusively on Mac so I have never seen this issue 😕  Has anyone else experienced this problem?

**Comment by raphaelvallat** [comment]
Any updates on this @thomas-haslwanter? Otherwise, I'll close the issue.
