### ISSUE TITLE
Support for Bayesian Credible Intervals

### ISSUE THREAD

**Issue by filipmarkoski** [raphaelvallat/pingouin#262]
Hello, is there an implementation for Bayesian credible intervals as there is for frequentist confidence intervals?

https://en.wikipedia.org/wiki/Credible_interval

Helpful Literature:
1. https://jakevdp.github.io/blog/2014/06/12/frequentism-and-bayesianism-3-confidence-credibility/

**Comment by raphaelvallat** [comment]
Hi @filipmarkoski,

This is not implemented in Pingouin. I think it may be an useful addition and we could use the R library bayestestR as an inspiration (see [here](https://cran.r-project.org/web/packages/bayestestR/vignettes/credible_interval.html) and [here](https://easystats.github.io/bayestestR/reference/ci.html)). However, I think this will be a significant effort and I personally won't have the time to implement this anytime soon. If anyone wants to give it a try, please feel free to open a PR!

Thanks,
Raphael

**Comment by raphaelvallat** [comment]
Closing this, feel free to reopen
