### ISSUE TITLE
AssertionError using pg.rm_corr 

### ISSUE THREAD

**Issue by vitotitto** [raphaelvallat/pingouin#263]
Good evening guys, 

I am trying to calculate within-participant correlations  **pg.rm_corr**  in in **power.py**

but I get     AssertionError:  
```
886     if r is not None:
--> 887         assert -1 <= r <= 1
    888         if alternative == "two-sided":
    889             r = abs(r) 
``` 

I can't understand the relation what in the data causes this,  can you please help with this?

**Comment by raphaelvallat** [comment]
Hi @vitotitto,

Please make sure to use [GitHub Discussions](https://github.com/raphaelvallat/pingouin/discussions) for analysis-related questions in the future. To answer your question, I am guessing that you're getting an invalid `r` value (most likely a NaN), which leads to the AssertionError. I would thus check your data for the following:

1. Do you have multiple data points for each participant, even after removing the missing values?
2. Do you have many missing values? Do you still get the error if you remove the missing values and re-run the function?
3. Do you have at least some variance in your data (both within and between participants)
4. Do you have enough participants?

Finally, you can try running the repeated measures correlation using the [original R package](https://cran.r-project.org/web/packages/rmcorr/rmcorr.pdf).

Hope this helps,
Raphael

**Comment by raphaelvallat** [comment]
Closing this issue. Feel free to re-open.
