### ISSUE TITLE
An issue with pairwise_ttests

### ISSUE THREAD

**Issue by qniksefat** [raphaelvallat/pingouin#265]
Hey, I hope everything's good.

there was a problem when running pg.pairwise_ttests example, saying _TypeError: object of type 'int' has no len()_

the code I run 

```
import pingouin as pg

df1 = pg.read_dataset('mixed_anova.csv')
pg.pairwise_ttests(df1, dv='Scores', between='Group', subject='Subject')

```

Apparently, in _pingouin/parametric.py in ttest(x, y, paired, alternative, correction, r, confidence)_ in line 309, when I changed this
`stats = pd.DataFrame.from_records(stats, columns=col_order, index=['T-test'])`
to this
`stats = pd.DataFrame(stats, columns=col_order, index=['T-test'])`
the issue is solved.

I'm running python 3.8, pandas 1.3.5, and pg 0.5.0

**Comment by raphaelvallat** [comment]
Hi @qniksefat,

This issue has been fixed in Pingouin 0.5.1 (https://github.com/raphaelvallat/pingouin/pull/234). Updating Pingouin with `pip install -U pingouin` should fix the problem.

Thanks,
Raphael
