### ISSUE TITLE
python3.7 unable to install

### ISSUE THREAD

**Issue by mochazi** [raphaelvallat/pingouin#266]
[lazy_loader](https://pypi.org/project/lazy_loader/)
[pingouin](https://pypi.org/project/pingouin/)
![QQ图片20220515125037](https://user-images.githubusercontent.com/54659396/168457784-e41ef977-f96a-4f4a-86a3-9285718dd0c6.png)

`lazy_loader`>=3.8
Reason: `lazy_loader` not supported 3.7

**Comment by raphaelvallat** [comment]
See https://github.com/raphaelvallat/pingouin/discussions/240#discussioncomment-2676737

Run the following commands in a terminal:
`pip install -U pandas_flavor`
`pip install -U pingouin`

Thanks,
Raphael
