### ISSUE TITLE
when run with not root user ,will have the problem :  No module named pingouin

### ISSUE THREAD

**Issue by dyhyao6** [raphaelvallat/pingouin#267]
![微信截图_20220517181632](https://user-images.githubusercontent.com/49445844/168789721-a9d37487-bd01-45d6-91b4-928a20aa0a58.png)
![微信截图_20220517182504](https://user-images.githubusercontent.com/49445844/168790516-5ff9affc-8ab1-4b71-9e12-23dadf8d9d82.png)
 @ecederstrand @Leicas @isaacto @arthurpaulino

**Comment by dyhyao6** [comment]
![not_root](https://user-images.githubusercontent.com/49445844/168790880-9525b0de-8006-4276-a02d-01dfb342e4ab.png)

**Comment by sappelhoff** [comment]
did you install the package in an "isolated environment", as can be achieved with for example

- [conda](https://docs.conda.io/en/latest/miniconda.html)
- [venv](https://docs.python.org/3/tutorial/venv.html)

Doing that will make sure that you don't mix system and user installations.

**Comment by dyhyao6** [comment]
> did you install the package in an "isolated environment", as can be achieved with for example
> 
> * [conda](https://docs.conda.io/en/latest/miniconda.html)
> * [venv](https://docs.python.org/3/tutorial/venv.html)
> 
> Doing that will make sure that you don't mix system and user installations.

my steps ：
1、pip install pingouin
2、source /data/miniconda/envs/py379-tesla/bin/activate
3、python test.py

test.py：
from pingouin import bayesfactor_ttest
print(bayesfactor_ttest(3.5, 20, 20))

is there any wrong?

**Comment by raphaelvallat** [comment]
Is this issue specific to Pingouin? What if you try to install any other packages? Can you import pingouin in iPython?

**Comment by dyhyao6** [comment]
> Is this issue specific to Pingouin? What if you try to install any other packages? Can you import pingouin in iPython?

yes, I install other package like scipy , it can import in python:
![企业微信截图_20220518093342](https://user-images.githubusercontent.com/49445844/168939050-33404072-6d26-44f8-bcfb-f23dabc165a3.png)

**Comment by dyhyao6** [comment]
> Is this issue specific to Pingouin? What if you try to install any other packages? Can you import pingouin in iPython?

how to solve this issue?

**Comment by raphaelvallat** [comment]
SciPy might be already included in your dist though. Can you try installing another package, like `astropy` or `mne`? I don't think it's really related to a bug in Pingouin, but rather it has to do with the configuration of your environment. Have you tried creating a new env?

**Comment by dyhyao6** [comment]
> SciPy might be already included in your dist though. Can you try installing another package, like `astropy` or `mne`? I don't think it's really related to a bug in Pingouin, but rather it has to do with the configuration of your environment. Have you tried creating a new env?

I tryed install :
![微信截图_20220518103113](https://user-images.githubusercontent.com/49445844/168945118-bbbf97e2-188a-48e4-ac52-e271398a66b9.png)

it work , I think only root user can use pingouin.

**Comment by raphaelvallat** [comment]
Closing this, feel free to reopen if needed
