### ISSUE TITLE
pg.multicomp() uses a lot of memory, crashes the system

### ISSUE THREAD

**Issue by FlorinAndrei** [raphaelvallat/pingouin#270]
Python 3.9.9
Pingouin 0.5.1
Windows 10
Jupyter Notebook in Chrome
32 GB RAM

```
np.random.seed(seed=124)
T1 = 1000
T0 = 9 * T1
x = np.concatenate((np.random.normal(size=T0), np.random.normal(loc=3, size=T1)))
P = 1 - stats.norm.cdf(x)
D = sum(P < 0.05)

def explore(P, T0, T1):
    test = P > 0.05
    test0 = test[0:T0]
    test1 = test[T0 + 1 : T0 + T1]
    TN = sum(test0 == True)
    FD = sum(test0 == False)
    FN = sum(test1 == True)
    TD = sum(test1 == False)
    D = FD + TD
    print(f"For the {T0} true null hypotheses there were:") 
    print(f"- {TN} correct true nondiscoveries\n- {FD} false discoveries")
    print(f"The type I error rate is {FD}/{T0} or {FD/T0}.")
    print("")
    print(f"For the {T1} true alternative hypotheses there were:")
    print(f"- {TD} correct true discoveries\n- {FN} false nondiscoveries")
    print(f"The type II error rate is {FN}/{T1} or {FN/T1}.")
    print("")
    print(f"The false discovery rate is {FD}/{D} or {FD/D}.")

explore(P, T0, T1)

fwer2_reject, fwer2_pvals = pg.multicomp(P, method='holm')
explore(fwer2_pvals, T0, T1)

fdr1_reject, fdr1_pvals = pg.multicomp(P, method='fdr_bh')
explore(fdr1_pvals, T0, T1)
```

As I increase T1, `pg.multicomp()` uses more and more memory. The highest value I can run on my 32GB RAM system is around `T1=5000`.

**Comment by raphaelvallat** [comment]
Hi @FlorinAndrei,

Thanks for catching this. A reproducible example:

```python
import time
import numpy as np
import pingouin as pg
import matplotlib.pyplot as plt
import seaborn as sns
sns.set(font_scale=1.25)
out = {"method": [], "n": [], "time": []}

for method in ["bonf", "holm", "sidak", "fdr_bh", "fdr_by"]:
    for n in [10, 100, 500, 1000, 2000, 5000, 10000, 20000, 30000]:
        np.random.seed(42)
        t = time.time()
        pg.multicomp(np.random.random(n), method=method)
        elapsed = time.time() - t
        
        out["method"].append(method)
        out["n"].append(n)
        out["time"].append(elapsed)
        
out = pd.DataFrame(out)

# Plot
sns.lineplot(
    data=out, x="n", y="time", hue="method", palette="colorblind", 
    alpha=0.8, ci=None, lw=3)
```

![image](https://user-images.githubusercontent.com/25703792/173389438-1885de81-56ee-4fe3-be53-a1be695be022.png)

In other words, computation time scales exponentially with number of p-values for `holm`, `fdr_bh` and `fdr_by`. The function becomes very slow when the number of p-values exceed ~20,000.  By contrast, it stays roughly the same for `bonf` and `sidak`. These benchmarks were performed on a MacBook Pro 2019.

I think that there are improvements that can be made to speed up the FDR and Holm correction. I'll try to work on this for the next release. As a reference, here is the code of the [p.adjust](https://github.com/SurajGupta/r-source/blob/master/src/library/stats/R/p.adjust.R) R function.

**Tasks**

- [ ] Improve performance of Holm and FDR correction. The current code can be found [here](https://github.com/raphaelvallat/pingouin/blob/master/pingouin/multicomp.py)
- [ ] Allow pandas.Series here: https://github.com/raphaelvallat/pingouin/blob/8825a215f50a21fdaa53aa63fc25a1af44aee7bc/pingouin/multicomp.py#L473

Thanks,
Raphael

**Comment by raphaelvallat** [comment]
See improvements in https://github.com/raphaelvallat/pingouin/pull/271
