### ISSUE TITLE
Cannot import name 'studentized_range' from 'scipy.stats'

### ISSUE THREAD

**Issue by ph-code-repo** [raphaelvallat/pingouin#275]
When trying to import Pengouin (0.5.1) into my notebook, I get the error message:
`cannot import name 'studentized_range' from 'scipy.stats'`
My version of scipy is 1.8.1
I noticed that someone else had a similar problem a few months ago, but their only suggestion was to update versions, which hasn't worked: https://stackoverflow.com/questions/71886116/how-to-fix-python-error-code-cannot-import-name-studentized-range-from-sci

**Comment by raphaelvallat** [comment]
@ph-code-repo can you run the following lines:

```python
import scipy
scipy.__version__
```

One possible explanation is that you have two Python environments and are using the one with the outdated version of SciPy.

Thanks
Raphael

**Comment by raphaelvallat** [comment]
Closing this, feel free to reopen
