### ISSUE TITLE
pg.qqplot() should obey general pyplot parameters

### ISSUE THREAD

**Issue by FlorinAndrei** [raphaelvallat/pingouin#284]
I have a preamble which I add to a lot of notebooks. For some reason, each of the three blocks needs to be loaded into a separate Jupyter Notebook cell in order to be fully effective - no idea why. Anyway, the part that matters is the line that contains `figsize`.

```
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import statsmodels.api as sm
import statsmodels.stats.api as sms
from scipy import stats
import pingouin as pg

fig, ax = plt.subplots()
plt.clf();

sns.set_style('whitegrid')
plt.rcParams["figure.figsize"] = (16, 9)
plt.rcParams['figure.titlesize'] = 'xx-large'
plt.rcParams['figure.titleweight'] = 'bold'
plt.rcParams['legend.title_fontsize'] = 'x-large'
plt.rcParams['legend.fontsize'] = 'x-large'
plt.rcParams['axes.titlesize'] = 'x-large'
plt.rcParams['axes.titleweight'] = 'bold'
plt.rcParams['axes.labelsize'] = 'x-large'
plt.rcParams['xtick.labelsize'] = 'x-large'
plt.rcParams['ytick.labelsize'] = 'x-large'
sns_pal = sns.color_palette()
```

One of the effects is that `figsize` is set for most functions for the rest of the notebook. Seaborn tends to obey it. Matplotlib definitely uses it. However, `pg.qqplot()` still needs an explicit `figsize` parameter.

Would be nice if `pg.qqplot()` used the general pyplot context that most other functions use. Thanks!

**Comment by raphaelvallat** [comment]
@FlorinAndrei what if you use:

```python
pg.qqplot(..., figsize=None)
```

Currently, the default figsize in qqplot is (5, 4) inches, but setting figsize to None should revert to your global plt.rcParams

https://github.com/raphaelvallat/pingouin/blob/b1c334d93f8f7f8b13c39199c08a7d8b619afd95/pingouin/plotting.py#L229

**Comment by raphaelvallat** [comment]
Pingouin calls seaborn, so maybe it changes some default parameters. 

https://github.com/raphaelvallat/pingouin/blob/b1c334d93f8f7f8b13c39199c08a7d8b619afd95/pingouin/plotting.py#L9-L12

Anyway, I don't think this is really an issue so I'm closing this for now. Feel free to reopen. Thanks
