### ISSUE TITLE
plot_paired not working - palette issue (from sns.lineplot?) 

### ISSUE THREAD

**Issue by R1-Globulo** [raphaelvallat/pingouin#293]
Hello - 

I used pingouin to illustate a paired t-test a few months back - and rerunning the exact same code today now leads to an error when I plot the **plot_paired** graphs - error message is: 

ValueError: The palette dictionary is missing keys: {**list of numbers**
![pg plot_paired error](https://user-images.githubusercontent.com/73608484/180436440-381c612a-b64d-48d0-8d00-cb894717735f.PNG)
}

**Comment by raphaelvallat** [comment]
Can you please copy-paste your code here? Have you updated seaborn, matplotlib or Pingouin recently?

**Comment by R1-Globulo** [comment]
Hi there - thanks for the reply - all fixed now actually. 
It looks like it was due to a variable type, which caused the issue! 
Screenshots provided - with the final graph!

Really cool package btw - thanks for the good work and sharing with the rest of us! 

![image](https://user-images.githubusercontent.com/73608484/180778043-8f5c52c7-114a-4080-8757-4989394c85f0.png)

and the solution by changing the Z variable type

![image](https://user-images.githubusercontent.com/73608484/180778321-482080dd-601b-466f-8113-a1c527719665.png)

**Comment by raphaelvallat** [comment]
Awesome, thanks! Closing the issue.
