### ISSUE TITLE
holm correction in pairwise_ttests does not correct using rank

### ISSUE THREAD

**Issue by PibeChorro** [raphaelvallat/pingouin#294]
Hello,
first off - thank you for your brilliant package

When I use pairwise_ttests with the holm p-value correction it seems like the p-value is not corrected based on its rank, but just by its position in the dataframe.

Best
Vincent

**Comment by raphaelvallat** [comment]
Hi @PibeChorro,

Can you please provide an example code + a screenshot of the output of Pingouin? Even better if you can also print the expected p-values from another statistical software (R, JAMOVI, Matlab etc).

Thanks!
Raphael

**Comment by PibeChorro** [comment]
Hey Raphael,
sure

I am performing pairwise t-tests for mean activation in a brain area (roi). I have a 2(before and after intervention)*3(stimuli types) within subject design.
```
post_hoc_test = pg.pairwise_ttests(data=average_df,
                                           dv=roi,
                                           within=['pre_post', 'Effect'],
                                           subject='subject',
                                           parametric=normality_given,
                                           effsize='cohen',
                                           padjust='holm')
```

here is the output (I rounded to the third digit):

```
          Contrast pre_post       A       B  Paired  Parametric      T     dof alternative  p-unc  p-corr p-adjust    BF10  cohen  
0           pre_post        -    post     pre    True        True  1.823   23.0   two-sided  0.081     NaN      NaN   0.892  0.431
1             Effect        -  Appear  Change    True        True  0.337   23.0   two-sided  0.739   0.739     holm   0.226  0.069 
2             Effect        -  Appear  Vanish    True        True  -2.169  23.0   two-sided  0.041   0.081     holm   1.533 -0.504 
3             Effect        -  Change  Vanish    True        True -3.032   23.0   two-sided  0.006   0.018     holm   7.536 -0.631  
4  pre_post * Effect     post  Appear  Change    True        True -0.144   23.0   two-sided  0.886   1.000     holm   0.217 -0.034  
5  pre_post * Effect     post  Appear  Vanish    True        True -0.707   23.0   two-sided  0.486   1.000     holm   0.269 -0.155  
6  pre_post * Effect     post  Change  Vanish    True        True -0.756   23.0   two-sided  0.457   1.000     holm   0.278 -0.141  
7  pre_post * Effect      pre  Appear  Change    True        True  0.950   23.0   two-sided  0.352   1.000     holm   0.322  0.168  
8  pre_post * Effect      pre  Appear  Vanish    True        True -3.436   23.0   two-sided  0.002   0.011     holm  17.278 -0.767  
9  pre_post * Effect      pre  Change  Vanish    True        True -3.574   23.0   two-sided  0.002   0.010     holm  23.138 -0.887  

```

I haven't used R and MATLAB in a long time to do statistics so wouldn't know how to do it.
However, I would have expected the corrected p-value to be calculated like this:

```
p_corr = data['p-unc']*data['p-unc'].rank(ascending=False)
p_corr[p_corr>1]=1
```

Which would yield this:
```
0    0.486
1    1.000
2    0.287
3    0.048
4    0.886
5    1.000
6    1.000
7    1.000
8    0.019
9    0.019
```

I think I understand that you do a correction for each effect (the two main effects and the interaction) separately. But that still should give other corrected p-values for the interaction 

```
inter_ps = data['p-unc'][data['Contrast']=='pre_post * Effect']
inter_corr = inter_ps*inter_ps.rank(ascending=False)
inter_corr[inter_corr>1]=1
inter_corr

4    0.886
5    0.972
6    1.000
7    1.000
8    0.011
9    0.011
```

Hope that is helpful and that I did not misunderstand the correction procedure.

Best
Vincent

**Comment by raphaelvallat** [comment]
Hi Vincent,

That is not how the multiple comparison correction is calculated. Pingouin uses the [Holm-Bonferroni correction](https://en.wikipedia.org/wiki/Holm%E2%80%93Bonferroni_method), which is implemented in the [pingouin.multicomp](https://pingouin-stats.org/generated/pingouin.multicomp.html) function:

https://github.com/raphaelvallat/pingouin/blob/dce908b8a23ff39309d0d30c28daf3c1e4c47d9a/pingouin/multicomp.py#L265-L274

Thanks,
Raphael

**Comment by PibeChorro** [comment]
Hi Raphael,
yes now I get it. Thanks for pointing it out and I apologize for the inconvenience 

Best
Vincent
