### ISSUE TITLE
Bug post-hoc : pairwise_tests()

### ISSUE THREAD

**Issue by ValentinGhibaudo** [raphaelvallat/pingouin#295]
Hi,

First, thank you a lot for this amazing toolbox ! 

There might be a bug with the computing of the p-value uncorrected from pairwise_tests() function, in condition of a within design with parametric = False.

Below some boxplots of simulated data being truely different but p-unc of wilcoxon post-hocs returning non-significant with a questionable constant result of 0.25.

![simu_data_pg](https://user-images.githubusercontent.com/89797925/182596610-e7a00191-685f-4b3a-9028-48998200a8cc.png)

![simu_post_hoc](https://user-images.githubusercontent.com/89797925/182597672-ec6a63c9-5f52-495d-a537-2ed46f1e40b9.png)

This could be related to the update 0.5.2 of june 2022 :
"The pingouin.pairwise_ttests() has been renamed to [pingouin.pairwise_tests()](https://pingouin-stats.org/generated/pingouin.pairwise_tests.html#pingouin.pairwise_tests). Non-parametric tests are also supported in this function with the parametric=False argument, and thus the name “ttests” was misleading"

Others settings seem to work well (parametric = True or between design)

Or may I be doing something wrong ? 

Thanks !

PS : 
How I simulated data : 

```
concat = []
means = {'cond1':50, 'cond2':100, 'cond3':150, 'cond4':200}
for sujet in ['P1','P2','P3']:
    for cond in ['cond1','cond2','cond3','cond4']:
        df_concat = pd.DataFrame(data=np.random.randn(100)*5 + means[cond], columns = ['values'])
        df_concat.insert(0, 'cond', cond)
        df_concat.insert(0 , 'sujet', sujet)
        concat.append(df_concat)
df_simu = pd.concat(concat)

pg_post_hoc = pg.pairwise_tests(data=df_simu, dv = 'values', within = 'cond', subject = 'sujet', parametric = False)
```

**Comment by raphaelvallat** [comment]
Hi @ValentinGhibaudo,

Thanks for opening the issue. I think there is something wrong with the data that you have simulated. You have: 3 participants (not enough), 4 conditions (ok) and 100 repeated values for each participant and condition (which will be aggregated using the mean). `sujet` should be a `np.arange(0, 100)` to get **one unique value per each of the 4 conditions per each of the 100 participants**.

Hope this is helpful,
Thanks

Raphael

**Comment by ValentinGhibaudo** [comment]
Thank your for answering so quickly ! 
Yes indeed ! 
Sorry for this bad issue. 
I could find this on google easily but in your opinion what should be the minimal number of participants ?

**Comment by raphaelvallat** [comment]
I would say n=15-20 participants for reliable results. If you have less than that, I would probably just use a parametric T-test.
