### ISSUE TITLE
Wish list: power analysis

### ISSUE THREAD

**Issue by ajdneuro12** [raphaelvallat/pingouin#3]
Hi Raphael,

I was thinking a great addition to the toolbox would be some python based tools for power analysis such as something similar to R's 'pwr'. https://cran.r-project.org/web/packages/pwr/pwr.pdf. Thanks again for your great work on this tool!

Best,
Alex

**Comment by raphaelvallat** [comment]
Hi @ajdneuro12 !

Thank you for the suggestion. So far I have only implemented two power-related functions, namely `ttest_power` and `anova_power` (see [here](https://raphaelvallat.github.io/pingouin/build/html/api.html#id4)). I definitely agree that it would be great to have a more exhaustive approach, with the possibility to compute and plot the sample size and/or power (e.g. similar to the [GPower](http://www.gpower.hhu.de/) software).

I am gonna be traveling a lot in December and therefore will not have much time to work on Pingouin, but if you feel that you can help please do not hesitate to append new functions to the `power.py` file!

Thanks again for your positive feedback and suggestions, I really appreciate!
Raphael
