### ISSUE TITLE
pingouin.wilcoxon doesn't pass 'method' optional keyword argument to scipy.stats.wilcoxon

### ISSUE THREAD

**Issue by DavidALloyd** [raphaelvallat/pingouin#301]
pingouin.wilcoxon receiving p-value calculation method warning "UserWarning: Exact p-value calculation does not work if there are ties. Switching to normal approximation.". This is automatically fixed but the warning remains. scipy.stats.wilcox accepts an optional 'method' kwarg to change the method automatically, but this results in an unknown kwarg error in pingouin.wilcoxon. Other kwargs like 'zero_method' pass with no issue.

Reproducible code:
Example 1: no kwargs
```
import numpy as np
import pingouin as pg

x = np.array([20, 22, 19, 20, 22, 18, 24, 20, 19, 24, 26, 13])
y = np.array([38, 37, 33, 29, 14, 12, 20, 22, 17, 25, 26, 16])

wilcox_nokwargs = pg.wilcoxon(x, y)
```
Output: `UserWarning: Exact p-value calculation does not work if there are ties. Switching to normal approximation.`

Example 2: 'method' kwarg
```
import numpy as np
import pingouin as pg

x = np.array([20, 22, 19, 20, 22, 18, 24, 20, 19, 24, 26, 13])
y = np.array([38, 37, 33, 29, 14, 12, 20, 22, 17, 25, 26, 16])

wilcox_method = pg.wilcoxon(x, y, method='auto')
```
Output: `TypeError: wilcoxon() got an unexpected keyword argument 'method'`

Example 3: other kwarg besides method

```
import numpy as np
import pingouin as pg

x = np.array([20, 22, 19, 20, 22, 18, 24, 20, 19, 24, 26, 13])
y = np.array([38, 37, 33, 29, 14, 12, 20, 22, 17, 25, 26, 16])

wilcox_zero_method = pg.wilcoxon(x, y, zero_method='zsplit')
```
Output: `UserWarning: Exact p-value calculation does not work if there are ties. Switching to normal approximation.`

**Comment by raphaelvallat** [comment]
Hi @DavidALloyd,

This is because the `method` argument of scipy.stats.wilcoxon was previously called `mode`. See the documentation for the latest version of SciPy ([1.9.1)](https://docs.scipy.org/doc/scipy/reference/generated/scipy.stats.wilcoxon.html) and version [1.8.1](https://docs.scipy.org/doc/scipy-1.8.1/reference/generated/scipy.stats.wilcoxon.html). Using `mode=` or updating scipy should fix the issue.

Thanks
Raphael
