### ISSUE TITLE
Support for passing most plotting functions to seaborn grids

### ISSUE THREAD

**Issue by remrama** [raphaelvallat/pingouin#306]
Hi @raphaelvallat , I'm wondering how tied you are to generating figures explicitly in most of pingouin's plotting functions (e.g., `plot_blandaltman`). Currently, most of these plotting functions generate a figure explicitly when the `ax` parameter is not provided, something like:
```python
if ax is None:
    fig, ax = plt.subplots(1, 1, figsize=figsize, dpi=dpi)
```

I think it might be better or more flexible to generate a figure with default size the way seaborn does:
```python
if ax is None:
    ax = plt.gca()
```

Seems trivial, but if it's set up this way, then the function can be used to "map" plots onto seaborn grids (e.g., [this demo](http://seaborn.pydata.org/examples/many_facets.html)). It would be great if pingouin's plotting functions could be applied to this popular seaborn feature. Other very minor changes would also need to happen, namely taking a `color` parameter (see [here](https://seaborn.pydata.org/generated/seaborn.FacetGrid.map.html#seaborn.FacetGrid.map:~:text=A%20plotting%20function%20that%20takes%20data%20and%20keyword%20arguments.%20It%20must%20plot%20to%20the%20currently%20active%20matplotlib%20Axes%20and%20take%20a%20color%20keyword%20argument.%20If%20faceting%20on%20the%20hue%20dimension%2C%20it%20must%20also%20take%20a%20label%20keyword%20argument.)).

Other reasons to favor this change:
- As far as I can tell, you don't lose anything except the ability to specify figure details. BUT that's where the `ax` parameter gets its use; if someone wants a figure a specific size, they open up the figure themselves (specifiying size, dpi, etc.) and then pass the ax in. Ultimately this has more complete flexibility and suggests the user build their own figure if they are concerned about aesthetic details.
- Currently, when `ax` is used, `figsize` (and and sometimes `dpi`) is ignored. This is slightly confusing so this avoids that as well.

This would of course _not_ apply to any figures that need to build their own, like anything using seaborn facetgrids. At a glance, I think this change could apply to the following functions:
- `plot_blandaltman`
- `plot_paired`
- `plot_circmean`
- `qqplot` (also dropping the automatic Title here would help compatibility with seaborn)

Note there is a 3rd option where you could have both. You could check if a figure already exists, and then if not build one with the arguments passed to the pingouin plotting function. I don't favor this much, but just mentioning it.

If you're into this I'd be happy to make the pull request.

**Comment by remrama** [comment]
Just now realizing something like this (from [FacetGrid docs](https://seaborn.pydata.org/generated/seaborn.FacetGrid.html#seaborn.FacetGrid)) could probably be reworked as a clunky work-around to my specific concern:

```python
import matplotlib.pyplot as plt
def annotate(data, **kws):
    n = len(data)
    ax = plt.gca()
    ax.text(.1, .6, f"N = {n}", transform=ax.transAxes)

g = sns.FacetGrid(tips, col="time")
g.map_dataframe(sns.scatterplot, x="total_bill", y="tip")
g.map_dataframe(annotate)
```

Basically a wrapper for pingouin plotting functions could use `plt.gca()` and pass that as `ax` to pingouin.

Putting this here for completeness but I still think the more general solution is better with some additional side benefits.

**Comment by raphaelvallat** [comment]
Hi @remrama,

Thanks for the detailed issue. I don't see any reasons why not to implement your proposed solution, and I agree that it may improve flexibility and at the same time simplify Pingouin's API. Please feel free to work on a PR 👍

**Comment by remrama** [comment]
#314
