### ISSUE TITLE
anderson() boolean returned value is inverted

### ISSUE THREAD

**Issue by ALL-SPACE-Rob** [raphaelvallat/pingouin#308]
[scipy.stats.anderson()](https://docs.scipy.org/doc/scipy/reference/generated/scipy.stats.anderson.html) returns the statistic "A2", a list of critical values and a list of significance levels for those critical values (both lists distribution-dependent). As stated on [that webpage](https://docs.scipy.org/doc/scipy/reference/generated/scipy.stats.anderson.html), 

"If the returned statistic is larger than these critical values then for the corresponding significance level, the null hypothesis that the data come from the chosen distribution can be rejected. The returned statistic is referred to as ‘A2’ in the references."
            
Basic hypothesis testing has the test as one of two ways:

1. the comparison of the statistic to a critical value for a given significance, as above, with the null hypothesis accepted if `calculated_value < critical_value` and rejected (alternative hypothesis accepted) if `calculated_value > critical_value`
2. the comparison of the calculated p-value of the calculated statistic to the given significance (p-value reference, often called alpha), with the null hypothesis accepted if `calculated_p_value > ref_p_value` and rejected (alternative hypothesis accepted) if `calculated_p_value < ref_p_value`
            
[pingouin.anderson()](https://pingouin-stats.org/generated/pingouin.anderson.html) returns a boolean and a float, with the latter the significance level, if any, and the boolean "True if data comes from [requested] distribution" (https://pingouin-stats.org/generated/pingouin.anderson.html). However, this is in error, as the code ([line 439](https://github.com/raphaelvallat/pingouin/blob/master/pingouin/distribution.py)) has `True if (st > cr).any() else False` with `st` the calculated statistic and `cr` the critical values returned by [scipy.stats.anderson()](https://docs.scipy.org/doc/scipy/reference/generated/scipy.stats.anderson.html). Given the standard understanding of hypothesis testing and the documentation for the underlying scipy function are in agreement, it is clear the pingouin implementation is in error. Line 439 should be corrected to read `True if (st < cr).any() else False` bringing it into accord with standard practice, the scipy.stats implementation and the existing pingouin documentation and expected behaviour.

**Comment by raphaelvallat** [comment]
Hi @ALL-SPACE-Rob,

Indeed, you are right. The `pingouin.anderson` is one of these old functions for which I have never implemented a robust unit testing pipeline — in fact, I have never used it for my own analyses. 

We do need to fix this asap. Please feel free to submit a PR with your proposed change. I'll also add more unit tests and documentation to this function.

For testing:

```python
>>> import numpy as np
>>> import pandas as pd
>>> pg.anderson(np.random.random(size=1000000))  # NOT normally-distributed
(True, 1.0)

>>> pg.anderson(np.random.normal(size=1000000))  # Normally-distributed
(False, 15.0)
```

Thanks,
Raphael

**Comment by ALL-SPACE-Rob** [comment]
No worries! Happy to do my little bit to help. I've only recently discovered `pingouin` and I'm finding it useful, so thanks for your efforts with it.

I see where you are coming from, in terms of value-add. My opinion, for what it is worth, is that there is some value in having the "answer" provided via the boolean, as it saves the user (me!) having to code that kind of check. When I want to check normality of residuals and homoscedasticity for ANOVA analyses, I typically want to know first whether these assumptions are broken, and second, the significance level/p-value if they are not broken (mostly for completeness, and to inform interpretation of results). Your homoscedasticity function is essentially a wrapper around `scipy.stats.levene()` and `scipy.stats.bartlett()`, giving a user a single function to do "what they want", with options to control how that is completed, and the boolean "answer". You have a function `normality()` that seems to work in a similar way with other functions. Maybe one option would be to merge `anderson()` with `normality()` as a special method (with `alpha` ignored and replaced with `dist`)?

**Comment by raphaelvallat** [comment]
Thanks @ALL-SPACE-Rob for your thoughtful answer. 

> Maybe one option would be to merge anderson() with normality() as a special method (with alpha ignored and replaced with dist)?

Yeah I thought about that too. One concern here is that we already have three different methods in pingouin.normality, and choice overload is not a good thing. To be honest, I do not know which of these 3 (or 4 if we include anderson!) is the most reliable and accurate method to check for normality. I know that Shapiro (the default) is not accurate for large sample sizes.

**Comment by ALL-SPACE-Rob** [comment]
I get where you are coming from with choice overload. I'm currently looking at replicating analysis other users are performing in Minitab, so I wasn't thinking too much about which is "best". However, [this paper seems to be a good examination of the issue](https://www.tandfonline.com/doi/full/10.1080/00949655.2010.520163) (open access full paper). It's conclusion is, for the tests examined:

- if the distribution is asymmetric (i.e. skewed) then the SW test is the best test followed closely by the AD test;
- if the distribution is symmetric with low kurtosis values (i.e. symmetric short-tailed distribution), then the D'Agostino and SW tests have good power;
- if the distribution is symmetric with high sample kurtosis (symmetric long-tailed), the researcher can use the JB, SW or AD tests.

Interestingly, the SW is "generally good" for all three types; AD for two. Your `normality()` function allows for three of these four. I'm not sure that any of them are universally the best, but it does seem that you have the right default. Merging `anderson()` might be unnecessary, given the coverage of the other three methods; on the other hand, merging `anderson()` could give you more choice for the asymmetric scenario...

I would still keep the function, though, if not merging it, as it is more "generic" in that you can use the test on other distributions (ok, only a small number in current implementations, but still!). Maybe an alternative would be a more generic `test_distribution()` function that has `anderson()` as a method, and other methods as appropriate?

As for the accuracy of SW for large sample sizes, I know it was originally only suited for  n < 50, but it was extended to n < 2000, and then to n < 5000, which seems to be the limitation (for p-value accuracy, at least) for `scipy.stats.shapiro()`. I would have thought that anyone needing to use the test for larger sample sizes should be able to check the validity of the test and work out its suitability (and any mitigation they need to do) - if there's no warning already generated, then adding it would be my solution.

**Comment by raphaelvallat** [comment]
Thank you for the detailed reply, appreciate it. Let's keep `pg.anderson` separate for now, and in the future we can maybe switch to a more generic `test_distribution` function as you suggest. 

Also, +1 for adding a warning when N>5000 for the SW test! Feel free to submit a quick PR.

Apologies for the delay with your PR, planning to work on it around Thanksgiving!
