### ISSUE TITLE
shift_plot

### ISSUE THREAD

**Issue by turkalpmd** [raphaelvallat/pingouin#318]
Thank you for suggesting that I open an issue on GitHub after my unsuccessful pull requests. You're right, my experience on GitHub is low, and using the issue topics might be a better way to address the problem. I originally edited the HTML in my previous pull request because I didn't know how to use Sphinx, but now I understand its logic better. Based on your suggestion, I edited the second figure in the shift plot documentation and added it to the helper section. However, I wasn't able to achieve the desired result in my fork. You can see the change I made in my fork, and if you think it's appropriate, I can create a pull request for it.

Here is my Kaggle notebook: [Shift plot example](https://www.kaggle.com/code/zzettrkalpakbal/shift-plot)

This figure need for doc
![I attached pingouin-plot_shift-2.png](https://user-images.githubusercontent.com/85236337/206109345-1942edf8-3bcc-49ab-9b09-7355c2c4febd.png)

Here is the my commit : [commit](https://github.com/turkalpmd/pingouin_plot_shift/commit/653bc8b982bac54998e54967c86303e9143cdca3)

**Comment by raphaelvallat** [comment]
Feel free to open a PR 👍 I'll make some minor edits once you've created it. Thanks!

**Comment by turkalpmd** [comment]
> Feel free to open a PR 👍 I'll make some minor edits once you've created it. Thanks!

Thank you for the feedback and for taking the time to review my pull request. You can check the status of the PR and see the results of the tests by visiting the pull request page on GitHub. If you have any further questions or concerns, please don't hesitate to let me know. Thank you again for your time and feedback.

[PR commit](https://github.com/raphaelvallat/pingouin/pull/320)
