### ISSUE TITLE
Normality test fails with misleading error message

### ISSUE THREAD

**Issue by GegznaV** [raphaelvallat/pingouin#319]
# Issue

Shapiro Wilk test fails for group sizes less than 2 with a misleading error message.

Consider this dataset with 8 samples:

```py
import pandas as pd
import pingouin as pg

data1 = [
    ["abc15", 55],
    ["abc18", 38],
    ["ark", 100],
    ["abc15", 56],
    ["ark", 101],
    ["ark", 100],
    ["abc19", 39],
    ["abc15", 56],
]
df = pd.DataFrame(data1, columns=["group", "variable"])
print(df.shape[0])
```
```
8
```
Then
```py
pg.normality(df, dv="variable", group="group")
```
returns this error, which is misleading:
```
AssertionError: Data must have more than 3 samples.
```

The error message is misleading, as there are 8 samples in the dataset (only some groups are smaller than 3).

# Expected output

1) *(desired solution)* No errors when some groups are too small, just no results in those cases, e.g., as in:
```py
from scipy.stats import shapiro

sw_rez = (
    df.groupby("group")['variable']
    .apply(
        lambda x: pd.Series(shapiro(x), index=["W", "p-value"])
        if len(x) > 2
        else pd.Series([np.nan, np.nan], index=["W", "p-value"])
    ).unstack().reset_index()
    
)

print(sw_rez)
```
```
   group     W       p-value
0  abc15  0.75 -9.106917e-07
1  abc18   NaN           NaN
2  abc19   NaN           NaN
3    ark  0.75 -9.106917e-07
```

**or**

2) *(only if it is impossible to implement 1)* Write a more informative error message, e.g., print the names of the groups that are really too small for the test.

**Comment by raphaelvallat** [comment]
Hi @GegznaV,

Thanks for opening the PR. I agree that the error message is confusing in this case and that solution 1 would be preferable. I would also add a generic warning that "Normality tests could not be measured for some groups with a sample size below 3. Returning NaN."

It should be pretty straightforward to modify these lines:

https://github.com/raphaelvallat/pingouin/blob/c97b0ef0bf77d984eb2cb1efc5f133d3b4e7ebde/pingouin/distribution.py#L236-L240

Feel free to open a PR!

**Comment by raphaelvallat** [comment]
Fixed in https://github.com/raphaelvallat/pingouin/pull/324

**Comment by GegznaV** [comment]
Thanks for looking into this.
