### ISSUE TITLE
Add Bonferroni correction as an argument for multiple comparison tests

### ISSUE THREAD

**Issue by turkalpmd** [raphaelvallat/pingouin#326]
I suggest adding the Bonferroni correction as an optional argument for multiple comparison tests in our project. This would give users the option to apply the correction to their tests if they wish, which could be particularly useful for controlling the risk of false positive errors when conducting multiple comparisons. What do you think about this suggestion?

**Comment by raphaelvallat** [comment]
Hi @turkalpmd,

Bonferroni correction is already supported in Pingouin via the `pg.multicomp(method="bonf")` function, which can be called from other functions, e.g. `pg.pairwise_tests(..., padjust="bonf")`

**Comment by turkalpmd** [comment]
Maybe benferroni also add chisqr and friedman . Thank you, im closing the issue. 👍🏼
