### ISSUE TITLE
Enhancing Data Analysis with a Bit of Machine Learning

### ISSUE THREAD

**Issue by turkalpmd** [raphaelvallat/pingouin#327]
1- I have developed a hyperparameter tuning feature for our logistic regression module. It is also including a recursive feature elimination (RFE) function and measures for accuracy and ROC-AUC score. I have also created a function to plot the results. If you are interested, I can share the code with you.

2- I developed some automated functions for numeric and categorical analysis, but first I focused on creating a logistic regression function.

**Comment by raphaelvallat** [comment]
Hi @turkalpmd,

Thanks for opening the issue, and please feel free to share your code here! However, I think it's better that Pingouin's functions stay very general and high-level. It seems that what you have developed would work only for very specific use cases.
