### ISSUE TITLE
Please share wheel file on pypi

### ISSUE THREAD

**Issue by MarcSkovMadsen** [raphaelvallat/pingouin#335]
Hi

I am a contributor to the [HoloViz](https://holoviz.org/) ecosystem and [Panel](https://panel.holoviz.org) in particular. Panel is a data app framework that can also run in the browser using Pyodide or Pyscript.

A user is asking for help getting an application using biopsykit and thus pingouin working in https://discourse.holoviz.org/t/pyodide-cant-find-a-pure-python-3-wheel-for-pingouin-0-6-0-0-5-2/4856.

The issue is that pingouin does not release wheel files on pypi. As far as I can see it should be possible to release.

Please consider doing so. Thanks.

[![image](https://user-images.githubusercontent.com/42288570/214777460-51b2d445-6df0-439b-a389-cae315cf36f6.png)](https://pypi.org/project/pingouin/0.5.3/#files)

**Comment by afrendeiro** [comment]
Hi, in Python 3.11 I'm having issues installing Pingouin as well due to the lack of wheel files - it would be greatly appreciated.

**Comment by raphaelvallat** [comment]
Hi @MarcSkovMadsen,

Thanks for opening the issue and apologies about the late reply. I have now uploaded the wheel files on pypi: https://pypi.org/project/pingouin/#files

Thanks
Raphael

**Comment by afrendeiro** [comment]
Thank you so much Raphael for making and maintaining this awesome package!
Best wishes, André
