### ISSUE TITLE
A column having all 1s in it cannot be a covariate for partial correlation.

### ISSUE THREAD

**Issue by juhng62** [raphaelvallat/pingouin#336]
I want to calculate partial correlation. So I tried pg.pairwise_corr(data=df, columns=["A", "B"], covar=["C", "D"], where df is something like:
A, B, C = x.xx, x.xx, x.xx ...
D = 1, 1, 1 ...
But then it produced an error: "Covariate(s) are either not in data or not numeric." and I figured out that it was because of D.

However, when I tried this with Matlab: rho = partialcorr(A, B, E), where E = [C D], it didn't produce any error.

How do I fix this problem?

Thank you in advance.

**Comment by remrama** [comment]
Sometimes pandas dataframe columns can _look_ numeric but not be. Like maybe the 1's are for some reason strings. You can check that D is numeric by looking at it's datatype: `df["D"].dtype`.

Or try rerunning like this:
```python
pg.pairwise_corr(data=df.astype(float), columns=["A", "B"], covar=["C", "D"])
```

**Comment by juhng62** [comment]
@remrama Thanks for your comment. Unfortunately though it still doesn't work.
```
import pandas as pd
import pingouin as pg
data = {'A' : [4.2, 2.4, 2.1, 1.2, 8.3, 6.4, 9.5, 8.6, 11.7, 13.8, 12.9, 14.5],
        'B' : [1.1, 2.3, 2.4, 4.1, 9.8, 8.2, 9.3, 6.4, 14.7, 12.2, 13.5, 12.6],
        'C' : [1.1, 2.5, 3.6, 4.7, 1.2, 2.8, 3.9, 4.3, 1.6, 2.7, 3.4, 4.5],
        'D' : [1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0]}        
df = pd.DataFrame(Data, columns = ['A', 'B', 'C', 'D'])
print(df['D'].dtype)
result = pg.pairwise_corr(data=df.astype(float), columns=['A', 'B'], covar=['C', 'D'])
print(result)
```

**Comment by remrama** [comment]
Thanks for the detailed output.

Upon deeper investigation, it looks like indeed pingouin explicitly removes any constant value columns. See [line 1312](https://github.com/raphaelvallat/pingouin/blob/6f4a7b483e4abb320148880bb507d96fb98f271d/pingouin/pairwise.py#L1312)-1313.

I'm not familiar with how partial correlations are supposed to deal with this. Correlations can't include constants ([quick explanation](https://stats.stackexchange.com/a/267155)), but I suppose if it was a covariate you could say it just has no impact. As for how matlab handles this case differently than pingouin under-the-hood, I'm not sure. I suspect it just does nothing with the constant (you should get same result whether D is included in matlab or not). If that's the case, I think you could just drop "D" from your pinguoin analysis. But again, this is not my area of expertise!

**Comment by juhng62** [comment]
@remrama Oh yes. Matlab indeed produces the same output whether D is included or not. Thank you remrama. I appreciate your response. It would be my fault to include a column with constants in the dataframe. I need to review why my data has constants and what it means. Thanks again.
