### ISSUE TITLE
AssertionError for bicor when n == 2

### ISSUE THREAD

**Issue by SabrinaRichter** [raphaelvallat/pingouin#340]
Hi,

I would like to use the bicor method within pairwise_corr. My data contains a lot of nan values that I would like to exclude with nan_policy='pairwise'. Unfortunately, there are also cases where the overlap of notnan values is only 2. In that case I would like to get nan for correlation (or anything else, I don't care too much...), but instead I am getting this AssertionError (that I am btw not getting when replacing the 4 with a 3...):
```
pingouin.corr([1, np.nan, 2, 4], [1, 2, np.nan, 3], method='bicor')
```
```
---------------------------------------------------------------------------
AssertionError                            Traceback (most recent call last)
Input In [55], in <cell line: 1>()
----> 1 pingouin.corr([1, np.nan, 2, 4], [1, 2, np.nan, 3], method='bicor')

File ~/miniconda3/envs/glue/lib/python3.8/site-packages/pingouin/correlation.py:648, in corr(x, y, alternative, method, **kwargs)
    644 else:
    645     ci = compute_esci(
    646         stat=r, nx=n_clean, ny=n_clean, eftype="r", decimals=6, alternative=alternative
    647     )
--> 648     pr = power_corr(r=r, n=n_clean, power=None, alpha=0.05, alternative=alternative)
    650 # Recompute p-value if tail is one-sided
    651 if alternative != "two-sided":

File ~/miniconda3/envs/glue/lib/python3.8/site-packages/pingouin/power.py:852, in power_corr(r, n, power, alpha, alternative)
    845 assert alternative in [
    846     "two-sided",
    847     "greater",
    848     "less",
    849 ], "Alternative must be one of 'two-sided' (default), 'greater' or 'less'."
    851 if r is not None:
--> 852     assert -1 <= r <= 1
    853     if alternative == "two-sided":
    854         r = abs(r)

AssertionError: 
```

**Comment by remrama** [comment]
I think this is happening in the edge case where rounding differences somewhere lead the `r` value to be slightly greater than 0. The assertion check that fails is checking to make sure `r` is between -1 and 1 (as any good r-value should be).

In the example you gave, running the biweight midcorrelation gives `1.0000000000000002` which then fails when later passed to `power_corr`. This is _not_ the case when changing that last number to 4, as you say.

I'm basing this on the code below, where the relevant lines of `pg.corr` are pulled out:
```python
import numpy as np
import pingouin as pg

x, y = pg.remove_na([1, np.nan, 2, 4], [1, 2, np.nan, 4], paired=True)
r, p = pg.correlation.bicor(x, y)
print(r)

x, y = pg.remove_na([1, np.nan, 2, 4], [1, 2, np.nan, 3], paired=True)
r, p = pg.correlation.bicor(x, y)
print(r)
```

I agree with you, in that even though this specific example isn't something one would really want to run anyways, it should pass the assertion even if just for the use-case you described. This would be an easy fix that could happen at different stages, but probably makes most sense to catch within the `pg.correlation.bicor` before returning the r value). Are you comfortable with submitting a PR for this? If not I could get to it at some point.

**Comment by raphaelvallat** [comment]
Hi,

Indeed, an easy fix is simply to add:

```python
r = np.clip(r, -1, 1)
```

somewhere in the `bicor` or `pg.corr` functions, before calling `power_corr`.

Thanks
Raphael
