### ISSUE TITLE
Crash when calculating power with too large effect size

### ISSUE THREAD

**Issue by agkphysics** [raphaelvallat/pingouin#343]
This crash occurs for me with the following code, although it may not work identically on all platforms:
```python
import numpy as np
from pingouin.effsize import compute_effsize
from pingouin.power import power_ttest

x = np.ones(10) * 0.3
y = np.ones(10) * 0.6
d = compute_effsize(x, y, paired=True)
print(d)
print(power_ttest(d, x.size))
```
Running this code results in the output
```
-3242591731706756.5
terminate called after throwing an instance of 'boost::wrapexcept<boost::math::rounding_error>'
  what():  Error in function boost::math::itrunc<double>(double): Value 2.3657402561699292e+31 can not be represented in the target integer type.
Aborted (core dumped)
```

The root cause of this is related to https://github.com/scipy/scipy/issues/17916. However, it occurs in `power_ttest()` due to calling `scipy.stats.nct.cdf()` with the huge value of `nc` based on `d`:
https://github.com/raphaelvallat/pingouin/blob/c66b6853cfcbe1d6d9702c87c09050594b4cacb4/pingouin/power.py#L146-L168

Perhaps a check should be done in `compute_effsize()` to check whether the variance to too small? Or check whether the effect size magnitude is too high in `power_ttest()`?

**Comment by agkphysics** [comment]
@raphaelvallat I've been thinking about the best way to solve/avoid this problem, but I see a few issues:
- If we return NaN simply because of a small denominator, this won't work if the scale of the data itself is smaller than the tolerance, which by default is 1e-8.
- An huge effect size is at least theoretically possible even if it doesn't happen in practice, so returning NaN seems the wrong thing to do.
- We could simply check the `nc` values being sent to `{nct,ncx2,ncf}.{sf,cdf}` where they would cause issues. However, this is really just a workaround for scipy crashing the interpreter instead of throwing a Python exception. Hopefully when https://github.com/scipy/scipy/issues/17916 is fixed it will simply raise an exception and so we only need a temporary fix.

What do you think?

**Comment by raphaelvallat** [comment]
Hi @agkphysics,

1. We could use a smaller tolerance value in np.isclose.
2.  I agree, but in this specific example the variance of both groups is zero, and therefore the denominator should be zero and not a very small value. (For reference see also: https://stats.stackexchange.com/questions/354391/cohens-d-calculation-when-within-group-variance-is-zero).
3. I think this is my least favorite option. What threshold would you use here to check the `nc` value?

Thanks,
Raphael

**Comment by agkphysics** [comment]
@raphaelvallat Based on the integer types used in the Boost algorithm: for `nct` we need `-2**16 < nc < 2**16`; for `ncx2` we need `nc < 2**32`; for `ncf` we need `nc < 2**32`.

`nc` is calculated not just from the effect size `d` but also the sample size `n`. So even if the sample variance is non-zero and above the `isclose` threshold, it can still fail:
```python
import numpy as np
import pingouin as pg

x = np.random.randn(1000) * 1e-3 + 5
y = np.random.randn(1000) * 2e-3 + 10

num = x.mean() - y.mean()
denom = np.sqrt((x.var(ddof=1) + y.var(ddof=1)) / 2)
print(denom)
d = num / denom if not np.isclose(denom, 0) else np.nan
print(d)

pg.ttest(x, y)
```
This bit of code yields:
```
0.0016064327488178193
-3112.5095382194936
terminate called after throwing an instance of 'boost::wrapexcept<boost::math::rounding_error>'
  what():  Error in function boost::math::itrunc<double>(double): Value 2421928906.3768315 can not be represented in the target integer type.
Aborted (core dumped)
```
I'm not sure there's an elegant solution, and all of this is because scipy/Boost crashes instead of throwing an exception. I'm still inclined towards checking values sent to the scipy methods because that is closest to the source of the problem and catches all issues.

That being said, it would still be good to check for deviations that are too small. Scipy does this for it's t-test: 
```python
with np.errstate(divide='ignore', invalid='ignore'):
    rel_diff = np.max(np.abs(a_zero_mean), axis=axis,
                      keepdims=True) / np.abs(mean)
with np.errstate(invalid='ignore'):
    precision_loss = np.any(rel_diff < eps)
```
So perhaps Pingouin could do something similar for calculating effect size.

**Comment by raphaelvallat** [comment]
> I'm still inclined towards checking values sent to the scipy methods because that is closest to the source of the problem and catches all issues.

Sounds good. Please feel free to submit a PR for this!
