### ISSUE TITLE
(Feature request) Implementations for pairwise partial correlation for compositional data

### ISSUE THREAD

**Issue by jolespin** [raphaelvallat/pingouin#346]
Trying to reproduce the methodology in the following publication:

https://www.sciencedirect.com/science/article/pii/S2590197420300082

In particular, implementing pairwise partial correlations for compositional data. This is pretty powerful for any biological data that comes from a DNA/RNA sequencing machine. 

Is there any pairwise implementation available with Pingouin?

**Comment by raphaelvallat** [comment]
Hi @jolespin,

I think this is too specific to be implemented in Pingouin (paper from 2020 with 20 citations). I see that you already have developed a Python package dedicated to compositional data (https://github.com/jolespin/compositional), why not implement it there? For reference, see also:

- http://scikit-bio.org/docs/latest/generated/skbio.stats.composition.html#module-skbio.stats.composition
- https://github.com/ntessore/composition_stats

Thanks,
Raphael

**Comment by jolespin** [comment]
Would the best way to implement pairwise partial correlation to just do a for loop between all pairs of features?  Or is there a more efficient way you would recommend?

**Comment by raphaelvallat** [comment]
Pairwise partial correlation is already implemented in Pingouin in the https://pingouin-stats.org/build/html/generated/pingouin.pairwise_corr.html#pingouin.pairwise_corr function, which is indeed basically a for loop between all pairs of features. See also the https://pingouin-stats.org/build/html/generated/pingouin.pcorr.html#pingouin.pcorr function

**Comment by raphaelvallat** [comment]
Closing this, but feel free to reopen if needed
