### ISSUE TITLE
New plot function: logistic regression estimate and 95%CI

### ISSUE THREAD

**Issue by turkalpmd** [raphaelvallat/pingouin#348]
I have created a display of coefficients for logistic regression, including a conversion of odds ratios. Can I generate a function to produce a plot of the results? Below is an example of the plot.

![newplot](https://user-images.githubusercontent.com/85236337/222825608-de7383b3-c188-4c11-82e4-b7a684a11784.png)

**Comment by raphaelvallat** [comment]
Hi @turkalpmd,

I am reluctant to add new plotting functions to Pingouin because they are very hard to maintain and debug. Can you please copy-paste the code that you used to generate this figure here? I think it might be useful to others.

Thanks
Raphael
