### ISSUE TITLE
Import of scikit-learn is stuck after import of pingouin

### ISSUE THREAD

**Issue by gcathelain** [raphaelvallat/pingouin#354]
When executing these two lines, 
```
import pingouin
import sklearn
```

the second line gets stuck indefinitely.

I had to downgrade pingouin to v0.3.1 to see this bug disappear...

I have these logs after killing the command :
   
> import sklearn
>   File "/usr/local/lib/python3.8/dist-packages/sklearn/__init__.py", line 82, in <module>
>     from .base import clone
>   File "/usr/local/lib/python3.8/dist-packages/sklearn/base.py", line 17, in <module>
>     from .utils import _IS_32BIT
>   File "/usr/local/lib/python3.8/dist-packages/sklearn/utils/__init__.py", line 21, in <module>
>     from . import _joblib
>   File "/usr/local/lib/python3.8/dist-packages/sklearn/utils/_joblib.py", line 7, in <module>
>     import joblib
>   File "/usr/local/lib/python3.8/dist-packages/joblib/__init__.py", line 113, in <module>
>     from .memory import Memory, MemorizedResult, register_store_backend
>   File "/usr/local/lib/python3.8/dist-packages/joblib/memory.py", line 32, in <module>
>     from ._store_backends import StoreBackendBase, FileSystemStoreBackend
>   File "/usr/local/lib/python3.8/dist-packages/joblib/_store_backends.py", line 15, in <module>
>     from .backports import concurrency_safe_rename
>   File "/usr/local/lib/python3.8/dist-packages/joblib/backports.py", line 22, in <module>
>     import distutils  # noqa
>   File "<frozen importlib._bootstrap>", line 991, in _find_and_load
>   File "<frozen importlib._bootstrap>", line 971, in _find_and_load_unlocked
>   File "<frozen importlib._bootstrap>", line 914, in _find_spec
>   File "/usr/local/lib/python3.8/dist-packages/_distutils_hack/__init__.py", line 97, in find_spec
>     return method()
>   File "/usr/local/lib/python3.8/dist-packages/_distutils_hack/__init__.py", line 108, in spec_for_distutils
>     mod = importlib.import_module('setuptools._distutils')
>   File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
>     return _bootstrap._gcd_import(name[level:], package, level)
>   File "/usr/local/lib/python3.8/dist-packages/setuptools/__init__.py", line 16, in <module>
>     import setuptools.version
>   File "/usr/local/lib/python3.8/dist-packages/setuptools/version.py", line 1, in <module>
>     import pkg_resources
>   File "<frozen importlib._bootstrap>", line 202, in _lock_unlock_module
>   File "<frozen importlib._bootstrap>", line 98, in acquire
> KeyboardInterrupt

You have any idea of a fix ?

**Comment by karanotsingyu** [comment]
I didn't met this problem:

**Comment by karanotsingyu** [comment]
I didn't met this problem:

```python
Python 3.8.11 (default, Jul 29 2021, 14:57:32)
[Clang 12.0.0 ] :: Anaconda, Inc. on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import pingouin as pg
>>> import sklearn
>>>
```

Python 3.8.11, MacOS 13 with M1 chip.

```
(base) ➜  ~ pip show pingouin
Name: pingouin
Version: 0.5.3
Summary: Pingouin: statistical package for Python
Home-page: https://pingouin-stats.org/index.html
Author: Raphael Vallat
Author-email: raphaelvallat9@gmail.com
License: GPL-3.0
Location: /Users/maiyunfei/miniconda3/lib/python3.8/site-packages
Requires: matplotlib, numpy, outdated, pandas, pandas-flavor, scikit-learn, scipy, seaborn, statsmodels, tabulate
Required-by:
(base) ➜  ~ pip show scikit-learn
Name: scikit-learn
Version: 1.1.1
Summary: A set of python modules for machine learning and data mining
Home-page: http://scikit-learn.org
Author:
Author-email:
License: new BSD
Location: /Users/maiyunfei/miniconda3/lib/python3.8/site-packages
Requires: joblib, numpy, scipy, threadpoolctl
Required-by: librosa, pingouin
```

**Comment by raphaelvallat** [comment]
Hi @gcathelain ,

I am also not able to reproduce the issue on an Intel-Macbook, Python 3.9, scikit-learn 1.1.3 and pingouin 0.5.3.

**Comment by gcathelain** [comment]
I have this issue on a tensorflow-2.8.4-gpu docker image, with WSL. Several people I'm working with have the same issue

**Comment by raphaelvallat** [comment]
1. What if you import `sklearn` first and then `pingouin`?
2. Do you only see this bug with pingouin, e.g. calling `scipy` and then `sklearn` works fine? Conversely, does calling `pingouin` and then another library (numpy, pandas, scipy) works fine?
3. What `sklearn` version are you using?
4. You said that you had to downgrade to 0.3.1, which is a fairly old version of Pingouin. Did you try downgrading to 0.5.2, 0.5.1, 0.4.0, etc?
5. Did you try up/downgrading your `sklearn` version?
6. It seems like the issue may be related to `joblib` or `setuptools`. Have you tried up/downgrading these packages as well?

I just don't see anything in the error message that leads to Pingouin, and since we're not able to replicate it is going to be very hard for us to debug.

Thanks
Raphael
