### ISSUE TITLE
bug in partial correlation when x ~ 10^9

### ISSUE THREAD

**Issue by dpellow** [raphaelvallat/pingouin#359]
When computing partial correlation with the x variable on the order of 10^9 I found that the result is unexpectedly extremely high or close to 1. This seems like a bug and replicates even when the x variable is a random number*10^9.

**Comment by raphaelvallat** [comment]
@dpellow I've investigated the bug in more details and I think it comes from the pseudo-inverse returning extremely small values:

https://github.com/raphaelvallat/pingouin/blob/5c5f61a09ee4e49ed81716fa9485527092fcc6b0/pingouin/correlation.py#L957

If I print `Vi`:

```python
import numpy as np
import pandas as pd
import pingouin as pg

np.random.seed(123)
df = pd.DataFrame(np.random.randn(100, 3), columns=list('ABC'))
df.pcorr()
```

<img width="504" alt="image" src="https://github.com/raphaelvallat/pingouin/assets/25703792/bfff87ff-e897-4afa-937c-80b5359619c9">

A few other observations:
- Interestingly, multiplying the entire `df` by `10**9` works as expected. I think it comes from the fact that the covariance matrix is ill-defined when one of the variable is so much larger than the other variables.
- I have tried changing the `rcond` in [np.linalg.pinv](https://numpy.org/doc/stable/reference/generated/numpy.linalg.pinv.html) and using [scipy.linag.pinvh](https://docs.scipy.org/doc/scipy/reference/generated/scipy.linalg.pinvh.html) but it doesn't help.

I'm not sure how to fix this. Thoughts?

**Comment by dpellow** [comment]
I'm not sure either. I discovered it because I was accidently correlating a feature that was an arbitrary 10 digit ID number with something actually meaningful. Usually I would take the log of features that are of that order of magnitude first.

**Comment by raphaelvallat** [comment]
Ok, well I think that this is a very rare occurrence, so closing this issue for now. Thanks for flagging this though.

**Comment by maayanorner** [comment]
I have had the same issue with my data, I found it can be solved by modifying rcond to rcond=1e-12, it seems like something underflows due to small singular values. I clearly don't know enough about the project to make a pull request for it (though the fix is trivial), but you might want to consider using it in some way to fix numerical instabilities.

`def pcorr(df):
    V = df.cov()  # Covariance matrix
    Vi = np.linalg.pinv(V, hermitian=True, rcond=1e-12)  # This is the fix, it is a tradeoff.
    D = np.diag(np.sqrt(1 / np.diag(Vi)))
    pcor = -1 * (D @ Vi @ D)  # Partial correlation matrix
    pcor[np.diag_indices_from(pcor)] = 1
    return pd.DataFrame(pcor, index=V.index, columns=V.columns)`

Cheers :)
