### ISSUE TITLE
question about effect size of ttest

### ISSUE THREAD

**Issue by shangll** [raphaelvallat/pingouin#361]
Hi, here is my code. The Cohen's d of paired ttest in pg is exactly the same as the Cohens d of independent t, but they shouldn't be, actually...
### Python ver.
```
import numpy as np
import pingouin as pg
arr1 = np.random.rand(30)
arr2 = np.random.rand(30)
arr1
arr2
t_val = pg.ttest(arr1,arr2,paired=True,alternative='two-sided',correction='auto')
pg.print_table(t_val)
```
### R ver.
(sorry I dont want to save .csv and dont know how to run them together, either... then just simply copy arr1&2 from pycharm)
```
library(tidyverse)
library(rstatix)

arr1 <- c(8.06848803e-01, 9.41218853e-01, 6.25649798e-01, 7.42518616e-01,
          9.79889534e-01, 8.44519575e-01, 7.34186267e-01, 2.38104767e-01,
          5.37203582e-01, 3.62354917e-04, 6.01246056e-01, 8.84546730e-01,
          9.22420993e-01, 4.74625503e-01, 9.56491229e-01, 8.96827152e-01,
          3.49802290e-01, 9.25680327e-02, 3.97904058e-01, 2.03759061e-02,
          1.10759461e-01, 3.42321779e-01, 2.99171249e-01, 9.38519888e-01,
          8.14681411e-01, 9.02615907e-01, 8.13290751e-01, 6.71935166e-01,
          7.84344014e-01, 5.12488155e-01)
arr2 <- c(0.41763186, 0.59465205, 0.81294349, 0.18845256, 0.95457772,
          0.42418905, 0.37336982, 0.88441999, 0.48147399, 0.18549061,
          0.10747044, 0.28272549, 0.29807464, 0.21666688, 0.37752749,
          0.52079059, 0.64694567, 0.40672402, 0.61236351, 0.27219483,
          0.05035356, 0.81949949, 0.40083164, 0.05034748, 0.07793052,
          0.98104925, 0.96401988, 0.85437085, 0.86374442, 0.87093899)
t_val <- t.test(arr1,arr2,paired=TRUE)
dat <- data.frame(data=c(arr1,arr2),cate=rep(c('a','b'),each=length(arr1)))
head(dat)
tail(dat)
d <- dat %>% cohens_d(data~cate,paired=TRUE)
d
d1 <- dat %>% cohens_d(data~cate)
d1
```

**Comment by raphaelvallat** [comment]
Hi,

Thanks for opening the issue. I am actually not familiar with the `rstatix` library, but most likely it's using a slightly different formula than Pingouin for paired Cohen d. As explained in the [doc](https://pingouin-stats.org/build/html/generated/pingouin.compute_effsize.html), Pingouin uses the Cohen d_average formula for paired samples:

https://github.com/raphaelvallat/pingouin/blob/7923141161564b7a065b75f44f5fc75a2c1a1aa2/pingouin/effsize.py#L797-L809

This is in accordance with two of the reference articles on the topic:

- Lakens, D., 2013. Calculating and reporting effect sizes to facilitate cumulative science: a practical primer for t-tests and ANOVAs. Front. Psychol. 4, 863. https://doi.org/10.3389/fpsyg.2013.00863
- Cumming, Geoff. Understanding the new statistics: Effect sizes, confidence intervals, and meta-analysis. Routledge, 2013.

If I understand the `rstatix` code correctly, the denominator is just the standard deviation of the differences, so it is expected that the two implementations return different results:

https://github.com/kassambara/rstatix/blob/360cda40bd22e80bce19ed63fbadfc4a9e52ce23/R/cohens_d.R#L253-L255

Thanks,
Raphael

**Comment by raphaelvallat** [comment]
@DwightCohen 

Please see this article: https://www.frontiersin.org/articles/10.3389/fpsyg.2013.00863/full

There are several ways to calculate the Cohen d for paired samples. The general recommendation however is to use the Cohen d _average_, which is what Pingouin uses, where the denominator is set as 

```python
np.sqrt((x.var(ddof=1) + y.var(ddof=1)) / 2)
```

You can see the source code of Pingouin here:

https://github.com/raphaelvallat/pingouin/blob/7923141161564b7a065b75f44f5fc75a2c1a1aa2/pingouin/effsize.py#L805-L809C41

Thanks,
Raphael
