### ISSUE TITLE
Multiple comparison One-way ANOVA in a dataframe with multiple columns

### ISSUE THREAD

**Issue by sjg2203** [raphaelvallat/pingouin#367]
Hi,
I have a data frame with 3 genotypes (X, A, B), each having 20 individuals, and 30 columns with their parameters (I melted them into a single column 'parameter', thinking it would make it easier). My data frame looks like this:
| Genotype | parameter | value |
|--------|--------|--------|
| X | W | 45 |
| X | R | 15 |
| A | W | 54 |
| A | R | 23 |
| B | W | 79 |
| B | R | 17 |
| ... | ... | ... |

I wish to perform statistical analyses between X-A, X-B and A-B for each parameter individually. Though, I am missing something here.
```python
res=pingouin.pairwise_tests(data=df,dv='value',within='parameter',subject='Genotype',alpha=.05,alternative='two-sided',return_desc=True,interaction=True,padjust='bonferroni')
```
In its final form, the `res` data frame should look like this one (only showing a shortened version, for illustration purposes)
| parameter | Genotype | pval | adj_pval |
|--------|--------|--------|--------|
| W | X-A | 0.04 | 0.03 |
| | X-B | 0.02 | 0.001 |
| | A-B | 0.02 | 0.01 |
| R | X-A | 0.1 | 0.7 |
| | X-B | 0.01 | 0.001 |
| | A-B | 0.06 | 0.04 |

If someone would have any idea on how this could be done, that would greatly help!
Thanks

**Comment by raphaelvallat** [comment]
Hi @sjg2203,

Currently there's no built-in way in Pingouin to deal with multiple dependent variables, however it can be done pretty easily with a for loop and some basic pandas operations, something like:

```python
stats = []
for dv in all_dvs:
    tt = pg.pairwise_tests(dv=dv, ...)
    tt["dv"] = dv
    stats.append(tt)
stats = pd.concat(stats).set_index(["dv"])
```
  
Thanks
Raphael

**Comment by sjg2203** [comment]
Hi @raphaelvallat,
I found that this line would return a dataframe with every comparison possible. It does the same as your example with the for loop
```python
stats=pg.pairwise_tests(data=df,dv='value',between=['parameter','Genotype'],
    alpha=0.05,alternative='two-sided',return_desc=True,interaction=True,padjust='bonf')
```
Thank you!

**Comment by raphaelvallat** [comment]
Even better then! Closing this issue :)
