### ISSUE TITLE
"Starting new HTTPS connection" when importing

### ISSUE THREAD

**Issue by buhtz** [raphaelvallat/pingouin#368]
I installed from PyPi (on Windows 10) and directly after `import pingouin` I got this output.

```
[DEBUG] Starting new HTTPS connection (1): pypi.python.org:443
[DEBUG] Starting new HTTPS connection (1): pypi.python.org:443
[DEBUG] https://pypi.python.org:443 "GET /pypi/pingouin/json HTTP/1.1" 301 122
[DEBUG] Starting new HTTPS connection (1): pypi.org:443
[DEBUG] https://pypi.python.org:443 "GET /pypi/outdated/json HTTP/1.1" 301 122
[DEBUG] Starting new HTTPS connection (1): pypi.org:443
[DEBUG] https://pypi.org:443 "GET /pypi/pingouin/json HTTP/1.1" 200 7381
[DEBUG] https://pypi.org:443 "GET /pypi/outdated/json HTTP/1.1" 200 3685
```

What happens here? Why are these connections?

**Comment by raphaelvallat** [comment]
I have never seen this before. Does it only happen with Pingouin? Can you try importing scikit-learn, pandas, etc? I don't think this is directly related to Pingouin, based on a similar post:

https://github.com/urllib3/urllib3/issues/1535

**Comment by buhtz** [comment]
I can not reproduce this anymore. Maybe because it has cached the content that was downloaded at the first time.
I'm pretty sure it is pingouin or an interaction of pingouin with one of my other packages (pandas, seaborn, ...) that where imported at this time.

**Comment by buhtz** [comment]
It happend again today but just once. Do you see the string `pingouin` in line 3 and 7?

```
[DEBUG] Starting new HTTPS connection (1): pypi.python.org:443
[DEBUG] https://pypi.python.org:443 "GET /pypi/outdated/json HTTP/1.1" 301 122
[DEBUG] https://pypi.python.org:443 "GET /pypi/pingouin/json HTTP/1.1" 301 122
[DEBUG] Starting new HTTPS connection (1): pypi.org:443
[DEBUG] Starting new HTTPS connection (1): pypi.org:443
[DEBUG] https://pypi.org:443 "GET /pypi/outdated/json HTTP/1.1" 200 3685
[DEBUG] https://pypi.org:443 "GET /pypi/pingouin/json HTTP/1.1" 200 7381
```

**Comment by raphaelvallat** [comment]
Oh I see. I think this is related to the `outdated` [package](https://github.com/alexmojaki/outdated), which Pingouin uses to check that the user is using the latest available version.

Could you try setting the environment variable `OUTDATED_IGNORE=1`?

Thanks

**Comment by buhtz** [comment]
Before I can test this I need to know how to trigger it. The behavior is not reproducible.

**Comment by buhtz** [comment]
Please re-tag that Issue. It is a bug and not a question.
Using that package "outdated" without informing the user is IMHO an inappropriate behavior.

**Comment by raphaelvallat** [comment]
I think we can safely remove the call/dependency to the `outdated` package. Please feel free to submit a PR. 

Thanks,
Raphael
