### ISSUE TITLE
output of normality is text not bool when testing fewer than 4 samples

### ISSUE THREAD

**Issue by dalensis** [raphaelvallat/pingouin#373]
Hi, thank you for the exceptional library you developed. 
The output of the normality function is not a bool when using less than 4 replicates per sample. the test return a warning and a NAN in the pvalue. It still write false in the the normal column, but now it's a string value and not a bool. 

Bests

**Comment by dalensis** [comment]
Here it is:

`from pingouin import normality
import seaborn as sns


data = sns.load_dataset("penguins")[:3]
#data = pd.read_table(data, engine="python", header=0, index_col=None, on_bad_lines='skip') 
print (data)

normal = normality(data, dv=data.columns[2], group=data.columns[1]) #test normality
print(normal)
       
if normal["normal"].all():
    print("ALL TRUE test bool")
else:
    print("at least 1 false test bool")

if  all(map(lambda ele: str(ele).lower().capitalize() == "True",normal["normal"])): #sometimes the result of normal is a str!
    print("ALL TRUE test string")        

else: 
    print("At least 1 false test string")`

**Comment by raphaelvallat** [comment]
Thank you. You are right that Pingouin incorrectly returns False as a string:

https://github.com/raphaelvallat/pingouin/blob/7923141161564b7a065b75f44f5fc75a2c1a1aa2/pingouin/distribution.py#L244

Actually, I think it might make more sense to return either np.nan or a [nullable boolean](https://pandas.pydata.org/docs/user_guide/boolean.html).

If you'd like, please feel free to submit a PR to fix this behavior. Thanks
