### ISSUE TITLE
Welch's ANOVA return values not match with document

### ISSUE THREAD

**Issue by tico88612** [raphaelvallat/pingouin#384]
In document, Welch's ANOVA function return this:
```
ANOVA summary:
- 'Source': Factor names
- 'SS': Sums of squares
- 'DF': Degrees of freedom
- 'MS': Mean squares
- 'F': F-values
- 'p-unc': uncorrected p-values
- 'np2': Partial eta-squared
```

but when I used this function, it gave me: `ddof1`, `ddof2`, `F`, `p-unc`, `np2`.
what are `ddof1`, `ddof2` means?

**Comment by raphaelvallat** [comment]
Thanks for opening the issue. `ddof1` refers to the numerator degrees of freedom, while `ddof2` is the denominator degrees of freedom (see [here](https://www.statisticshowto.com/probability-and-statistics/hypothesis-testing/degrees-of-freedom/#DFANOVA)).

I have now corrected the documentation in https://github.com/raphaelvallat/pingouin/commit/0af0e1715be32bd62109801d93e8b6eebafa137b

This will be updated on the Pingouin web documentation in the next release (date TBD).
