### ISSUE TITLE
CI column in results should not contain actual conf. level number

### ISSUE THREAD

**Issue by FlorinAndrei** [raphaelvallat/pingouin#386]
E.g. `ttest()` returns a dataframe where one column contains the confidence interval. Usually it's called `CI95%`, but if you specify a different confidence level, it will be called differently - like `CI90%`.

This gets a little tricky if you want to collect the results in code by column name. I think that column should simply be called `CI` and leave it at that.

I guess you could get the result by column index, but that's generally not a good idea (if columns are shuffled, or dataframes are joined, etc).

Perhaps other functions in this library do the same thing, in which case they should change as well.

**Comment by raphaelvallat** [comment]
I do like the fact that the CI level is explicit. I understand that it can be suboptimal in the situation that you describe, but in these cases it should be pretty straightforward to rename the pandas columns if you need to combine two dataframes with different CI levels.

Are other people in favor of removing the explicit conf levels in the column names?
