### ISSUE TITLE
non normal distribution error thrown when using ANCOVA

### ISSUE THREAD

**Issue by thebeancounter** [raphaelvallat/pingouin#395]
I am trying to use ANCOVA to find a relation between two variables eliminating one other variable. 
All of them are numeric. 
I am getting an error thrown saying the predicted variable is not normally distributed, 
no visible outliers, no NA values, and the same data works well with partial_corr. 

Where can I check what is the data caused that error?

**Comment by raphaelvallat** [comment]
Hi @thebeancounter,

Can you copy-paste the full error message and provide minimal code example to reproduce the error? There's no such error message in Pingouin, so the error might come from the lower-level statsmodels function.
