### ISSUE TITLE
conda package

### ISSUE THREAD

**Issue by hoechenberger** [raphaelvallat/pingouin#4]
Thanks for creating this amazing project! Only found out about it by accident :)

At any rate, I just created a `conda` recipe and [proposed it for inclusion](https://github.com/conda-forge/staged-recipes/pull/7320) in the `conda-forge` channel, so users would be able to install `pingouin` and all dependencies simply by doing `conda install -c conda-forge pingouin`

I wanted to ask you if you had any interest in
- [x] getting included as a recipe maintainer in the `conda-forge` recipe, and 
- [x] adding a `conda` badge as well as
- [x] amending the installation instructions

once the PR to `conda-forge` is accepted and the packages become available? (Meaning, I could do a PR for all of that.)

**Comment by raphaelvallat** [comment]
Hi @hoechenberger !
Thank you for your feedback,
YES to all three questions, that would be great to have a conda install. Thank you for doing this,
Please keep me updated on this,
Raphael

**Comment by hoechenberger** [comment]
The package is now available from `conda-forge`: https://anaconda.org/conda-forge/pingouin

**Comment by raphaelvallat** [comment]
Thank you @hoechenberger for this. I will add the conda badge and update the installation instructions as soon as I get back from holiday.

**Comment by raphaelvallat** [comment]
Hi @hoechenberger! Just added the conda badge and conda installation instructions to the develop branch. The changes will be included in the next release. I am closing this issue. Thanks again.

**Comment by hoechenberger** [comment]
Great, thank you!
