### ISSUE TITLE
plot_shift function differs from R

### ISSUE THREAD

**Issue by raphaelvallat** [raphaelvallat/pingouin#40]
See https://garstats.wordpress.com/2016/07/12/shift-function/ and https://garstats.wordpress.com/2016/07/29/matlab-shift-function/

@LegrandNico

**Comment by raphaelvallat** [comment]
Added warning in doc 857963642b4adc8a9f5f6af303e1292abcb22f61

**Comment by hoechenberger** [comment]
Cool,  I missed you've added shift function plots, awesome! I've been using my own implementation of this stuff, maybe we can exchange thoughts (and code) some time soon? :)

**Comment by raphaelvallat** [comment]
Hi @LegrandNico ! 

I just updated the plot_shift function to use the Harrel-Davis quantile estimator together with bias-corrected bootstrap confidence intervals. Is there any chance that you could have a look at the commits (da0f6a0dbae317e0a7585beeba66149b27a670a6 and f02d0de55c4cc10265e0ffc1f77197bc57c10e38) and make sure that everything seems right, perhaps testing on some of your own data? I rarely use this function so it'd make more sense that you validate it.

Thank you so much for your help!
Raphael

**Comment by LegrandNico** [comment]
This is a great addition to the shift function. Maybe in the future we could dissociate a `shift()` function (paired or not), outputting delta and delta_ci from 2 vectors of observations, and the `plot_shift` creating the figure. The `shift` function could then implement different approaches for percentiles and CI estimation (see many alternatives to the "classic" shift here https://garstats.wordpress.com/2019/02/21/hsf/), and the `plot_shift` could accept different graphical output like CDF as it was proposed in #62.

This would allow the percentiles estimates to be used in other contexts and will facilitate testing and comparison with other codes. What do you think?

I can work on it but maybe not for the next release, depending on when you want to do it.

**Comment by raphaelvallat** [comment]
Hi @LegrandNico ! It's a great idea -- let's do that! I think I might release the new version (0.3.0) of Pingouin with the current updated `plot_shift` function and we can split into 2 functions for the 0.3.1 release (around January).

**Comment by raphaelvallat** [comment]
Closing this issue for now but please feel free to reopen.
