### ISSUE TITLE
WEBSITE

### ISSUE THREAD

**Issue by bobo-jamson** [raphaelvallat/pingouin#400]
Hello, 
I am filing an issue with the website (www.pingouin-stats.org), it seems that most graphics and possibly CSS are broken, I suspect it's a path or permissions  issue, but I wanted to bring it to your attention.  The API documentation site does work though.

**Comment by raphaelvallat** [comment]
Hi,

Can you please share screenshots? The website is working well at least on my computer (and different browsers).

Thanks

**Comment by bobo-jamson** [comment]
Of course, here is what I am seeing, I checked on personal (macOS) and work computers (windows) and see the same thing. 

<img width="1271" alt="image" src="https://github.com/raphaelvallat/pingouin/assets/82302227/3c96b563-f880-4315-8e49-c66abafb6ea8">

**Comment by raphaelvallat** [comment]
I'm not able to reproduce this. Is anyone else experiencing the same issue?

**Comment by raphaelvallat** [comment]
Issue should now be fixed. Can you please confirm that's it's working on your side as well? Thanks

**Comment by FlorinAndrei** [comment]
It was broken for me as well, until today. It seems okay now. A few observations:

- it redirects to a longer URL https://pingouin-stats.org/build/html/index.html
- the Functions link at the top is sitting higher than the other links there in the menu

I'm using the latest Chrome on Ubuntu 22.04. I've Shift-reloaded the main page a couple times.

![Screenshot from 2024-01-31 10-52-25](https://github.com/raphaelvallat/pingouin/assets/901867/cd78480a-8c88-4467-a55a-19d31bef8add)

**Comment by raphaelvallat** [comment]
Thanks @FlorinAndrei for confirming ! 1) is expected, and for 2) I unfortunately have not found a solution to this.

**Comment by bobo-jamson** [comment]
Fixed as well for me :) 

Sorry being absent, work happened :)
