### ISSUE TITLE
Two new test failures fails in Fedora Rawhide

### ISSUE THREAD

**Issue by musicinmybrain** [raphaelvallat/pingouin#402]
Two tests (`TestRegression::test_linear_regression` and `TestMultivariate::test_box_m`) recently started failing in Fedora Rawhide. This link shows what dependency updates *could* be responsible: https://koschei.fedoraproject.org/build/17077907.

A failing build log is attached, [build.log](https://github.com/raphaelvallat/pingouin/files/14115002/build.log).

I’ve determined that the regression in `TestMultivariate::test_box_m` is associated with the update of openblas from 0.3.25 to 0.3.26. The test still passes when I set `export FLEXIBLAS=netlib` to run the tests.

Setting `export FLEXIBLAS=netlib` does *not* fix `TestRegression::test_linear_regression`; it still fails on all applicable architectures (`x86_64`, `ppc64le`, `aarch64`, and `s390x`).

It’s not immediately obvious to me what to do about either of these, and I know you don’t have a lot of time to work on pingouin right now. For now, I’m going to run the tests under netlib BLAS, and I’m going to skip `TestRegression::test_linear_regression`. I am very happy to do any testing that might help.

**Comment by musicinmybrain** [comment]
Oh! I realized we’re still on 0.5.3! I’ll check 0.5.4 and see if that fixes it or not.

**Comment by musicinmybrain** [comment]
> Oh! I realized we’re still on 0.5.3! I’ll check 0.5.4 and see if that fixes it or not.

No, the situation with 0.5.4 remains the same.

**Comment by raphaelvallat** [comment]
Thanks for reporting this! I'm not able to reproduce this error, and have not found an obvious cause by looking at the build log... If you could maybe try to manually re-run the failing unit test in a Jupyter notebook that might help us give a better understanding of the error?
