### ISSUE TITLE
chi2_independence p-values are possibly reversed

### ISSUE THREAD

**Issue by sam-tritto** [raphaelvallat/pingouin#405]
First off, I really love what you're doing with this library - wonderful stuff. I was in the process of putting together a short tutorial on the Chi-Squared test for Independence used for A/B testing purposes, and in the process of that I am comparing the implementations in scipy, statsmodels, and pingouin (version 0.5.4). I've generated some synthetic categorical data for 2 groups which have drastically different probabilities of categories. The results of the A/B should return low p-values since the groups are very different, and similarly I'd expect the results of an A/A test to return high p-values. Running the code below, you can see I'm getting the opposite results from pingouin, which contradict the other libraries. 

Here's a link to a notebook comparing the 3 libraries:
https://github.com/sam-tritto/Statistical-Tests/blob/main/Chi_Squared_Test.ipynb

```
# Number of samples for each version
n_samples = 1000

# Generate synthetic data for two website versions
version_A = np.random.choice(['Satisfied', 'Not Satisfied'], size=n_samples, p=[0.8, 0.2])
version_B = np.random.choice(['Satisfied', 'Not Satisfied'], size=n_samples, p=[0.1, 0.9])

# Create pandas dataframe
chi_squared_data = pd.DataFrame({'Version_A': version_A, 'Version_B': version_B})

# Similar categorical variables should present low chi-squared statistics and high p-values.

# A/A Test
# Perform chi-squared test for proportions using pingouin (bootstrap)
expected, observed, stats = chi2_independence(chi_squared_data, x='Version_A', y='Version_A', correction=True)
print("A/A Summary Stats:")
display(stats.round(3))
print(f"A/A Avg p-value: {stats['pval'].mean().round(3)}")

print('\n')

# A/B Test
# Perform chi-squared test for proportions using pingouin (bootstrap)
expected, observed, stats = chi2_independence(chi_squared_data, x='Version_A', y='Version_B', correction=True)
print("A/B Summary Stats:")
display(stats.round(3))
print(f"A/B Avg p-value: {stats['pval'].mean().round(3)}")
```

<img width="546" alt="Screenshot 2024-02-11 at 8 38 36 AM" src="https://github.com/raphaelvallat/pingouin/assets/59342606/36c785a1-4dc1-4ec4-905f-718ae341f9e9">

**Comment by sam-tritto** [comment]
Sorry, I think I understand why now. The power_divergence() function uses both the observed data and generated expected data from the expected_freq() function which assumes independence to create the expected data. Since I was attempting to use this function on a duplicate column, the contingency table has 0's in its corners since the data is identical. The expected data functions contingency table will not have values near 0, and thus the chi2_independence() function will correctly label the data as being different categorical data.  When I shuffle one column of duplicate data points the contingency table the values make sense.

**Comment by raphaelvallat** [comment]
Thanks @sam-tritto! Just seeing this now but glad to hear that you found the root cause.
