### ISSUE TITLE
Rename development branch

### ISSUE THREAD

**Issue by hoechenberger** [raphaelvallat/pingouin#409]
Hello, many (most?) projects have moved from the branch name `master` to something else; `main` seems to be particularly popular. For consistency with the rest of the ecosystem, it could make sense to rename the main development branch to `main` here, too.

(FYI we made the switch for all MNE-Python projects a while ago; the experience is rather smooth)

**Comment by raphaelvallat** [comment]
Agreed — should be pretty straightforward. I can implement later this week.
