### ISSUE TITLE
Mann-Whitney U (mwu): Order of `x` and `y` determines sign of rank-biserial correlation (RBC)

### ISSUE THREAD

**Issue by viggotw** [raphaelvallat/pingouin#417]
I was testing a hypothesis where I suspected the distribution of a user group to have higher values than the non-users. I tested this as follows
```python
mwu(
    x = group_user,
    y = group_non_user,
    alternative="greater"
)
```

I verified my calculations using Jamovi. Everything seemed correct, except the RBC had a negative sign. I then tried switching order of what I used as `x` and `y` inputs, and changing the `alternative` accordingly, as follows:
```python
mwu(
    x = group_non_user,
    y = group_user,
    alternative="less"
)
```

Now all my results correspond to Jamovi, including the RBC. However, I am a bit confused, as I could not find this requirement documented anywhere?

**Comment by raphaelvallat** [comment]
Hi @viggotw,

Thanks for opening the issue. Could you please provide a minimal code with simulated data to reproduce the valid and invalid outputs (including screenshots from Jamovi)? I think it might be related to the distinction between `U1` and `U2` explained in the documentation of the [scipy.stats.mannwhitneyu](https://docs.scipy.org/doc/scipy/reference/generated/scipy.stats.mannwhitneyu.html) function (of which Pingouin is a wrapper):

https://github.com/raphaelvallat/pingouin/blob/e74eaa3846951bd2013a627bbf3101a50812b00e/src/pingouin/nonparametric.py#L282-L295

**Comment by raphaelvallat** [comment]
Hey — apologies about the slow reply.

I did some further testing and you were right that the sign of RBC in `pg.mwu` was incorrect. This is fixed in https://github.com/raphaelvallat/pingouin/pull/424. I've also updated the documentation of the function to make it clear what the sign of RBC means. I'd appreciate if you could review the PR (it's a very short and easy one). Thank you!

**Comment by viggotw** [comment]
I've reviewed it, and it looks good now. I attempted to approve the PR, but it still says "Review required". I reckon you can sort this out. Anyway, thanks for fixing it! 😁
