### ISSUE TITLE
Effect sizes Cohens D and Hedges g with pingouin differ from R

### ISSUE THREAD

**Issue by sigbertklinke** [raphaelvallat/pingouin#431]
Hi,

I'am confused. Computing  Cohens D and Hedges g for a data set from R leads to very different results:

```
library("effsize")
survey <- MASS::survey
# Cohens d
cohen.d(survey$Height, survey$Sex, na.rm=TRUE)
cohen.d(survey$Wr.Hnd, survey$W.Hnd, na.rm=TRUE)
# Hedges g
cohen.d(survey$Height, survey$Sex, na.rm=TRUE, hedges.correction=TRUE)
cohen.d(survey$Wr.Hnd, survey$W.Hnd, na.rm=TRUE, hedges.correction=TRUE)
```

d estimate: -1.782261 (large)
d estimate: 0.3370644 (small)
g estimate: -1.775764 (large)
g estimate: 0.3359783 (small)

And with pingouin:

```
import pandas as pd
import pingouin as pg
survey = r['MASS::survey']
# Cohens d
x = survey['Height']
y = survey['Sex'].map({'Male': 0, 'Female': 1})
pg.compute_effsize(x, y, eftype='cohen')
pg.compute_effsize(x, y, eftype='hedges')
x = survey['Wr.Hnd']
y = survey['W.Hnd'].map({'Left': 0, 'Right': 1})
pg.compute_effsize(x, y, eftype='cohen')
pg.compute_effsize(x, y, eftype='hedges')
```

np.float64(25.43526497221914) # d
np.float64(25.39217869615101) # g
np.float64(13.224161840841502) # d
np.float64(13.203048224278156) #g

I would have expected some difference between R and Python due to handling of missings, but not that large.

**Comment by raphaelvallat** [comment]
Hi — sorry for the late reply.

I think that you are not calculating the effect size properly. What you're trying to do is:

```python
x = survey[survey["Sex"] == "Male"]['Height']
y = survey[survey["Sex"] == "Female"]['Height']
pg.compute_effsize(x, y, eftype='cohen')
```

Closing this issue but feel free to reopen
