### ISSUE TITLE
Diebold-Mariano test / time series and forecasting tests

### ISSUE THREAD

**Issue by aeturrell** [raphaelvallat/pingouin#434]
Hi there,

A huge fan of this package, so thank you. I just wondered if there was any possibility of adding forecasting tests, in particular the *Diebold-Mariano* test. There's an example in Python [here](https://github.com/johntwk/Diebold-Mariano-Test).

Thanks again for this brilliant package, which I cover a lot in [Coding for Economists](https://aeturrell.github.io/coding-for-economists/econmt-statistics.html).

**Comment by raphaelvallat** [comment]
Hi Arthur,

Thanks for your message and kind words! I unfortunately have very little time to work on Pingouin these days and therefore am not planning on implementing any new features. The DM test is also very specific in a way so I'm not sure if Pingouin is the best place for it. I wonder if it would be better implemented as part of `scipy.stats`?

Thanks for sharing the [Coding for Economists](https://aeturrell.github.io/coding-for-economists/econmt-statistics.html) great resource!

Raphael

**Comment by aeturrell** [comment]
Sorry to hear you don't have as much time to work on Pingouin, it's so often the case that life has other demands that have to come first. You've built something truly amazing in the time you have spent on it! 

Good shout on another place that might be a better fit. Thinking about its focus on forecast and prediction, I actually wonder if `sklearn.metrics` might be the one to go for; I'll raise an issue there. Thanks.
