### ISSUE TITLE
Better handling of 'greater' & 'less' tails (alternative) for hypothesis testing

### ISSUE THREAD

**Issue by raphaelvallat** [raphaelvallat/pingouin#44]
This affects several Pingouin functions (T-test, effect sizes...).

- **T-test**: The confidence intervals of the difference in means should be Inf on one of the two sides, as in the R [t.test function](https://github.com/SurajGupta/r-source/blob/a28e609e72ed7c47f6ddfbb86c85279a0750f0b7/src/library/stats/R/t.test.R#L98).

Or should we automatically determine the 'greater' and 'less' using the sign of the T-value?

**Comment by Leicas** [comment]
I was gonna ask about that, I looked at the code and the wilcoxon handling of one side tails is just 0.5 the P value of the two sided.
So instead of `distributions.norm.sf(z)` it's doing `0.5*2. * distributions.norm.sf(abs(z))` , which looks like a "greater" but actually is not the same.
I know it's been introduced by the 1.3.0 version of scipy but I think the current implementation should maybe print a warning instead of silently computing half of a two sided.

I'm also currently looking at non inferiority test and equivalence test (thus the interest in greater and less tails alternative), maybe it is something that could be added to the pairwise-ttest ?

**Comment by raphaelvallat** [comment]
Hi @Leicas!

So I've been wanting to add the option to choose between 4 different tails values on all hypothesis-testing Python functions, (i.e. `tail=('two-sided', 'greater', 'positive', 'one-sided')`), and by extension, the [pingouin.pairwise_ttests](https://pingouin-stats.org/generated/pingouin.pairwise_ttests.html#pingouin.pairwise_ttests) function as well. 

The [pingouin.wilcoxon](https://pingouin-stats.org/_modules/pingouin/nonparametric.html#wilcoxon) is a great example. For now, it only supports `tail=('two-sided', 'one-sided')`, with the latter being half the former, which is kind of an oversimplification. However, as you noted, the newest release of SciPy (1.3.0) now accepts `tail=('greater', 'positive')`. Two things on that:
1. Since this would require to add scipy>=1.3.0 as a mandatory dependency, which might cause conflict for users dealing with other packages, I prefer to wait for at least a few months before implementing that. I think we can safely aim for an August release.
2. I am still wondering if `tail='one-sided'` should return simply half the two-sided p-value, or rather automatically decide between `tail=('greater', 'positive')` based on the sign of the difference. The former solution is the current behavior of the [pingouin.wilcoxon](https://pingouin-stats.org/_modules/pingouin/nonparametric.html#wilcoxon) function, while the latter solution is the behavior of the [pingouin.mwu](https://pingouin-stats.org/_modules/pingouin/nonparametric.html#mwu) function. I do think that we need to homogenize that in future releases, i.e. having the same behavior for all functions. Do you have any thoughts on that?

Thanks

**Comment by Leicas** [comment]
Hi!
Nice for the 4 tails values.

2) I'm not sure why half a two-sided p-value would be of interest... I saw
the implementation on the mwu but honestly don't see why it would be
something else than "positive"/"negative" as I think choosing the side is
important in the hypothesis formulation.

Thanks,

Le ven. 28 juin 2019 à 13:19, Raphael Vallat <notifications@github.com> a
écrit :

**Comment by raphaelvallat** [comment]
Yes, agreed! So, I'll change the behavior of the `pingouin.wilcoxon` function to match the `pingouin.mwu` function and include it in the next or so release.

Thanks again, and if there are any other changes that you'd like to make to the `pingouin.pairwise_ttests` or any other functions, please feel free to make a PR!

Have a great day,
Raphael
