### ISSUE TITLE
ensure compatibility with numpy 2.0

### ISSUE THREAD

**Issue by raphaelvallat** [raphaelvallat/pingouin#444]
See the [NumPy 2.0 migration guide](https://numpy.org/doc/stable/numpy_2_0_migration_guide.html)

**Comment by raphaelvallat** [comment]
Yeah, I keep hearing good things about ruff so let's change

**Comment by remrama** [comment]
Adding a checklist for this Issue that combines goals of numpy 2.0 compatibility with ruff replacement.

- [ ] Replace black with ruff in `pyproject.toml`
- [ ] Replace flake8 with ruff in `pyproject.toml`
- [ ] Replace black GitHub Action with ruff GitHub action
- [ ] Update `[test]` installation requirements
- [ ] Replace black and flake8 with ruff in Contributing sections in docs and README.
- [ ] Run ruff's formatter (in case of minor deviations from black)
- [ ] Run ruff's linter (in case of minor deviations from flake8)
- [ ] Run ruff's numpy 2.0 compatibility enforcer

**Comment by remrama** [comment]
@raphaelvallat this got addressed when #446 was merged, so you can close it as completed 👍 ✅
