### ISSUE TITLE
Rmcorr Issues

### ISSUE THREAD

**Issue by sknepal** [raphaelvallat/pingouin#46]
Hi,

Noticed some issues while trying rmcorr. 

- If the column you pass is non-numeric, it just results in an assertion error with no error message. The r library rmcorr() returns message saying: _'Measure 1' and 'Measure 2' must be numeric_. Maybe return some message like this?

- In ancova, `bw = ss_slopes.sum() / ss.sum()` (and `ss_c = ss_slopes.sum() * bw`) returns NaN if any of the values in ss_slopes is NaN. Basically, sum() on a numpy array == NaN if it has any NaNs in the array. As a result, rmcorr or ancova result turns out to be NaN. I think this should be changed to np.nansum(ss_slopes) instead. This will ignore NaNs but still sum the remaining values.

Thank you!

**Comment by raphaelvallat** [comment]
Hi @sknepal !
I just pushed a new commit to the develop branch to take into account your suggestions (see 71e60a8343cb605cabc35a3e06312e5b0f05455f). This will be released in the next release of Pingouin, probably end of July or early August.

Quick question: could you give an example of when `ss_slopes` contains NaN? Both the rm_corr and ANCOVA function apply an automatic deletion of NaN values. Do you have the latest version of Pingouin?

Thanks!
Raphael
