### ISSUE TITLE
module 'numpy' has no attribute 'format_float_positional'

### ISSUE THREAD

**Issue by xigrug** [raphaelvallat/pingouin#52]
I try to run the example
```
import numpy as np
import pingouin as pg

np.random.seed(123)
mean, cov, n = [4, 5], [(1, .6), (.6, 1)], 30
x, y = np.random.multivariate_normal(mean, cov, n).T

# T-test
pg.ttest(x, y)
```
 The erroe is module 'numpy' has no attribute 'format_float_positional'

Python 3.6.7
statsmodels-0.10.1  
pingouin-0.2.8  
numpy-1.16.4

**Comment by raphaelvallat** [comment]
Hi @xigrug ! Are you sure that you have Numpy 1.16.4? I believe the `numpy.format_float_positional` was added in Numpy 1.14.0, so it seems that you don't have the latest version of numpy. Please update with:

`pip install --upgrade numpy`

and then in a iPython console / Jupyter notebook:

```
import numpy as np
print(np.__version__)
np.format_float_positional(0.325)
```

Thanks

**Comment by raphaelvallat** [comment]
Hi @xigrug ! Did you find the solution to your problem? Unless I hear from you I will close this issue in a few days since I cannot replicate the error and I suspect it's mostly an outdated dependency error.
Thanks
