### ISSUE TITLE
logistic regression is using regularization by default

### ISSUE THREAD

**Issue by ejolly** [raphaelvallat/pingouin#53]
Thanks for the awesome package! I noticed a small concern with the logistic regression implementation. Since pingouin relies on `sklearn`'s `LogisticRegression` implementation, it's worth noting that it implements L2 regularization by default with a hyperparameter value `C=1`. 

This results in coefficients being penalized by default, and I suspect (but not 100% sure) the standard-error and p-values not being totally correct/interpretable. I say this because estimating standard errors for regularized/penalized models is not trivial and the computation often involves incorporating the penalty term somehow, but even then may not all that informative. See for example [this stackoverflow discussion and links](https://stats.stackexchange.com/questions/171448/ridge-regression-in-r-with-p-values-and-goodness-of-fit).

Here's [an example jupyter notebook](https://nbviewer.jupyter.org/urls/dl.dropbox.com/s/7y3raos4fxfrq6y/logistic_regression_example.ipynb) demonstrating the results different from the same analysis using `glm` in R (using the rpy2 package). 

One possibility is setting the `C=1e9` by default but letting it be overridden if desired. This effectively removes the effect of regularization as `sklearn` doesn't have a flag to disable it completely but this seems to be the accepted community solution. 

Opened a pull request if you go with that solution!

**Comment by raphaelvallat** [comment]
Thanks @ejolly this is very useful! I've replied directly to the PR.
