### ISSUE TITLE
Circular correlation for uniform marginals

### ISSUE THREAD

**Issue by dominikstrb** [raphaelvallat/pingouin#55]
According to Jammalamadaka & Sengupta (2001, pg. 177) the circular means are not well defined if the marginal distribution of one of the angles is uniform. This leads to wrong estimates of circular correlations in these cases. There is an alternative formulation of the circular correlation coefficient that deals with this problem (see equation 8.2.4 in Jammalamadaka & Sengupta, 2001). This implementation can also lead to slightly different values for the coefficient in other cases, though. This is the implementation:

```
def circcorr(x, y, tail='two-sided'):
    from scipy.stats import norm
    
    x = np.asarray(x)
    y = np.asarray(y)

    # Check size
    if x.size != y.size:
        raise ValueError('x and y must have the same length.')

    n = x.size
    
    x_sin = np.sin(x - stats.circmean(x))
    y_sin = np.sin(y - stats.circmean(y))

    
    num = np.abs(np.sum(np.exp((x - y)*1j))) - np.abs(np.sum(np.exp((x + y)*1j)))
    denom = 2 * np.sqrt(np.sum(x_sin**2) * np.sum(y_sin**2))
    
    r = num / denom
    
    # Compute T- and p-values
    tval = np.sqrt((n * (x_sin**2).mean() * (y_sin**2).mean())
                   / np.mean(x_sin**2 * y_sin**2)) * r

    # Approximately distributed as a standard normal
    pval = 2 * norm.sf(abs(tval))
    pval = pval / 2 if tail == 'one-sided' else pval
    
    return r, pval
```
I'm not sure if this should be added to pingouin, whether as an extra function or an alternative to circ_corrcc with a kwarg.

References:
- Jammalamadaka, S. R., & Sengupta, A. (2001). Topics in circular statistics (Vol. 5). world scientific.

**Comment by raphaelvallat** [comment]
Hi @dominikstrb ! This is interesting, thanks for sharing! I, unfortunately, don't have access to the book, any chance that you could send me a screenshot of the relevant paragraph/equation?

Here are a few thoughts:

1) I would probably leave the current method as the default, to be consistent with the Matlab circular toolbox.

2) However, we can indeed add an optional argument for this method. What do you think is the most appropriate argument name? `correction_uniform=True`, `method='js'`, or any other ideas?

3) Do you know of any packages / softwares (R, Matlab, Python, SPSS) that implement this equation? It would be better for testing purposes.

Thanks!
Raphael

**Comment by dominikstrb** [comment]
Thanks for your quick answer!

I took a ![screenshot of the relevant page](https://user-images.githubusercontent.com/23743923/62699014-cd509780-b9de-11e9-9d7c-86eac2b5eb99.png)

My answers to your thoughts:
1. Definitely!
2. I think as long as there's only one alternative method, one boolean kwarg should be enough, if the user is referred to the relevant literature.
3. I wasn't able to find one, unfortunately. Most circular statistics packages (like this one) seem to build upon Philipp Berens' MATLAB toolbox. I'll make sure to test the two methods against one another with simulations before proposing any changes to Pingouin.

If you're okay with it, I could start a pull request that keeps the default method, but allows to enable the alternative with a kwarg.

Best,
Dominik

**Comment by raphaelvallat** [comment]
Hi @dominikstrb ! Yes, please start working on a pull request :) Make sure to push on the develop, and not the master, branch. Thanks!

**Comment by raphaelvallat** [comment]
Hi @dominikstrb! Just wanted to follow-up on the PR. Please let me know if you need any help, or, if you're too busy at the time I can also quickly add it.

Thanks!
Raphael

**Comment by dominikstrb** [comment]
Thanks for reminding me. I was in fact quite busy the past few weeks, but I managed to create the PR this morning. Hope everything is alright!

**Comment by raphaelvallat** [comment]
Thanks for the PR @dominikstrb ! Closing the issue now.
