### ISSUE TITLE
Use pandas_flavor to extend pandas functionality

### ISSUE THREAD

**Issue by hoechenberger** [raphaelvallat/pingouin#59]
Currently, `pingouin` imports `pandas` and mokey-patches the `DataFrame` to add new methods. The "proper" way to achieve this, however, is to use the pandas extension API, most probably via [`pandas_flavor`](https://github.com/Zsailer/pandas_flavor) (`pyjanitor`, for example, [does this too](https://pyjanitor.readthedocs.io/#adding-new-functionality))

One simply needs to import `pandas_flavor` and add a decorator:

```python
# pingouin/pairwise.py

import pandas as pd
import pandas_flavor as pf

@pf.register_dataframe_method
def pairwise_ttests(dv=None, between=None, within=None, subject=None,
                    data=None, parametric=True, alpha=.05, tail='two-sided',
                    padjust='none', effsize='hedges', return_desc=False,
                    export_filename=None):
...
```

Usage from the user's side:
```python
import pandas as pd
import pingouin as pg

data = pd.DataFrame(...)
data.pairwise_ttests(...)
```

**Comment by raphaelvallat** [comment]
Hi @hoechenberger!

I like this, thanks so much for sharing the pandas_flavor package. I agree that using a decorator is much more elegant. Do you have time to work on a PR on the develop branch?

Thanks!
Raphael

**Comment by hoechenberger** [comment]
Hi @raphaelvallat, I won't have time for a few weeks I'm afraid. Just wanted to leave this here so it won't be forgotten ;) Best wishes!

**Comment by raphaelvallat** [comment]
Got it, I'll add this to my todo list then :-)
Thanks again for the tip @hoechenberger!

**Comment by raphaelvallat** [comment]
Added in 93d74d332fe767f9f8278c1cf86b7d78581f5771

**Comment by hoechenberger** [comment]
Awesome, thanks!

**Comment by LegrandNico** [comment]
Thanks for sharing this @hoechenberger, I didn't know this was available. Indeed much more elegant than the brute force method I shared ;)
