### ISSUE TITLE
Shapiro-Wilk test should have option to return W statistic

### ISSUE THREAD

**Issue by hoechenberger** [raphaelvallat/pingouin#6]
Currently `pingouin.normality()` silently discards the `W` statistic returned by `scipy.stats.shapiro()`. I would love to have an option to retrieve these stats, as I need to present them together with the `p` values when drafting a scientific publication. I wonder if the function could not be adjusted to return a `DataFrame` with numerous information like most of the other `pingouin` functions?

**Comment by raphaelvallat** [comment]
Indeed @hoechenberger that's a good idea, I agree that returning a dataframe might be best here. I should be able to work on this next week, unless you want to submit a PR! Thanks

**Comment by hoechenberger** [comment]
I am currently busy and won’t have time to work on an implementation until mid-February or so. But would be willing to give it a try then ;)

**Comment by hoechenberger** [comment]
Hi @raphaelvallat, I just started working on this, but we need to make a design decision before I can continue. Currently, the `distribution.normality()`, like some other functions in that module, allow passing multiple array-like objects, and would then return arrays with the corresponding number of results. If we intend to return a results `DataFrame` instead, we now have two options:

- return a `DataFrame` with multiple rows, one corresponding to the test results of each passed array, in the order they were provided by the user
- or we could allow providing a single input array only, and accordingly return a `DataFrame` with the results for this array

I personally would prefer the 2nd approach, as it seems to fit better with the way things are currently done in other places of `pingouin`. But I'll leave it to you to decide.

**Comment by raphaelvallat** [comment]
Hi @hoechenberger! I am planning on releasing the next Pingouin version sometimes in March and I was wondering if you'd have time to submit this PR in the coming days/weeks? If not I can also work on this, just let me know!

Thanks,
Have a great day,
Raphael

**Comment by hoechenberger** [comment]
Hi, I actually implemented this weeks ago already, don’t remember why I never filed a PR. I’m currently traveling, but can look at the code again (and file a PR) tomorrow!

**Comment by hoechenberger** [comment]
Heh, running late again. Expect a PR tonight CET :)

Cheers!

**Comment by hoechenberger** [comment]
Hey @raphaelvallat, I just looked at my code again and remembered why I hadn't filed a PR: I ran into a conceptual issue. Currently, `distribution.normality()` accepts a variable number of arguments: `def normality(*args, alpha=.05)`

Now, if I were to return a `DataFrame`, I'm not sure how to best represent the connection between input argument and test results. My first idea was to create one row per input, and row order follows input order. However, I don't really _like_ this approach, it feels kind of clumsy and also a bit inconsistent considering how other functions in `pingouin` behave. I would propose we change the `normality()` API such that it accepts 
- either a single iterable to do the stats on, or
- a `DataFrame` and a collection of column names

In both cases, the output could uniquely point out to which input it belongs, as for the multiple-columns-in-a-DataFrame case we could use the column names as unique identifies.

Proposed API: `def normality(x, data=None, alpha=.05)`

---

Don't know if this is the right place, but I was also thinking that I would like to see _all_ functions in pingouin follow this approach. Like, I would love to do `correlation.corr(x='foo', y='bar', data=foobar)` instead of `correlation.corr(x=foobar['foo'], y=foobar['bar']` -- also because this would match more closely with how I plot data (using `seaborn`).

---
Another suggestion, since we're talking about potentially breaking API changes: Have you considered changing function parameters to keyword-only params? I believe this is a really neat feature of Python 3 that makes it much easier to change APIs, be it through introduction of new or by changing the order of existing params. In the `correlation.corr()` example above, one could then simply plug in a `data` param anywhere in the function signature, without breaking existing code.

---

Sorry if this was a bit much at once and a little out of scope, bit these are the things I'd been thinking about while working on this issue, and which kept me from filing the PR :)

**Comment by raphaelvallat** [comment]
Hi @hoechenberger ! Thanks for all your inputs!

1. I agree with you that the function should work with either a single iterable `x` (list of values, 1D numpy array, pandas series) OR a list of columns `x` + a dataFrame `data`. The function should return a DataFrame with a single row if a single iterable was passed, and one row per column passed if `x` was a list of column (where the indices are the column(s) names). 
Furthermore, the current implementation of the normality test is the Shapiro test, which is not appropriate for n > 50 (see [here](https://datascience.stackexchange.com/questions/12846/how-to-decided-which-test-of-normality-to-use)). I propose that we change the API to  `normality(x, data=None, method="auto", alpha=.05)`. If n < 50 we use [scipy.stats.shapiro](https://docs.scipy.org/doc/scipy/reference/generated/scipy.stats.shapiro.html) and if n > 50 we use [scipy.stats.normaltest](https://docs.scipy.org/doc/scipy/reference/generated/scipy.stats.normaltest.html). The `method` argument could also be _"shapiro"_ or _"normaltest"_. What do you think?

2. I actually use the [pingouin.corr()](https://pingouin-stats.org/generated/pingouin.corr.html#pingouin.corr) function very often with NumPy array or python lists and I don't think we should add the `data=None` argument here. The _pandas-only_ version of this function is the [pingouin.pairwise_corr()](https://pingouin-stats.org/generated/pingouin.pairwise_corr.html#pingouin.pairwise_corr) function which I use almost exclusively when working with Pandas DataFrame, and which has some really nice advanced columns selection / combination features. We should mention the `pairwise_corr` function in the documentation of the `corr` function.

3. I totally agree with you on this point, I think that this flexibility is really nice. This is what I implemented for all the ANOVAs-related function (e.g. `anova(dv=None, between=None, data=None, detailed=False, export_filename=None)`). If you see any other functions that you think we should modify like this, please let me know or don't hesitate to fill a PR.

Thank you again, Richard, and have a great day!
Raphael

**Comment by hoechenberger** [comment]
Hey Raphael, I will respond to your message tomorrow – just wanted to let you know this is on my agenda, I'm just extremely busy these days, therefore cannot reply earlier. Best wishes!

**Comment by hoechenberger** [comment]
> 1. I agree with you that the function should work with either a single iterable `x` (list of values, 1D numpy array, pandas series) OR a list of columns `x` + a dataFrame `data`. The function should return a DataFrame with a single row if a single iterable was passed, and one row per column passed if `x` was a list of column (where the indices are the column(s) names).

Great, so we agree on this one :)

>    Furthermore, the current implementation of the normality test is the Shapiro test, which is not appropriate for n > 50 (see [here](https://datascience.stackexchange.com/questions/12846/how-to-decided-which-test-of-normality-to-use)). I propose that we change the API to  `normality(x, data=None, method="auto", alpha=.05)`. If n < 50 we use [scipy.stats.shapiro](https://docs.scipy.org/doc/scipy/reference/generated/scipy.stats.shapiro.html) and if n > 50 we use [scipy.stats.normaltest](https://docs.scipy.org/doc/scipy/reference/generated/scipy.stats.normaltest.html). The `method` argument could also be _"shapiro"_ or _"normaltest"_. What do you think?

This sounds very reasonable. I didn't know about `normaltest()`! Not so sure about `method='auto'` -- maybe should default to `method=None` (which would work like you proposed for `auto`?)

> 2. I actually use the [pingouin.corr()](https://pingouin-stats.org/generated/pingouin.corr.html#pingouin.corr) function very often with NumPy array or python lists and I don't think we should add the `data=None` argument here. The _pandas-only_ version of this function is the [pingouin.pairwise_corr()](https://pingouin-stats.org/generated/pingouin.pairwise_corr.html#pingouin.pairwise_corr) function which I use almost exclusively when working with Pandas DataFrame, and which has some really nice advanced columns selection / combination features. We should mention the `pairwise_corr` function in the documentation of the `corr` function.

Okay, I think you've got a valid point here. I need to think this over :) -- Wouldn't a list comprehension work similarly well for you?

> 3. I totally agree with you on this point, I think that this flexibility is really nice. This is what I implemented for all the ANOVAs-related function (e.g. `anova(dv=None, between=None, data=None, detailed=False, export_filename=None)`). If you see any other functions that you think we should modify like this, please let me know or don't hesitate to fill a PR.

That's not _quite_ what I meant! These are keyword arguments alright. But as such, the arguments can still be passed by position, omitting the keywords. 
Say the function signature was this:
```python
def anova(dv=None, between=None, data=None)
```
then the users could invoke it like `anova('x', 'y', z)
```
they don't _have_ to use the keywords.

Now, assume you want to change the function signature from to `def anova(data=None, dv=None, between=None)`: the above user code would break.

In Python 3.6+, we have keyword-only arguments. A function signature could look like this:
```python
def anova(*, dv=None, between=None, data=None)
```
Now, the users _have_ to specify parameters by keyword;  passing by position is not possible anymore. If you decide to change the order of arguments in the signature, the user code would continue to work as intended.

**Comment by raphaelvallat** [comment]
Thanks @hoechenberger!

1. Ok I agree that `method='auto'` might be confusing. I'd suggest that we let `method='shapiro'` as the default then, since it is clearly the most well-known and widely-used univariate normality test.

2. Can you please show an example of list comprehension? Not sure to understand what you mean!

3. Oh I see! I didn't know that, thank you! I guess I have to think this over but I definitely agree with you that keyword-only arguments are (much) better. Is this only valid for Python 3.6+? Pingouin is compatible (and tested) on Python 3.5-3.6-3.7 and I'd like to keep the Python 3.5 compatibility for now. If it _is_ compatible with Python 3.5-->3.7, then, yes, we should move to keyword-only arguments!

Thank you very much for your help, Richard, really appreciate it!
Raphael

**Comment by raphaelvallat** [comment]
Hi @hoechenberger ! Are you still working on the normality function? Just wanted to let you know that it'd be great to add a `remove_na=True` argument to automatically remove missing values as well (as suggested in https://github.com/raphaelvallat/pingouin/issues/12). 
Thank you!
Raphael

**Comment by raphaelvallat** [comment]
Hi! 

I am closing this issue since I completely rewrote the `normality` function:
-  support for pandas dataframe (wide or long format)
- support for scipy.stats.normaltest
- casewise deletion of missing values

The changes will be visible in the next (June) release of Pingouin.
See develop commit at 9a7fc50ac79b5c287a433e151cc55136029415d6

Thanks!
