### ISSUE TITLE
Keyword-only arguments

### ISSUE THREAD

**Issue by hoechenberger** [raphaelvallat/pingouin#60]
The docs mention that one should ideally pass parameters as keyword arguments, not by position. I'm wondering why this isn't simply enforced? Python 3 supports keyword-only arguments. It's as simple as changing a function signature from
```python
def f(foo=1, bar=2)
```
to
```python
def f(*, foo=1, bar=2)
```
Now, positional arguments won't be accepted anymore.

**Comment by raphaelvallat** [comment]
Hi @hoechenberger ! 

I remember that we had a discussion about that a few months ago. Keywords only argument are great, and I definitely plan to implement them in future releases. My only concern is that for users that are beginners in Python, it can be a bit confusing to see `def f(*, ...)` in the documentation of the function. It will also certainly break existing code of potentially many current users so I think we have to do a smooth transition here. Thoughts?

Thanks
Raphael
