### ISSUE TITLE
Type hints

### ISSUE THREAD

**Issue by hoechenberger** [raphaelvallat/pingouin#61]
A great addition in Python 3 are [type hints](https://blog.jetbrains.com/pycharm/2015/11/python-3-5-type-hinting-in-pycharm-5/), which can make development less error-prone if an IDE is used that supports this feature.

Here's an example from one of my projects that's using type hints (and keyword-only arguments, for that matter):

https://github.com/hoechenberger/questplus/blob/9d5a6b9fc7bafd000dd82c1737be274ea31ee3de/questplus/qp.py#L10-L20

And another one:
https://github.com/hoechenberger/questplus/blob/9d5a6b9fc7bafd000dd82c1737be274ea31ee3de/questplus/psychometric_function.py#L7-L13

I think type hints could be a welcome addition to pingouin as well.

**Comment by raphaelvallat** [comment]
Thanks @hoechenberger for another great Python tip! A few questions:
1. Do you know if this feature is supported by Jupyter Lab? 
2. And can it support multiple input type (e.g. a Series, a list, and a numpy array for the same argument?). Looking at your code, I think you have to use `Union`, is that correct?
3 How is this displayed in the Sphinx documentation? I don't want to overburden the API with type hints for every variables.

Thanks!

**Comment by raphaelvallat** [comment]
I don't see any immediate need for type hints in Pingouin as I feel it would only help a fraction of all Pingouin users, at the cost of less-readable API documentation and code.

Closing the issue for now but please feel free to reopen.
Thanks
Raphael
