### ISSUE TITLE
Empirical CDF shift functions

### ISSUE THREAD

**Issue by hoechenberger** [raphaelvallat/pingouin#62]
I sometimes plot shift functions as / via empirical cumulative distribution functions, to avoid the troubles that come with kernel-density estimates. Would be great to see this feature in Pingouin as well. I typically use [`statsmodels.distributions.empirical_distribution.ECDF`](https://www.statsmodels.org/devel/generated/statsmodels.distributions.empirical_distribution.ECDF.html) to estimate the CDFs.

**Example (based on my own implementation) using a KDE:**
![uni vs bi - Mean - SJ](https://user-images.githubusercontent.com/2046265/63998942-9c0d4800-cb02-11e9-82e4-80c6a17eb675.png)

**Same example using CDFs:**
![uni vs bi - Mean - SJ - CDF](https://user-images.githubusercontent.com/2046265/63998968-a62f4680-cb02-11e9-90c0-d4547764efcb.png)

(Yes, could use some visual tuning, I know :))

**Comment by raphaelvallat** [comment]
Hi @hoechenberger ! This looks great 👏! Any chance that you could share your code?

I didn't implement the plot_shift function, so I will let @LegrandNico replies to this one (see also issue https://github.com/raphaelvallat/pingouin/issues/40).

Thanks!

**Comment by hoechenberger** [comment]
@raphaelvallat @LegrandNico 
My current implementation is not generic enough to share – it's more or less closely coupled to a specific analysis we're doing. But I'm planning to refactor the code to make it re-usable, yes. Maybe some time next week!

**Comment by hoechenberger** [comment]
I will be looking into this soon-ish. I have not forgotten about it :)

**Comment by raphaelvallat** [comment]
HI @hoechenberger and @LegrandNico, closing this issue for now, but please feel free to reopen!
