### ISSUE TITLE
Question about homoscedasticity p-value

### ISSUE THREAD

**Issue by robotenique** [raphaelvallat/pingouin#67]
I have a simple question, that by reading through the docs I couldn't understand... What exactly is the p-value measuring in the homoscedasticity function? I find it confusing that when I apply the function it returns that equal_var is true, however the p-value is close to 1.

Does someone have a reference to how can I interpret this? Thanks!

**Comment by raphaelvallat** [comment]
Hi @robotenique ! The levene/bartlett test implemented in [pingouin.homoscedasticity](https://pingouin-stats.org/generated/pingouin.homoscedasticity.html#pingouin.homoscedasticity) test the **NULL** hypothesis that the group variances are equal. In other words, a p-value above the 0.05 significance level means that you **fail to reject the null hypothesis**, i.e. there is insufficient evidence to claim that the variances are not equal (so practically speaking you can consider the variances equal).

**Comment by robotenique** [comment]
Thank you, now I understand it :D
