### ISSUE TITLE
spherical statistics

### ISSUE THREAD

**Issue by kristianeschenburg** [raphaelvallat/pingouin#69]
Is there any interest in expanding this to spherical data?  I've been using the "Directional" R package to fit spherical VMF models and perform spherical regression, but it'd be great to have something for Python.

**Comment by raphaelvallat** [comment]
Hi @kristianeschenburg! I never use spherical analysis in my day-to-day analyses, and my knowledge on the topic is very limited. Therefore, I am not planning to implement it in Pingouin anytime soon. That said, please feel free to contribute. I'd be happy to help you create a pull request. I am also leaving the issue open in case others want to second your request. Thanks!
