### ISSUE TITLE
qqplot() should allow for NaN removal

### ISSUE THREAD

**Issue by hoechenberger** [raphaelvallat/pingouin#7]
Currently, if the passed iterable contains one or more `NaN` values, `qqplot()` will return a basically empty plot. There should be the option to automatically remove `NaN` values before plotting (might even be the default).

**Comment by raphaelvallat** [comment]
Yes, agreed, NaN should be automatically removed. We just need to add this line:

```
x = np.asarray(x)
x = x[~np.isnan(x)]
```

I'll include this in the next release. Thanks!
