### ISSUE TITLE
Allow to add rugplot to shift function plots

### ISSUE THREAD

**Issue by hoechenberger** [raphaelvallat/pingouin#70]
Additionally to the issues / requests raised in #40 and #62, I think it would be great to have the possibility to disable the pointplots and get a rugplot instead (or plot both, if desired). I just had a look at the code and believe quite some refactoring would be required to get this to work. But should be doable :)

**Comment by MartinLichtblau** [comment]
What do the shift colors (red/blue) tell? 
Cannot find anything in doc. 
Don't deem worth a separate issue.

**Comment by raphaelvallat** [comment]
Hi @MartinLichtblau, 
- red means that the 95% confidence intervals of the bootstrapped Y - X quantile is entirely _above_ 0.
- blue means that the 95% confidence intervals of the bootstrapped Y - X quantile is entirely _below_ 0.
- grey means that the 95% confidence intervals of the bootstrapped Y - X quantile includes zero, and therefore is not "significant" at the 0.05 level.

Hope this helps!
