### ISSUE TITLE
error when adding pingouin to default imports in IPython / JupyterLab

### ISSUE THREAD

**Issue by alonappleboim** [raphaelvallat/pingouin#72]
Before I provide system specific, perhaps someone else can verify this issue? I'm afraid my system might be a mess.
Thanks,

--------

When I add the import to ~/.ipython/profile_default/ipython_config.py (below), the kernels can't seem to be created (log below). I played around a bit with order of imports and it made no difference.

c.InteractiveShellApp.exec_lines = [
    'import sys, os, collections\n'
    **'import pingouin as pg\n'**
    'import itertools as it\n'
    'from IPython.display import display\n'
    'import numpy as np\n'
    'import numpy.random as rand\n'
    'import pandas as pd\n'
    'import scipy as sp\n'
    'import scipy.stats as stats\n'
    'from matplotlib import pyplot as plt\n'
    'import matplotlib as mpl\n'
    'import seaborn as sb\n'
    '%matplotlib inline\n'
]

---------

Jupyter lab log:
[I 08:35:39.337 LabApp] [nb_conda_kernels] enabled, 1 kernels found
[I 08:35:39.645 LabApp] JupyterLab extension loaded from /Users/user/anaconda3/lib/python3.6/site-packages/jupyterlab
[I 08:35:39.645 LabApp] JupyterLab application directory is /Users/user/anaconda3/share/jupyter/lab
[W 08:35:39.647 LabApp] JupyterLab server extension not enabled, manually loading...
[I 08:35:39.712 LabApp] JupyterLab extension loaded from /Users/user/anaconda3/lib/python3.6/site-packages/jupyterlab
[I 08:35:39.712 LabApp] JupyterLab application directory is /Users/user/anaconda3/share/jupyter/lab
[I 08:35:39.713 LabApp] Serving notebooks from local directory: /Users/user
[I 08:35:39.713 LabApp] The Jupyter Notebook is running at:
[I 08:35:39.713 LabApp] http://localhost:8888/?token=a342013f06db3c5f8da606492199a0ff4a7fa64944928585
[I 08:35:39.713 LabApp] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
[C 08:35:39.717 LabApp] 
    
    To access the notebook, open this file in a browser:
        file:///Users/user/Library/Jupyter/runtime/nbserver-5436-open.html
    Or copy and paste one of these URLs:
        http://localhost:8888/?token=a342013f06db3c5f8da606492199a0ff4a7fa64944928585
[W 08:35:42.724 LabApp] 404 GET /api/kernels/e9f2ef4e-c953-4d4d-82d7-ccfe2099483f/channels?session_id=cf2ef7f3-2ec8-43c0-9956-cfdfbe84b57e&token=0fc940aa10d581003cee51beba9120695378db5f3f6799ef (::1): Kernel does not exist: e9f2ef4e-c953-4d4d-82d7-ccfe2099483f

**Comment by raphaelvallat** [comment]
Do you have this issue only with Jupyter Lab, or also with Notebook and iPython (see https://github.com/jupyter/help/issues/189). Also, did you install Pingouin using pip (develop or stable?) or conda?

Thanks

**Comment by alonappleboim** [comment]
In iPython it seems to be ok.
In jupyter notebook it doesn't (kernel seems unresponsive starting from init).
Installed with: ../my/interpreter -m pip install pip pingouin
Note that all other default code work fine (imports, ipy magic etc.)

**Comment by raphaelvallat** [comment]
And if you remove the specific line of:

`'import pingouin as pg\n'`

in the ipython_config.py file, does it work on Jupyter Notebook / Lab?

I think it might also be worth a try installing Pingouin with conda instead of pip.

Thanks

**Comment by alonappleboim** [comment]
Yes. The command collection (without the pg line) has been working for weeks (and still is). I'll try installing with conda and update (pip is how I usually install packages and it's been fine so far.)

So I understand that you can't recreate this issue? If it's just me then don't worry about it, my conda env/installation is probably completely messed up by now :)

**Comment by alonappleboim** [comment]
Installed with "conda install pingouin" and still have the same issue.

**Comment by raphaelvallat** [comment]
I cannot replicate the error: adding these lines to my profile_default did not work, so I add to create a new iPython profile, and I'm not sure how to run Jupyter Lab or Notebook with this specific iPython profile. But it seems that there might be specific config files for Jupyter Lab / Notebook: https://jupyter.readthedocs.io/en/latest/migrating.html

Also, have you tried simply changing/creating the `startup.py` file in your  profile_default/startup folder? I have the following lines and it works fine with iPython and Jupyter Lab / Notebook:

```
import numpy as np
import pandas as pd
import pingouin as pg
import seaborn as sns
import matplotlib.pyplot as plt
```

**Comment by alonappleboim** [comment]
Then it's probably only my setup. 
I tried updating the startup.py script and I get the same issue - no problem importing other modules, but the pingouin import causes the same issue (unresponsive jupyter kernels).

**Comment by raphaelvallat** [comment]
I am really sorry about that, but indeed I don't think it's an issue related to Pingouin per se. Closing the issue for now but please feel free to re-open if needed. Thanks
