### ISSUE TITLE
Potentially add option to retrieve outliers removed by correlation.shepherd()

### ISSUE THREAD

**Issue by hoechenberger** [raphaelvallat/pingouin#8]
`correlation.shepherd()` removes outliers before calculating Spearman's rho. Ideally this function would return a list of removed outliers, just like `correlation.skipped()` does.

**Edit** I haven't looked into the literature, but I would assume that the degrees of freedom of Shepherd's pi are `N – N_outliers – 1`, right? It could be helpful if the correlation functions were also to return the dof, then :)

**Comment by raphaelvallat** [comment]
Yes, I was planning on adding that at some point. With regards to the dof, please note that the `corr` wrapper function returns the sample size before outlier rejection. Perhaps the best option here would be to add an `outliers` column to the output dataframe (when using shepherd or skipped) with the number of outliers removed. I think that this would be more informative than simply having a `dof` column. What do you think? Thanks

**Comment by raphaelvallat** [comment]
Hi @hoechenberger! Just pushed to the develop branch the aforementioned changes. These will be included in the next release. Thanks again!
