### ISSUE TITLE
Friedman test raises ValuError when passing `within` as list

### ISSUE THREAD

**Issue by papr** [raphaelvallat/pingouin#82]
I originally came across this issue when I passed two `within` variables as a list.
> The Friedman test is used for one-way repeated measures ANOVA by ranks. [...]
> Note that if the dataset contains **one or more** other within subject factors, an **automatic collapsing** to the mean is applied on the dependant [sic] variable 

So, given this description I would assume that calling
```py
pg.friedman(test, dv="dv", subject="subject", within=["within_0", "within_1"])
```
should work, too. Unfortunately, this call fails at
[`data.groupby([subject, within]).mean().reset_index()`](https://github.com/raphaelvallat/pingouin/blob/master/pingouin/nonparametric.py#L583) since `within` is a `list` at that point and we basically are passing a nested list (e.g. `["subject", ["within_0", "within_1"]]`) to `data.groupby()`.

The same applies if a one-element list is passed as `within`.

See below for a full example + traceback.

<details>
<summary>Minimal example causing crash</summary>

```py
import pandas as pd
import pingouin as pg

subjects = pd.RangeIndex(100, name="subject")
test = pd.DataFrame({"dv": subjects / 2, "within_0": 0, "within_1": 1}, index=subjects)
test = test.reset_index()

pg.friedman(test, dv="dv", subject="subject", within=["within_0", "within_1"])
```
</details>

<details>
<summary>Traceback</summary>

```
~/.local/lib/python3.6/site-packages/pingouin/nonparametric.py in friedman(data, dv, within, subject)
    581 
    582     # Collapse to the mean
--> 583     data = data.groupby([subject, within]).mean().reset_index()
    584 
    585     # Remove NaN

~/.local/lib/python3.6/site-packages/pandas/core/frame.py in groupby(self, by, axis, level, as_index, sort, group_keys, squeeze, observed)
   5805             group_keys=group_keys,
   5806             squeeze=squeeze,
-> 5807             observed=observed,
   5808         )
   5809 

~/.local/lib/python3.6/site-packages/pandas/core/groupby/groupby.py in __init__(self, obj, keys, axis, level, grouper, exclusions, selection, as_index, sort, group_keys, squeeze, observed, mutated)
    407                 sort=sort,
    408                 observed=observed,
--> 409                 mutated=self.mutated,
    410             )
    411 

~/.local/lib/python3.6/site-packages/pandas/core/groupby/grouper.py in get_grouper(obj, key, axis, level, sort, observed, mutated, validate)
    623                 in_axis=in_axis,
    624             )
--> 625             if not isinstance(gpr, Grouping)
    626             else gpr
    627         )

~/.local/lib/python3.6/site-packages/pandas/core/groupby/grouper.py in __init__(self, index, grouper, obj, name, level, sort, observed, in_axis)
    254         self.name = name
    255         self.level = level
--> 256         self.grouper = _convert_grouper(index, grouper)
    257         self.all_grouper = None
    258         self.index = index

~/.local/lib/python3.6/site-packages/pandas/core/groupby/grouper.py in _convert_grouper(axis, grouper)
    653     elif isinstance(grouper, (list, Series, Index, np.ndarray)):
    654         if len(grouper) != len(axis):
--> 655             raise ValueError("Grouper and axis must be same length")
    656         return grouper
    657     else:

ValueError: Grouper and axis must be same length
```
</details>

**Comment by raphaelvallat** [comment]
Hi @papr,

In its current implementation, the Friedman test only works for _one-way_ repeated measures design, i.e. only one within-subject factor/variable. This is written in the Notes section of the docs: "The Friedman test is used for one-way repeated measures ANOVA by ranks.". However, I agree that the paragraph on automatic collapsing might be a bit misleading.

For action items, we can either:
1) Adapt the Friedman test to work with 2 within-factors (same behavior as pingouin.rm_anova); but I won't have the time to work on this in the next few weeks. If you do, please feel free to submit a PR.
2) Update the documentation to avoid any confusion on the number of factors.

Thanks,
Raphael

**Comment by papr** [comment]
Thank you for the quick response. I will try to implement it myself.
