### ISSUE TITLE
why return the absolute value of effect size in t-test ?

### ISSUE THREAD

**Issue by scilo7** [raphaelvallat/pingouin#86]
In pingouin.parametric.ttest, the cohen's d is transformed by round(abs(d), 3), thus loosing the way of the effect. Shouldn't it be returned with the sign ?
Thanks

**Comment by raphaelvallat** [comment]
Hi @scilo7,

Thanks for the issue. I did that because I figured most users care more about the magnitude of the effect size than the actual direction since this latter is already given by the signed T-value.

I don't really mind reverting back to a signed effect size though. What do people think?

Thanks

**Comment by manfred2020** [comment]
hi. for effect sizes it only the magnitude that counts. you want to know how small or large an effect is (-0.4 is the same size than +0.4, for exemple). for analyses on differences (anova, t-tests) i always saw absolute effect sizes.

the only effect sizes that come to my mind right know where -/+ is really valueable are measures of associaton, like correlation coefficients.

**Comment by scilo7** [comment]
Thanks for the responses. The sign seems important to me as I'm comparing my data to a reference group, so the sign also provides me the information if a factor has increased or decreased the results.

**Comment by raphaelvallat** [comment]
Thanks for your responses! I will wait until more people chime in. For now a quick fix would be to simply multiply the effect size by the sign of the T-values:

```
df_ttest['cohen-d'] = np.sign(df_ttest['T']) * df_ttest['cohen-d']
```

**Comment by manfred2020** [comment]
scilo7, so you're doing dependent t-tests?

**Comment by scilo7** [comment]
manfred2020: no, the groups are independant. For now I will use the T sign as mentionned above. Thanks

**Comment by manfred2020** [comment]
i see. well, for independent t-tests group coding is arbitrary (e.g. one may code male/female as 0/1 or as 1/0, it doesn't matter, you get the same result (with a + or - sign, depending on the coding)).

so for independent t-test +/- for cohens d or for the t value is absolutely arbitrary, only absolute numbers are important.

**Comment by raphaelvallat** [comment]
Closing this issue for now, but please feel free to reopen.
