### ISSUE TITLE
Modify assertion statement inside homoscedasticity function

### ISSUE THREAD

**Issue by apachaves** [raphaelvallat/pingouin#88]
Hi! Hope you're good during this pandemic times.

I was trying to run the `homoscedasticity()` function on my data and I got an **AssertionError** on the line related to the instance heritage checking. I thought it was my data so I tried to run the example code for One-Way ANOVA in the Guidelines page and I got the same error. I'm reporting here cause I believe it might be an issue to look at.

**Reproducible example (from [Guidelines](https://pingouin-stats.org/guidelines.html) page)**
```
# Load an example dataset comparing pain threshold as a function of hair color
df = pg.read_dataset('anova')

# 1. This is a between subject design, so the first step is to test for equality of variances
groups = df['Hair color'].unique()
a, b, c, d = [df.groupby('Hair color')['Pain threshold'].get_group(g).values for g in groups]
equal_var, pval = pg.homoscedasticity(a, b, c, d)

# 2. If the groups have equal variances, we can use a regular one-way ANOVA
pg.anova(data=df, dv='Pain threshold', between='Hair color')

# 3. If there is a main effect, we can proceed to post-hoc Tukey test
pg.pairwise_tukey(data=df, dv='Pain threshold', between='Hair color')
```

**Traceback (on my environment)**
```
AssertionError                            Traceback (most recent call last)
<command-4344134451870857> in <module>
      5 groups = df['Hair color'].unique()
      6 a, b, c, d = [df.groupby('Hair color')['Pain threshold'].get_group(g).values for g in groups]
----> 7 equal_var, pval = pg.homoscedasticity(a, b, c, d)
      8 
      9 # 2. If the groups have equal variances, we can use a regular one-way ANOVA

/databricks/python/lib/python3.7/site-packages/pingouin/distribution.py in homoscedasticity(data, dv, group, method, alpha)
    337     levene  3.192  0.079217       True
    338     """
--> 339     assert isinstance(data, (pd.DataFrame, list, dict))
    340     assert method.lower() in ['levene', 'bartlett']
    341     func = getattr(scipy.stats, method)
```

After double-checking myself with the code a bit, it seems that the result returned by the Pandas operation and assigned to a, b, c and d are from type **numpy.ndarray**, which makes sense because .values in Pandas has been returning a Numpy array most of the time (but not always, like in particular Pandas arrays, so this is why they added the method .to_numpy() to be explicit I believe).

Maybe a good modification would be to just include the possibility to work with **numpy.ndarray** if this is a desired behavior. And maybe a Pandas Series should be added too? I don't know exactly what should be the desired behavior for the API, but I would think this would be good inclusions. I don't know if you agree with me. In any case, I hope this issue could be of any help. I can also propose to do this small change and propose a pull request if you agree.

Best regards and stay safe!

**Comment by raphaelvallat** [comment]
Hi @apachaves !

Thanks for opening the issue, and first of all I hope that you and your loved ones are safe and healthy during these times!

Second, the issue here is in fact not with the function itself (which work well with pandas Series, NumPy array, etc), but with the Guidelines that were outdated and based on a previous version of Pingouin!

The following code should work:

```
# 1. This is a between subject design, so the first step is to test for equality of variances
groups = df['Hair color'].unique()
data_groups = [df.groupby('Hair color')['Pain threshold'].get_group(g).to_numpy() for g in groups]
pg.homoscedasticity(data_groups)
```

The important thing is that the [pingouin.homoscedasticity](https://pingouin-stats.org/generated/pingouin.homoscedasticity.html#pingouin.homoscedasticity) function requires either 1) a list of iterables (pandas Series, 1D array, list, etc), 2) a pandas DataFrame or 3) a dictionary, as you can see in the first lines in the function:

```
    assert isinstance(data, (pd.DataFrame, list, dict))
    assert method.lower() in ['levene', 'bartlett']
    func = getattr(scipy.stats, method)
    if isinstance(data, pd.DataFrame):
        # Data is a Pandas DataFrame
        if dv is None and group is None:
            # Wide-format
            # Get numeric data only
            numdata = data._get_numeric_data()
            assert numdata.shape[1] > 1, 'Data must have at least two columns.'
            statistic, p = func(*numdata.values)
        else:
            # Long-format
            assert group in data.columns
            assert dv in data.columns
            grp = data.groupby(group)[dv]
            assert grp.ngroups > 1, 'Data must have at least two columns.'
            statistic, p = func(*grp.apply(list))
    elif isinstance(data, list):
        # Check that list contains other list or np.ndarray
        assert all(isinstance(el, (list, np.ndarray)) for el in data)
        assert len(data) > 1, 'Data must have at least two iterables.'
        statistic, p = func(*data)
    else:
        # Data is a dict
        assert all(isinstance(el, (list, np.ndarray)) for el in data.values())
        assert len(data) > 1, 'Data must have at least two iterables.'
        statistic, p = func(*data.values())
```

I just updated the Guidelines section (b45596b45a2ebb3e0b8b9b506f166833bb37cd18). This will be apparent in the public documentation on the next release.

Thanks again!
Raphael

**Comment by apachaves** [comment]
Got it! Thank you for your kind words, for the patience and explanation.

And by the way, bravo for this project, it is very nice and something I really wanted to see. Plus it has a very beatiful and organized documentation. I will be following this proejct closely and wish the best to it!

Best wishes and keep yourself safe!

**Comment by raphaelvallat** [comment]
Thank you, I really appreciate it!
