### ISSUE TITLE
mixed_anova: ValueError: Grouper and axis must be same length

### ISSUE THREAD

**Issue by clementpoiret** [raphaelvallat/pingouin#89]
Hi Raphael,

I just saw that three way mixed anova isn't supported, leading to errors in the groupby call. Do you have any plans to support it?

Code to reproduce the error: 
```[python]
import pandas as pd
import pingouin as pg

data = pd.read_csv('./data.csv', sep=';')

aov = pg.mixed_anova(data=data,
                     dv='S_moy',
                     within='Lap',
                     between=['Sexe', 'Competition'],
                     subject='Nageur')
```

Thanks,
Clément.

**Comment by sappelhoff** [comment]
this was also recently in the Gitter chat, see: https://gitter.im/pingouin-stats/Lobby?at=5e66bacc80cc7b7924b3f7b9

**Comment by raphaelvallat** [comment]
Hi @clementpoiret ! As pointed out by @sappelhoff, 3-way designs are not yet supported. The mixed_anova function only accepts 2-way mixed design (one within and one between factor). I want at some point to have more than 2-ways but I doubt this will be implemented in the near future. For now, I'd recommend using R (e.g. ezANOVA package), or the JASP or JAMOVI free softwares. 

Thank you!

**Comment by clementpoiret** [comment]
Hi Raphael,

Thanks for your work, I'll take a look at ezANOVA.
