### ISSUE TITLE
Posthoc test for non parametric test.

### ISSUE THREAD

**Issue by Leicas** [raphaelvallat/pingouin#9]
Hi,
I like the simplicity of the library, especially running a Friedman test on a panda dataframe with one line is nice.

However due to the lack of posthoc test I have to use other library like Scikit-posthoc.
It would be nice to be able to use pingouin for that as well !

Best,

Antoine

**Comment by raphaelvallat** [comment]
Hi @Leicas!

You're absolutely right, I've been thinking of adding `pairwise_wilcoxon` and `pairwise_friedmann` functions for quite a bit of time now. The alternative would be to add a `parametric=[True/False]` option to the `pairwise_ttests` function, which would automatically choose between wilcoxon / friedman / paired T-test or independent T-test depending on the input data and arguments. Which option would you prefer? 

I'll include the changes in the next release of Pingouin (probably in March).

Thanks again,
Have a great day,
Raphael

**Comment by Leicas** [comment]
Both would be great, maybe the latest would simplify the use ?

Also wanted to thank you for the page at
https://pingouin-stats.org/guidelines.html, very clear and helpfull.

I'll be waiting for the next release then :)
Have a great day.

Antoine

Le ven. 15 févr. 2019 à 16:36, Raphael Vallat <notifications@github.com> a
écrit :

**Comment by raphaelvallat** [comment]
Hi @Leicas!

Just published the release 0.2.4 of Pingouin that includes non-parametric post-hoc tests! I am closing the issue. Thanks again for your input!

Raphael
