### ISSUE TITLE
part correlation with dummy variables

### ISSUE THREAD

**Issue by matanmazor** [raphaelvallat/pingouin#93]
Hey Raphael,

I'm getting an error message when trying to use partial_corr with a dummy variable:

`df = pd.DataFrame({'a':[0,1,2], 'b':['x','y','z'], 'c':[3, 4, 4]})`
`df = pd.get_dummies(df)`
`df.partial_corr(x='a',y='c',x_covar='b_x')`

I think the reason is that the output of get_dummies is uint8, because when I change it to int64 it all works fine. 

Thanks for this great tool!

**Comment by raphaelvallat** [comment]
Hi @matanmazor ! Thank you for noticing this! This is indeed related to the dtype check which should also allow for unsigned integer. I will update this in the next release. For now, as you pointed, a workaround is to convert to regular (signed) int64 with: `df.astype(np.int64)` or `pd.get_dummies(df, dtype=np.int64)`.

Thanks again!

**Comment by raphaelvallat** [comment]
Just made the changes on the develop branch (a955b76d8af462f00d6a47c8081c6ceea818df80). This will be released in the next stable version of Pingouin.
