### ISSUE TITLE
Problems in results from mixed ANOVAs

### ISSUE THREAD

**Issue by josea-rodas** [raphaelvallat/pingouin#98]
I was performing a set of 11 mixed ANOVAs and in two of them a negative F was reported with a p = 1. I re-analysed this data in JASP and got different results with a regular F and a very high p (<1).
The error can be replicated using the files I've attached. Both are csv files. Each include the set of data I am referring to. All other results were identical.

[file_1.txt](https://github.com/raphaelvallat/pingouin/files/4720527/file_1.txt)
[file_2.txt](https://github.com/raphaelvallat/pingouin/files/4720528/file_2.txt)

**Comment by raphaelvallat** [comment]
Hi @el-librero1800 , could you please provide a Python code or Jupyter Notebook replicating the error? I think this may be caused by missing values in your data, but I'll have to check. Thanks

**Comment by josea-rodas** [comment]
Hi @raphaelvallat, I just updated pingouin and re-run the analyses. All analyses are working fine now. Terribly sorry for not doing this before posting this issue! I thought I already had updated all my conda packages, but just realised pingouin updates differently. 
Thanks a lot! Love pingouin. Finally an easy way to do statistics in Python and have nice and complete output data.
